CREATE TABLE BOLDBI_AICredentials (
Id VARCHAR2(36) NOT NULL PRIMARY KEY,
AIModel NUMBER NOT NULL,
AIConfiguration VARCHAR2(4000) NULL,
CreatedById CHAR(38),
ModifiedById CHAR(38),
CreatedDate TIMESTAMP NOT NULL,
ModifiedDate TIMESTAMP NOT NULL,
IsActive NUMBER(1) NOT NULL,
IsAIModel NUMBER(1,0) DEFAULT 0 NOT NULL,
EnableAIFeature NUMBER(1,0) DEFAULT 0 NOT NULL,
IsAISummariesEnabledGlobally NUMBER(1,0) DEFAULT 0 NOT NULL
);
ALTER TABLE BOLDBI_ScheduleDetail ADD MultiExportType CLOB NULL;

ALTER TABLE BOLDBI_ScheduleDetail MODIFY ExportTypeId NULL;

ALTER TABLE BOLDBI_ItemView ADD IsWidgetLinking NUMBER(1, 0) DEFAULT 0 NOT NULL;

ALTER TABLE BOLDBI_ItemView MODIFY QueryString CLOB NOT NULL;