CREATE TABLE BOLDBI_ResourceFeatureAccess (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Name varchar(4000) NOT NULL,
    Type varchar(4000) NULL,
    IsActive NUMBER(1,0) NOT NULL
);
CREATE TABLE BOLDBI_ResourceFeatureAccEntity (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PermissionEntityId NUMBER NOT NULL,
    ResourceFeatureAccessId NUMBER NOT NULL,
    IsActive NUMBER(1,0) NOT NULL
);
CREATE TABLE BOLDBI_UserResourceFeaturePermission (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PermissionEntityId NUMBER NOT NULL,
    ResourceFeatureAccessJson varchar(4000) NOT NULL,
    ItemId varchar(4000) NULL,
    UserId NUMBER NOT NULL,
    ScopeGroupId NUMBER NULL,
    ItemTypeId NUMBER NULL,
    IsActive NUMBER(1,0) NOT NULL
);
CREATE TABLE BOLDBI_GroupResourceFeaturePermission (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PermissionEntityId NUMBER NOT NULL,
    ResourceFeatureAccessJson varchar(4000) NOT NULL,
    ItemId varchar(4000) NULL,
    GroupId NUMBER NOT NULL,
    ScopeGroupId NUMBER NULL,
    ItemTypeId NUMBER NULL,
    IsActive NUMBER(1,0) NOT NULL
);

INSERT into BOLDBI_ResourceFeatureAccess (Name,Type,IsActive) VALUES (N'Image',N'Export',1)
;
INSERT into BOLDBI_ResourceFeatureAccess (Name,Type,IsActive) VALUES (N'PDF',N'Export',1)
;
INSERT into BOLDBI_ResourceFeatureAccess (Name,Type,IsActive) VALUES (N'PPT',N'Export',1)
;
INSERT into BOLDBI_ResourceFeatureAccess (Name,Type,IsActive) VALUES (N'Excel',N'Export',1)
;
INSERT into BOLDBI_ResourceFeatureAccess (Name,Type,IsActive) VALUES (N'CSV',N'Export',1)
;
INSERT into BOLDBI_ResourceFeatureAccess (Name,Type,IsActive) VALUES (N'View Underlying Data',NULL,1)
;
INSERT into BOLDBI_ResourceFeatureAccess (Name,Type,IsActive) VALUES (N'Dashboard Parameters',NULL,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (12,1,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (13,1,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (14,1,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (12,2,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (13,2,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (14,2,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (12,3,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (13,3,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (14,3,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (12,4,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (13,4,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (14,4,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (12,5,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (13,5,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (14,5,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (12,6,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (13,6,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (14,6,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (12,7,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (13,7,1)
;
INSERT into BOLDBI_ResourceFeatureAccEntity (PermissionEntityId,ResourceFeatureAccessId,IsActive) VALUES (14,7,1)
;

ALTER TABLE BOLDBI_ResourceFeatureAccEntity ADD CONSTRAINT FK_ResourceFeatureAccEntity_PermissionEntity FOREIGN KEY (PermissionEntityId) REFERENCES BOLDBI_PermissionEntity (Id)
;
ALTER TABLE BOLDBI_ResourceFeatureAccEntity ADD CONSTRAINT FK_ResourceFeatureAccEntity_ResourceFeatureAccess FOREIGN KEY (ResourceFeatureAccessId) REFERENCES BOLDBI_ResourceFeatureAccess (Id)
;

ALTER TABLE BOLDBI_UserResourceFeaturePermission ADD CONSTRAINT FK_UserResourceFeaturePermission_PermissionEntity FOREIGN KEY (PermissionEntityId) REFERENCES BOLDBI_PermissionEntity (Id)
;
ALTER TABLE BOLDBI_UserResourceFeaturePermission ADD CONSTRAINT FK_UserResourceFeaturePermission_Item FOREIGN KEY (ItemId) REFERENCES BOLDBI_Item (Id)
;
ALTER TABLE BOLDBI_UserResourceFeaturePermission ADD CONSTRAINT FK_UserResourceFeaturePermission_User FOREIGN KEY (UserId) REFERENCES BOLDBI_User (Id)
;
ALTER TABLE BOLDBI_UserResourceFeaturePermission ADD CONSTRAINT FK_UserResourceFeaturePermission_SettingsType FOREIGN KEY (SettingsTypeId) REFERENCES BOLDBI_SettingsType (Id)
;
ALTER TABLE BOLDBI_UserResourceFeaturePermission ADD CONSTRAINT FK_UserResourceFeaturePermission_ScopeGroup FOREIGN KEY (ScopeGroupId) REFERENCES BOLDBI_Group (Id)
;
ALTER TABLE BOLDBI_UserResourceFeaturePermission ADD CONSTRAINT FK_UserResourceFeaturePermission_ItemType FOREIGN KEY (ItemTypeId) REFERENCES BOLDBI_ItemType (Id)
;

ALTER TABLE BOLDBI_GroupResourceFeaturePermission ADD CONSTRAINT FK_GroupResourceFeaturePermission_PermissionEntity FOREIGN KEY (PermissionEntityId) REFERENCES BOLDBI_PermissionEntity (Id)
;
ALTER TABLE BOLDBI_GroupResourceFeaturePermission ADD CONSTRAINT FK_GroupResourceFeaturePermission_Item FOREIGN KEY (ItemId) REFERENCES BOLDBI_Item (Id)
;
ALTER TABLE BOLDBI_GroupResourceFeaturePermission ADD CONSTRAINT FK_GroupResourceFeaturePermission_Group FOREIGN KEY (GroupId) REFERENCES BOLDBI_Group (Id)
;
ALTER TABLE BOLDBI_GroupResourceFeaturePermission ADD CONSTRAINT FK_GroupResourceFeaturePermission_SettingsType FOREIGN KEY (SettingsTypeId) REFERENCES BOLDBI_SettingsType (Id)
;
ALTER TABLE BOLDBI_GroupResourceFeaturePermission ADD CONSTRAINT FK_GroupResourceFeaturePermission_ScopeGroup FOREIGN KEY (ScopeGroupId) REFERENCES BOLDBI_Group (Id)
;
ALTER TABLE BOLDBI_GroupResourceFeaturePermission ADD CONSTRAINT FK_GroupResourceFeaturePermission_ItemType FOREIGN KEY (ItemTypeId) REFERENCES BOLDBI_ItemType (Id)
;
