ALTER TABLE BOLDBI_PublishType
ADD UNIQUE (Name);

ALTER TABLE BOLDBI_GroupLogType
ADD UNIQUE (Name);

ALTER TABLE BOLDBI_Item ADD DashboardLogo NVARCHAR2(1026);

ALTER TABLE BOLDBI_ScheduleDetail ADD AIInsightSummaryEnabled NUMBER(1, 0) DEFAULT 0 NOT NULL;

ALTER TABLE BOLDBI_AI_SESSIONS ADD ("RequestType" VARCHAR2(255),"SessionName" VARCHAR2(4000),"IsActive" NUMBER(1,0),"HistoryContent" VARCHAR2(4000),"SessionModifiedTime" TIMESTAMP WITH TIME ZONE);

ALTER TABLE BOLDBI_ItemLog ADD IPAddress NVARCHAR2(255);