INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsActive]) VALUES(N'Bold BI (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlaZ6433klELE9C2ksEgNSkUbKas8n/awQ/7tnUSvTFqmHPLQ+o18KSnsF7sIe5Qc/J6nkVeb7PH/U942NX/SVaioNSXqKAPBxE424ywY0gyh/flZxxpsjXWUFeB/ytKBkutJ5M4z/QT6Woo3g0lJy3XlQRRSr0712fNu+13qYWQ4Da+v5MYtS9brqazC63kx1gs/nk6UKXcyLzoYh5H9lhyPs96lcUYYzYMYPSHy30q3iIezoasj3/yODw+6HULaDRAPGrEosVc4MbY8KoZ9g+yS8oXB8VyVnKSCEp2uRbygA==', 15, 0, 1, GETDATE(), 1, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsActive]) VALUES(N'Bold BI On-Premise (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbkdkcJ0Dx5WooqYMhbaIraaIkeCwTmdeEGwPVKkX85afHfKmLcfUr5+nhK9vkeNYhQ51I41RFq0Sk0nKXxftxbH7bRmkA5WbmY0Bx5mna9O45I1n8lE2qcc0BKLFL/+ARVwtY+zgyhWLgn3vTcsrj9nUxROK+KamPACxxcN5FnQToZnsV/9gVaTpSNigdQuonqko9hhSN8NPJDngOAD8yLb4UHtr4SV4ilSVxg3nXsXG6CvZKUmClyXXzuzV1mPy7aQw6Y27oZxGUNNj0k+LuXV+vtqcmTVjea03jMmn3QfN1LLlKMZOK9lE0/+AyD7LI=', 15, 0, 3, GETDATE(), 1, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsActive]) VALUES(N'Bold Reports On-Premise (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdH0lN4e9YSrOWr8LYgiJK72/LT2XgtyCCX7V9KlYVP94MXr64wqM5T6CGNS7bVzTyvypJihWCOtYGf9/NNlQwBZv5KqolljXGvN9hoBsSdrg3cPuvqZmcpUAds61tPX6Xz/LvVec5oi7ftTRZs2yLrAL/gyjXt434NC4h6sMV+cnG8TUmM7ugM2MO5BHD9b1kXz6lfgVfl82aKecuJ50uRzPQ43yOU4aKxY+efndU6beXLoHbxCHHfFLarBpEnE+biY6VyAV8fxuaExujXy4xqw1nwleY9gKWjVDrjn7Cg7ycJBYLJWx1lez2rv3nWbjDo=', 15, 0, 4, GETDATE(), 1, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsActive]) VALUES (N'Bold Reports Viewer SDK (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdEzh1oY/yzboGRRvluxFlFdiYIa4alGN8Dd12GZyL9n451Gn/JR8ausXm1QWpw9tAhUr+1WWatyw1KIBGxNHIYJ/5C9dZK56VrA7KtPBsrOiwbfN+6fe+4dqed1eZ/1bbsRyodui+W36FHqS+VdLxBFULpIs5vtvDnSlHWMQmQReI5EUjURodvSUHdzL20FkNoyF3fN5F3l8nSAtqbIotGzuFbq1vBuZdE5mVfG2Tkp/hvubs+zDaKtZ8toHJEpQGkMAGxkh0HJq0/EaRUctpssNi3RN3/b0auJNTs4NJLUPhP/N2JdkppTxKwfWLf9Ca8=', 15, 0, 4, GETDATE(), 1, 1)


--development & staging product ids
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7927, N'Bold BI Annual Custom', 1, 44, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7928, N'Bold BI Annual Custom Subscription', 2, 44, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7929, N'Bold BI On-Premise Annual Custom', 1, 45, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7930, N'Bold BI On-Premise (Custom) Subscription', 2, 45, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7931, N'Bold Reports On-Premise Annual Custom', 1, 46, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7932, N'Bold Reports On-Premise Annual Custom Subscription', 2, 46, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7933, N'Bold Reports On-Premise Viewer SDK Annual Custom', 1, 47, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7934, N'Bold Reports On-Premise Viewer SDK Annual Custom Subscription', 2, 47, 1)

--production product ids - check with website team before using this query.
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7925, N'Bold BI Annual Custom', 1, 44, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7926, N'Bold BI Annual Custom Subscription', 2, 44, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7927, N'Bold BI On-Premise Annual Custom', 1, 45, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7928, N'Bold BI On-Premise (Custom) Subscription', 2, 45, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7929, N'Bold Reports On-Premise Annual Custom', 1, 46, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7930, N'Bold Reports On-Premise Annual Custom Subscription', 2, 46, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7931, N'Bold Reports On-Premise Viewer SDK Annual Custom', 1, 47, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7932, N'Bold Reports On-Premise Viewer SDK Annual Custom Subscription', 2, 47, 1)