-- BOLD_UPGRADE_CHECKPOINT_COVERED: true
-- BOLD_UPGRADE_STATEMENT_CHECKPOINT_VALIDATED: true
ALTER TABLE {database_name}.BOLDTC_AzureBlob MODIFY COLUMN Uri nvarchar(1024) NULL;

ALTER TABLE {database_name}.BOLDTC_TenantLog ADD OptionalData longtext NULL;
