//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.Dashboard.Connection.MicrosoftFabric.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.Dashboard.Connection.MicrosoftFabric.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS(SELECT {0} FROM {1} WHERE {2} ).
        /// </summary>
        internal static string AcosFunctionFormat {
            get {
                return ResourceManager.GetString("AcosFunctionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETWEEN.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTAINS.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom_Sort_Order_Table.
        /// </summary>
        internal static string CustomSortOrderTableAliasName {
            get {
                return ResourceManager.GetString("CustomSortOrderTableAliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDS WITH.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse relative date expression. Bad arguments.
        /// </summary>
        internal static string Err_FailToParseRelativeDateExpression {
            get {
                return ResourceManager.GetString("Err_FailToParseRelativeDateExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0} FROM ({1}) AS {2} WHERE {3} &gt;= {4} ORDER BY {5} ASC.
        /// </summary>
        internal static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTITION BY.
        /// </summary>
        internal static string PartitionBy {
            get {
                return ResourceManager.GetString("PartitionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEADD(ms, -DATEPART(ms, {0}), {1}).
        /// </summary>
        internal static string RemoveMilliSecondsFromDateTime {
            get {
                return ResourceManager.GetString("RemoveMilliSecondsFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ROW_NUMBER() OVER ({0} {1}) AS {2}.
        /// </summary>
        internal static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¤RowNumber.
        /// </summary>
        internal static string RowNumberColumnName {
            get {
                return ResourceManager.GetString("RowNumberColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROW_NUMBER.
        /// </summary>
        internal static string RowUnderscoreNumber {
            get {
                return ResourceManager.GetString("RowUnderscoreNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACOS.
        /// </summary>
        internal static string MicrosoftFabricAcos {
            get {
                return ResourceManager.GetString("MicrosoftFabricAcos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        internal static string MicrosoftFabricAnd {
            get {
                return ResourceManager.GetString("MicrosoftFabricAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND NOT.
        /// </summary>
        internal static string MicrosoftFabricAndNot {
            get {
                return ResourceManager.GetString("MicrosoftFabricAndNot", resourceCulture);
            }
        }

        internal static string MicrosoftFabricAndGroup
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricAndGroup", resourceCulture);
            }
        }
        internal static string MicrosoftFabricOrGroup
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricOrGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AS.
        /// </summary>
        internal static string MicrosoftFabricAs {
            get {
                return ResourceManager.GetString("MicrosoftFabricAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC.
        /// </summary>
        internal static string MicrosoftFabricAsc {
            get {
                return ResourceManager.GetString("MicrosoftFabricAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASIN.
        /// </summary>
        internal static string MicrosoftFabricAsin {
            get {
                return ResourceManager.GetString("MicrosoftFabricAsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG.
        /// </summary>
        internal static string MicrosoftFabricAvg {
            get {
                return ResourceManager.GetString("MicrosoftFabricAvg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVGD.
        /// </summary>
        internal static string MicrosoftFabricAvgD
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricAvgD", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to BEGIN SELECT {0} FROM {1} END ELSE BEGIN SELECT TOP 1({0}) FROM {1} END.
        /// </summary>
        internal static string MicrosoftFabricBeginFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricBeginFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETWEEN {0} AND {1}.
        /// </summary>
        internal static string MicrosoftFabricBetweenFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricBetweenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIGINT.
        /// </summary>
        internal static string MicrosoftFabricBigInt {
            get {
                return ResourceManager.GetString("MicrosoftFabricBigInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BINARY.
        /// </summary>
        internal static string MicrosoftFabricBinary {
            get {
                return ResourceManager.GetString("MicrosoftFabricBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIT.
        /// </summary>
        internal static string MicrosoftFabricBit {
            get {
                return ResourceManager.GetString("MicrosoftFabricBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VarBinary.
        /// </summary>
        internal static string MicrosoftFabricByte {
            get {
                return ResourceManager.GetString("MicrosoftFabricByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE.
        /// </summary>
        internal static string MicrosoftFabricCase {
            get {
                return ResourceManager.GetString("MicrosoftFabricCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} THEN {1} ELSE {2} END.
        /// </summary>
        internal static string MicrosoftFabricCaseWhenElseFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricCaseWhenElseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST.
        /// </summary>
        internal static string MicrosoftFabricCast {
            get {
                return ResourceManager.GetString("MicrosoftFabricCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST( {0} AS {1} ).
        /// </summary>
        internal static string MicrosoftFabricCastFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricCastFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEIL.
        /// </summary>
        internal static string MicrosoftFabricCeil {
            get {
                return ResourceManager.GetString("MicrosoftFabricCeil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAR.
        /// </summary>
        internal static string MicrosoftFabricChar {
            get {
                return ResourceManager.GetString("MicrosoftFabricChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string MicrosoftFabricComparisonFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricComparisonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} THEN {1} ELSE NULL END.
        /// </summary>
        internal static string MicrosoftFabricConditionalConversionFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricConditionalConversionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is broken and recovery is not possible.  The client driver attempted to recover the connection one or more times and all attempts failed.  Increase the value of ConnectRetryCount to increase the number of recovery attempts..
        /// </summary>
        internal static string MicrosoftFabricConnectionFailException {
            get {
                return ResourceManager.GetString("MicrosoftFabricConnectionFailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} like {1} THEN 1 ELSE 0 END.
        /// </summary>
        internal static string MicrosoftFabricContainsFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricContainsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT(VARCHAR, CAST({0} AS DATE), 112).
        /// </summary>
        internal static string MicrosoftFabricConvertCastDateFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricConvertCastDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT(VARCHAR(8), {0}, 112).
        /// </summary>
        internal static string MicrosoftFabricConvertFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricConvertFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT(VARCHAR(8), {0}, 108).
        /// </summary>
        internal static string MicrosoftFabricConvertFormat_Time {
            get {
                return ResourceManager.GetString("MicrosoftFabricConvertFormat_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT( {0} , {1} ).
        /// </summary>
        internal static string MicrosoftFabricConvertFunction {
            get {
                return ResourceManager.GetString("MicrosoftFabricConvertFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT(REPLACE(CONVERT(VARCHAR(8), CAST({0} AS DATETIME), 114),&apos;:&apos;,&apos;&apos;),6).
        /// </summary>
        internal static string MicrosoftFabricConvertTimeFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricConvertTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        internal static string MicrosoftFabricCount {
            get {
                return ResourceManager.GetString("MicrosoftFabricCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT(*).
        /// </summary>
        internal static string MicrosoftFabricCountAll {
            get {
                return ResourceManager.GetString("MicrosoftFabricCountAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Count_BIG.
        /// </summary>
        internal static string MicrosoftFabricCount_Big
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricCount_Big", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COUNTD.
        /// </summary>
        internal static string MicrosoftFabricCountD {
            get {
                return ResourceManager.GetString("MicrosoftFabricCountD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE {0} ( {1} );.
        /// </summary>
        internal static string MicrosoftFabricCreateTableFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricCreateTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART(month, CAST(GETDATE() AS DATE)).
        /// </summary>
        internal static string MicrosoftFabricCurrentmonth {
            get {
                return ResourceManager.GetString("MicrosoftFabricCurrentmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART(year, CAST(GETDATE() AS DATE)).
        /// </summary>
        internal static string MicrosoftFabricCurrentyear {
            get {
                return ResourceManager.GetString("MicrosoftFabricCurrentyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string MicrosoftFabricDate {
            get {
                return ResourceManager.GetString("MicrosoftFabricDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEADD.
        /// </summary>
        internal static string MicrosoftFabricDateAdd {
            get {
                return ResourceManager.GetString("MicrosoftFabricDateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEDIFF.
        /// </summary>
        internal static string MicrosoftFabricDateDiff {
            get {
                return ResourceManager.GetString("MicrosoftFabricDateDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART.
        /// </summary>
        internal static string MicrosoftFabricDatePart {
            get {
                return ResourceManager.GetString("MicrosoftFabricDatePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIME.
        /// </summary>
        internal static string MicrosoftFabricDatetime {
            get {
                return ResourceManager.GetString("MicrosoftFabricDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIME2.
        /// </summary>
        internal static string MicrosoftFabricDateTime2 {
            get {
                return ResourceManager.GetString("MicrosoftFabricDateTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIMEOFFSET.
        /// </summary>
        internal static string MicrosoftFabricDateTimeOffset {
            get {
                return ResourceManager.GetString("MicrosoftFabricDateTimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY.
        /// </summary>
        internal static string MicrosoftFabricDay {
            get {
                return ResourceManager.GetString("MicrosoftFabricDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAYOFYEAR.
        /// </summary>
        internal static string MicrosoftFabricDayOfYear {
            get {
                return ResourceManager.GetString("MicrosoftFabricDayOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECIMAL.
        /// </summary>
        internal static string MicrosoftFabricDecimal {
            get {
                return ResourceManager.GetString("MicrosoftFabricDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE.
        /// </summary>
        internal static string MicrosoftFabricDeclare {
            get {
                return ResourceManager.GetString("MicrosoftFabricDeclare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}( {3} ).
        /// </summary>
        internal static string MicrosoftFabricDeclareTableFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricDeclareTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000-0000-0000-0000-000000000000.
        /// </summary>
        internal static string MicrosoftFabricDefaultGuid {
            get {
                return ResourceManager.GetString("MicrosoftFabricDefaultGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESC.
        /// </summary>
        internal static string MicrosoftFabricDesc {
            get {
                return ResourceManager.GetString("MicrosoftFabricDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        internal static string MicrosoftFabricDifferent {
            get {
                return ResourceManager.GetString("MicrosoftFabricDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTINCT.
        /// </summary>
        internal static string MicrosoftFabricDistinct {
            get {
                return ResourceManager.GetString("MicrosoftFabricDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE {0}.
        /// </summary>
        internal static string MicrosoftFabricDropTableFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricDropTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELSE.
        /// </summary>
        internal static string MicrosoftFabricElse {
            get {
                return ResourceManager.GetString("MicrosoftFabricElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END.
        /// </summary>
        internal static string MicrosoftFabricEnd {
            get {
                return ResourceManager.GetString("MicrosoftFabricEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string MicrosoftFabricEquals {
            get {
                return ResourceManager.GetString("MicrosoftFabricEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC.
        /// </summary>
        internal static string MicrosoftFabricExec {
            get {
                return ResourceManager.GetString("MicrosoftFabricExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLOAT.
        /// </summary>
        internal static string MicrosoftFabricFloat {
            get {
                return ResourceManager.GetString("MicrosoftFabricFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMAT( {0} ).
        /// </summary>
        internal static string MicrosoftFabricFormatFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricFormatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        internal static string MicrosoftFabricFrom {
            get {
                return ResourceManager.GetString("MicrosoftFabricFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL.
        /// </summary>
        internal static string MicrosoftFabricFull {
            get {
                return ResourceManager.GetString("MicrosoftFabricFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}).
        /// </summary>
        internal static string MicrosoftFabricFunctionFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricFunctionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOGRAPHY.
        /// </summary>
        internal static string MicrosoftFabricGeography {
            get {
                return ResourceManager.GetString("MicrosoftFabricGeography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOMETRY.
        /// </summary>
        internal static string MicrosoftFabricGeometry {
            get {
                return ResourceManager.GetString("MicrosoftFabricGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string MicrosoftFabricGreaterOrEquals {
            get {
                return ResourceManager.GetString("MicrosoftFabricGreaterOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string MicrosoftFabricGreaterThan {
            get {
                return ResourceManager.GetString("MicrosoftFabricGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP BY.
        /// </summary>
        internal static string MicrosoftFabricGroupBy {
            get {
                return ResourceManager.GetString("MicrosoftFabricGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAVING.
        /// </summary>
        internal static string MicrosoftFabricHaving {
            get {
                return ResourceManager.GetString("MicrosoftFabricHaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIERARCHYID.
        /// </summary>
        internal static string MicrosoftFabricHierarchyId {
            get {
                return ResourceManager.GetString("MicrosoftFabricHierarchyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOUR.
        /// </summary>
        internal static string MicrosoftFabricHour {
            get {
                return ResourceManager.GetString("MicrosoftFabricHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE.
        /// </summary>
        internal static string MicrosoftFabricImage {
            get {
                return ResourceManager.GetString("MicrosoftFabricImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN( {0} ).
        /// </summary>
        internal static string MicrosoftFabricInFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER.
        /// </summary>
        internal static string MicrosoftFabricInner {
            get {
                return ResourceManager.GetString("MicrosoftFabricInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER JOIN.
        /// </summary>
        internal static string MicrosoftFabricInnerJoin {
            get {
                return ResourceManager.GetString("MicrosoftFabricInnerJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        internal static string MicrosoftFabricInsert {
            get {
                return ResourceManager.GetString("MicrosoftFabricInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4}.
        /// </summary>
        internal static string MicrosoftFabricInsertExecFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricInsertExecFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0} VALUES ( {1} ).
        /// </summary>
        internal static string MicrosoftFabricInsertIntoFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricInsertIntoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * INTO {0} FROM ( {1} ) AS QUERY.
        /// </summary>
        internal static string MicrosoftFabricInsertIntoFromQueryFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricInsertIntoFromQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        internal static string MicrosoftFabricInt {
            get {
                return ResourceManager.GetString("MicrosoftFabricInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT32.
        /// </summary>
        internal static string MicrosoftFabricInt32 {
            get {
                return ResourceManager.GetString("MicrosoftFabricInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT64.
        /// </summary>
        internal static string MicrosoftFabricInt64 {
            get {
                return ResourceManager.GetString("MicrosoftFabricInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        internal static string MicrosoftFabricIs {
            get {
                return ResourceManager.GetString("MicrosoftFabricIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDATE( {0} ) = 1.
        /// </summary>
        internal static string MicrosoftFabricIsDateFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricIsDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS NOT NULL.
        /// </summary>
        internal static string MicrosoftFabricIsNotNull {
            get {
                return ResourceManager.GetString("MicrosoftFabricIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS NULL.
        /// </summary>
        internal static string MicrosoftFabricIsNull {
            get {
                return ResourceManager.GetString("MicrosoftFabricIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISNULL.
        /// </summary>
        internal static string MicrosoftFabricIsNullFunction {
            get {
                return ResourceManager.GetString("MicrosoftFabricIsNullFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISNUMERIC( {0} ) = 1.
        /// </summary>
        internal static string MicrosoftFabricIsNumberFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricIsNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN.
        /// </summary>
        internal static string MicrosoftFabricJoin {
            get {
                return ResourceManager.GetString("MicrosoftFabricJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT OUTER.
        /// </summary>
        internal static string MicrosoftFabricLeft {
            get {
                return ResourceManager.GetString("MicrosoftFabricLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CROSS JOIN.
        /// </summary>
        internal static string MicrosoftFabricCross
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricCross", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LEFT JOIN.
        /// </summary>
        internal static string MicrosoftFabricLeftJoin {
            get {
                return ResourceManager.GetString("MicrosoftFabricLeftJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string MicrosoftFabricLessOrEquals {
            get {
                return ResourceManager.GetString("MicrosoftFabricLessOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string MicrosoftFabricLessThan {
            get {
                return ResourceManager.GetString("MicrosoftFabricLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIKE.
        /// </summary>
        internal static string MicrosoftFabricLike {
            get {
                return ResourceManager.GetString("MicrosoftFabricLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} LIKE {1}.
        /// </summary>
        internal static string MicrosoftFabricLikeFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricLikeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        internal static string MicrosoftFabricMax {
            get {
                return ResourceManager.GetString("MicrosoftFabricMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        internal static string MicrosoftFabricMin {
            get {
                return ResourceManager.GetString("MicrosoftFabricMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINUTE.
        /// </summary>
        internal static string MicrosoftFabricMinute {
            get {
                return ResourceManager.GetString("MicrosoftFabricMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD.
        /// </summary>
        internal static string MicrosoftFabricMod {
            get {
                return ResourceManager.GetString("MicrosoftFabricMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY.
        /// </summary>
        internal static string MicrosoftFabricMoney {
            get {
                return ResourceManager.GetString("MicrosoftFabricMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTH.
        /// </summary>
        internal static string MicrosoftFabricMonth {
            get {
                return ResourceManager.GetString("MicrosoftFabricMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCHAR.
        /// </summary>
        internal static string MicrosoftFabricNChar {
            get {
                return ResourceManager.GetString("MicrosoftFabricNChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        internal static string MicrosoftFabricNot {
            get {
                return ResourceManager.GetString("MicrosoftFabricNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT BETWEEN {0} AND {1}.
        /// </summary>
        internal static string MicrosoftFabricNotBetweenFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricNotBetweenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GETDATE().
        /// </summary>
        internal static string MicrosoftFabricNow {
            get {
                return ResourceManager.GetString("MicrosoftFabricNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTEXT.
        /// </summary>
        internal static string MicrosoftFabricNText {
            get {
                return ResourceManager.GetString("MicrosoftFabricNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string MicrosoftFabricNull {
            get {
                return ResourceManager.GetString("MicrosoftFabricNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMERIC.
        /// </summary>
        internal static string MicrosoftFabricNumeric {
            get {
                return ResourceManager.GetString("MicrosoftFabricNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVARCHAR.
        /// </summary>
        internal static string MicrosoftFabricNVarchar {
            get {
                return ResourceManager.GetString("MicrosoftFabricNVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string MicrosoftFabricOn {
            get {
                return ResourceManager.GetString("MicrosoftFabricOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string MicrosoftFabricOr {
            get {
                return ResourceManager.GetString("MicrosoftFabricOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY.
        /// </summary>
        internal static string MicrosoftFabricOrderBy {
            get {
                return ResourceManager.GetString("MicrosoftFabricOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR NOT.
        /// </summary>
        internal static string MicrosoftFabricOrNot {
            get {
                return ResourceManager.GetString("MicrosoftFabricOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTER.
        /// </summary>
        internal static string MicrosoftFabricOuter {
            get {
                return ResourceManager.GetString("MicrosoftFabricOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVER.
        /// </summary>
        internal static string MicrosoftFabricOver {
            get {
                return ResourceManager.GetString("MicrosoftFabricOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0}({1}) FROM(SELECT TOP({2}) {1} FROM {3}) AS RESULT.
        /// </summary>
        internal static string MicrosoftFabricPagingRunningQuery {
            get {
                return ResourceManager.GetString("MicrosoftFabricPagingRunningQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}().
        /// </summary>
        internal static string MicrosoftFabricParameterLessFunctionFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricParameterLessFunctionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART(month, DATEADD(month, -1, CAST(GETDATE() AS DATE))).
        /// </summary>
        internal static string MicrosoftFabricPreviousmonth {
            get {
                return ResourceManager.GetString("MicrosoftFabricPreviousmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART(year, DATEADD(year, -1, CAST(GETDATE() AS DATE))).
        /// </summary>
        internal static string MicrosoftFabricPreviousyear {
            get {
                return ResourceManager.GetString("MicrosoftFabricPreviousyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUARTER.
        /// </summary>
        internal static string MicrosoftFabricQuarter {
            get {
                return ResourceManager.GetString("MicrosoftFabricQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL.
        /// </summary>
        internal static string MicrosoftFabricReal {
            get {
                return ResourceManager.GetString("MicrosoftFabricReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE {0};.
        /// </summary>
        internal static string MicrosoftFabricRemoveTableFormat {
            get {
                return ResourceManager.GetString("MicrosoftFabricRemoveTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        internal static string MicrosoftFabricRight {
            get {
                return ResourceManager.GetString("MicrosoftFabricRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOND.
        /// </summary>
        internal static string MicrosoftFabricSecond {
            get {
                return ResourceManager.GetString("MicrosoftFabricSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        internal static string MicrosoftFabricSelect {
            get {
                return ResourceManager.GetString("MicrosoftFabricSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMALLDATETIME.
        /// </summary>
        internal static string MicrosoftFabricSmallDateTime {
            get {
                return ResourceManager.GetString("MicrosoftFabricSmallDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMALLINT.
        /// </summary>
        internal static string MicrosoftFabricSmallInt {
            get {
                return ResourceManager.GetString("MicrosoftFabricSmallInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMALLMONEY.
        /// </summary>
        internal static string MicrosoftFabricSmallMoney {
            get {
                return ResourceManager.GetString("MicrosoftFabricSmallMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicrosoftFabric_VARIANT.
        /// </summary>
        internal static string MicrosoftFabric_Variant {
            get {
                return ResourceManager.GetString("MicrosoftFabricMicrosoftFabric_Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string MicrosoftFabricStar {
            get {
                return ResourceManager.GetString("MicrosoftFabricStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDEV.
        /// </summary>
        internal static string MicrosoftFabricStdev {
            get {
                return ResourceManager.GetString("MicrosoftFabricStdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDEVP.
        /// </summary>
        internal static string MicrosoftFabricStdevP {
            get {
                return ResourceManager.GetString("MicrosoftFabricStdevP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSTRING.
        /// </summary>
        internal static string MicrosoftFabricSubstring {
            get {
                return ResourceManager.GetString("MicrosoftFabricSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string MicrosoftFabricSum {
            get {
                return ResourceManager.GetString("MicrosoftFabricSum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string MicrosoftFabricSumD
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricSumD", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ¤Super_Query.
        /// </summary>
        internal static string MicrosoftFabricSuperQuery {
            get {
                return ResourceManager.GetString("MicrosoftFabricSuperQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE.
        /// </summary>
        internal static string MicrosoftFabricTable {
            get {
                return ResourceManager.GetString("MicrosoftFabricTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT.
        /// </summary>
        internal static string MicrosoftFabricText {
            get {
                return ResourceManager.GetString("MicrosoftFabricText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THEN.
        /// </summary>
        internal static string MicrosoftFabricThen {
            get {
                return ResourceManager.GetString("MicrosoftFabricThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        internal static string MicrosoftFabricTime {
            get {
                return ResourceManager.GetString("MicrosoftFabricTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMESTAMP.
        /// </summary>
        internal static string MicrosoftFabricTimeStamp {
            get {
                return ResourceManager.GetString("MicrosoftFabricTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TINYINT.
        /// </summary>
        internal static string MicrosoftFabricTinyInt {
            get {
                return ResourceManager.GetString("MicrosoftFabricTinyInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP.
        /// </summary>
        internal static string MicrosoftFabricTop {
            get {
                return ResourceManager.GetString("MicrosoftFabricTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP (1).
        /// </summary>
        internal static string MicrosoftFabricTopOne {
            get {
                return ResourceManager.GetString("MicrosoftFabricTopOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNION ALL.
        /// </summary>
        internal static string MicrosoftFabricUnionAll {
            get {
                return ResourceManager.GetString("MicrosoftFabricUnionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIQUEIDENTIFIER.
        /// </summary>
        internal static string MicrosoftFabricUniqueIdentifier {
            get {
                return ResourceManager.GetString("MicrosoftFabricUniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR.
        /// </summary>
        internal static string MicrosoftFabricVar {
            get {
                return ResourceManager.GetString("MicrosoftFabricVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARBINARY.
        /// </summary>
        internal static string MicrosoftFabricVarBinary {
            get {
                return ResourceManager.GetString("MicrosoftFabricVarBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARCHAR.
        /// </summary>
        internal static string MicrosoftFabricVarChar {
            get {
                return ResourceManager.GetString("MicrosoftFabricVarChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARP.
        /// </summary>
        internal static string MicrosoftFabricVarP {
            get {
                return ResourceManager.GetString("MicrosoftFabricVarP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEK.
        /// </summary>
        internal static string MicrosoftFabricWeek {
            get {
                return ResourceManager.GetString("MicrosoftFabricWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEKDAY.
        /// </summary>
        internal static string MicrosoftFabricWeekDay {
            get {
                return ResourceManager.GetString("MicrosoftFabricWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN.
        /// </summary>
        internal static string MicrosoftFabricWhen {
            get {
                return ResourceManager.GetString("MicrosoftFabricWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE.
        /// </summary>
        internal static string MicrosoftFabricWhere {
            get {
                return ResourceManager.GetString("MicrosoftFabricWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH.
        /// </summary>
        internal static string MicrosoftFabricWith {
            get {
                return ResourceManager.GetString("MicrosoftFabricWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string MicrosoftFabricXml {
            get {
                return ResourceManager.GetString("MicrosoftFabricXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        internal static string MicrosoftFabricYear {
            get {
                return ResourceManager.GetString("MicrosoftFabricYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEADD(day, -1, CAST(GETDATE() AS DATE)).
        /// </summary>
        internal static string MicrosoftFabricYesterday {
            get {
                return ResourceManager.GetString("MicrosoftFabricYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARTS WITH.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT * FROM OPENQUERY([{0}],&apos;EXEC [{1}].[{2}].[{3}]&apos;)) [{3}].
        /// </summary>
        internal static string StoredProcedureWithOutParameter {
            get {
                return ResourceManager.GetString("StoredProcedureWithOutParameter", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to (SELECT TOP {4} * FROM OPENQUERY([{0}],&apos;EXEC [{1}].[{2}].[{3}]&apos;)) [{3}].
        /// </summary>
        internal static string StoredProcedureWithOutParameterforDataSampling {
            get {
                return ResourceManager.GetString("StoredProcedureWithOutParameterforDataSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT * FROM OPENQUERY([{0}],&apos;EXEC [{1}].[{2}].[{3}]  {4}&apos;)) [{3}].
        /// </summary>
        internal static string StoredProcedureWithParameter {
            get {
                return ResourceManager.GetString("StoredProcedureWithParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT TOP {5} * FROM OPENQUERY([{0}],&apos;EXEC [{1}].[{2}].[{3}]  {4}&apos;)) [{3}].
        /// </summary>
        internal static string StoredProcedureWithParameterforDataSampling {
            get {
                return ResourceManager.GetString("StoredProcedureWithParameterforDataSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNSUPPORT.
        /// </summary>
        internal static string UnSupport {
            get {
                return ResourceManager.GetString("UnSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        internal static string YearFormatCount {
            get {
                return ResourceManager.GetString("YearFormatCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to restrict Order By clause in query string unless TOP, OFFSET, or FOR XML is also specified.
        /// </summary>
        internal static string RestrictOrderByErrorMessage
        {
            get
            {
                return ResourceManager.GetString("RestrictOrderByErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FETCH NEXT {0} ROWS ONLY.
        /// </summary>
        internal static string MicrosoftFabricFetch
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OFFSET {0} ROWS .
        /// </summary>
        internal static string MicrosoftFabricOffset
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricOffset", resourceCulture);
            }
        }
        
        // <summary>
        ///   Looks up a localized string similar to TOTALPERCENTAGE.
        /// </summary>
        internal static string MicrosoftFabricTotalPercentage
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricTotalPercentage", resourceCulture);
            }
        }
        
        // <summary>
        ///   Looks up a localized string similar to  STRING_AGG.
        /// </summary>
        internal static string MicrosoftFabricStringAgg
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricStringAgg", resourceCulture);
            }
        }
        
        // <summary>
        ///   Looks up a localized string similar to MicrosoftFabricFiscalQuarter
        /// </summary>
        internal static string MicrosoftFabricFiscalQuarter
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricFiscalQuarter", resourceCulture);
            }
        }

        // <summary>
        ///   Looks up a localized string similar to MicrosoftFabricFiscalQuarter
        /// </summary>
        internal static string MicrosoftFabricFiscalQuarterYear
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricFiscalQuarterYear", resourceCulture);
            }
        }

        // <summary>
        ///   Looks up a localized string similar to MicrosoftFabricFiscalQuarter
        /// </summary>
        internal static string MicrosoftFabricFiscalMonthYear
        {
            get
            {
                return ResourceManager.GetString("MicrosoftFabricFiscalMonthYear", resourceCulture);
            }
        }
    }
}
