ALTER TABLE BOLDTC_TenantInactivity ADD COLUMN CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE BOLDTC_TenantInactivity ADD COLUMN ModifiedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;