CREATE TABLE IF NOT EXISTS BOLDTC_BackUp (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ConfigurationData LONGTEXT NOT NULL,
    PrivateKey LONGTEXT NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IsActive TINYINT NOT NULL
);