CREATE TABLE [BOLDTC_ConnectionTest] (
	Id int IDENTITY(1,1) NOT NULL,
	Name nvarchar(max) NOT NULL,
  CONSTRAINT PK_BOLDTC_CONNECTIONTEST PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)
;