ALTER TABLE SyncDS_Item ADD COLUMN DashboardLogo varchar(1026) NULL;

ALTER TABLE SyncDS_ScheduleDetail ADD COLUMN AIInsightSummaryEnabled SMALLINT DEFAULT 0 NOT NULL;

ALTER TABLE SyncDS_AI_SESSIONS ADD COLUMN RequestType TEXT,ADD COLUMN SessionName TEXT,ADD COLUMN IsActive BOOLEAN,ADD COLUMN HistoryContent TEXT,ADD COLUMN SessionModifiedTime TIMESTAMP WITH TIME ZONE;

ALTER TABLE SyncDS_ItemLog ADD COLUMN IPAddress varchar(255) NULL;