update [DirectoryType] set [DirectoryName] = 'AzureADFS' where id = '2'
update [DirectoryType] set [DirectoryName] = 'WindowsAD' where id = '5'

INSERT into [DirectoryType] (DirectoryName,IsActive) VALUES (N'Syncfusion',1)
INSERT into [DirectoryType] (DirectoryName,IsActive) VALUES (N'OAuth2',1)
INSERT into [DirectoryType] (DirectoryName,IsActive) VALUES (N'OpenIDConnect',1)
INSERT into [DirectoryType] (DirectoryName,IsActive) VALUES (N'LinkedIn',1)
INSERT into [DirectoryType] (DirectoryName,IsActive) VALUES (N'Google',1)
INSERT into [DirectoryType] (DirectoryName,IsActive) VALUES (N'GitHub',1)
INSERT into [DirectoryType] (DirectoryName,IsActive) VALUES (N'Facebook',1)
INSERT into [DirectoryType] (DirectoryName,IsActive) VALUES (N'Twitter',1)

update [User] set [DirectoryTypeId] = '6' where DirectoryTypeId = '5'
update [UserLogin] set [DirectoryTypeId] = '6' where DirectoryTypeId = '5'

ALTER TABLE [TenantInfo] ADD [Quantity] int NOT NULL CONSTRAINT df_Quantity default 1
ALTER TABLE [CustomPlan] ADD [PricePerLicense] int Null

ALTER TABLE [SqlServer] ADD [StorageAccountName] nvarchar(255) NULL, [StorageAccountAccessKey] nvarchar(max) NULL, [ResourceGroupName] nvarchar(255) NULL, [AzureTagKey] nvarchar(50) NULL, [AzureTagValue] nvarchar(50) NULL;

ALTER TABLE [SaasPlan] ADD [IsArchived] BIT NOT NULL DEFAULT 0;

INSERT [dbo].[SourceType]([Name], [URL], [ModifiedDate], [IsActive]) VALUES(N'ReportServer', N'', getdate(), 1)

INSERT INTO [SqlServer] ([ServerName],[UserName],[Password],[DatabaseLimit],[SqlServerType],[TenantType],[StorageAccountName],[StorageAccountAccessKey],[ResourceGroupName],[AzureTagKey],[AzureTagValue],[IsAvailable],[IsActive]) VALUES (N'',N'',N'',3900,1,2,N'',N'',N'',N'',N'',N'True',N'True');
GO
INSERT INTO [SqlElasticPool] ([PoolName],[SqlServerId],[DatabaseLimit],[SqlServerType],[TenantType],[IsAvailable],[IsActive]) VALUES (N'',1,95,1,2,N'True',N'True');
GO

UPDATE [SqlServer] SET [StorageAccountName] = '', [StorageAccountAccessKey] = '', [ResourceGroupName] = '', [AzureTagKey] = '',[AzureTagValue] = '' WHERE [TenantType] = '1'

UPDATE [SaasPlan] SET [Name] = 'Bold BI Enterprise (Custom)', [PlanSchema] = 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+PgzjVR9TTeqMcZDzNi8PUcl8S9L30vto2eVpL0pHlAqVYu9+RWpGIj1SdTgZS2abXGqJqtoTb87jqblB96+npLqViUSet+4zm4UA3r6SuITl/cwZB+0X8QDZHW98wPu2ND0225jjv2dQbbmt7Pbkl3NlQOd0Kug92CxGYjmrhlo6U98yGQUTfnQZ6YTWemDbvEMpDpdbX8PVOqqup+e3pI3F6TnUkt584QD+mwcjhJFOITNaHsUk2HT59eWejkcC8C32LrGJraiWOi64ktlg2YMqTfLQBEALz3fklnMokJYqXfZpfbX36CXswoa5OQXRstlOzi0dHfalV8DxCdHlquUJZwm7nM6YR1jGrf5Ppbg5E35Nz6IIhj9gHS6gY1/D8C5PPk99yKPYiGL+zYiNwqhn9vDdb5ByfigYKiIKOtRRrR+TdoU2To/ZcEl5pWy3HV9REx2S8KNg2qB3QH0G0JVbdGnbeIgVfIm50vXIatCnbznYWSLFoaQKSbBUTgV/yHP4XOwvQpimpIJ2NCMruNZkGeFp/NdGBFiOKeNMaCVUBVFjE2CEXOkFF5oSELbMzVgg3YbZCePYoSyyg6gPeJUM841QQSOSNCjU3RlG5K+8Mz+lCyrYATMyuXSGARw/vbchFwjv/zlj/qXLM5Ja6trXsikizDDV7nOETb5Ck2DhAKrGD5ntHyitCeUlErll9fU+jc3c3Hre/QWyIAv+ERPhJ/6aTaYlpeRITD+ImKUYPgzwoHtNbG728ZJMTIWDpQCDI8qv/y7YA9I7tppGY133bU6NUGZSox4BRzOfdzwuA6Cr9koT8Dp0Satz0s0tTCQh1TTywyBnLyqp0rdawov7RNJpb8Sh87ChyXuRTIPPi71ZqEb6a7KNBrjXTmevZmzmSyBo5wTSvKZsVMqASE81' WHERE [Id] = '20'
UPDATE [SaasPlan] SET [Name] = 'Bold BI Enterprise (Custom)', [PlanSchema] = 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlZn719TuITRq/Z1r96U+/EeM1DcTkcwcJ1lNs/zZUN+RCfSDjAcimUe1oWHV5KfdQW8gaDQzS2Sl6EqVYAKNqbk8ub/UkzHc1JbAQQUm+w6pE9ofdbHMVC41fS+/i5Hb8aIZXtPvOczU0I89f1pehKDpdEiNFxoC5WRaD/U7mK/DSDptcCRGSyaq3qNjHmEtTBuO4CS+9S61paa+D7Yue0l9H70WGCeY//E48zuySpxZ9/1Yl7LLkyHHJkivIm351Bv35fpSs6xAbiOKtvOrOH3teRJ12S1HN3F/kvIsMJwiqyqSaxvtuvIK9QYaW7lV4w=' WHERE [Id] = '45'
UPDATE [SaasPlan] SET [Name] = 'Bold BI Enterprise Half-Yearly (Custom)', [PlanSchema] = 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlayRBfrJtrl+NLav7ugjaAWWPmtsR7e+h+olCK+RKk/2F3Rdf2aQEe7oy1mHY9BnZq/jOJAP2UWUkDwiY4SVK9XBe3mhuG8t9SGWwM5I7NKDMf5ouHFvCPNAGJZRHp4NCkPyfLaEVFLEzHsFIm5uj1Ds465LH4aJfPk1JDiq2nL9QVaidtQyKQ8sueSU9O9tGw30iY97sASwrDNHm2hob8//9YprrvAUNczcTPuHlAK5Fu6KufSVYAN6RptwjK2KFB+YpdtU8bqkJFMy+T2imn7BfzGr5EKCLtNVr87rXofwRITt76S7Y4oc42FIb0bT54=' WHERE [Id] = '49'
UPDATE [SaasPlan] SET [Name] = 'Bold BI Enterprise Quarterly (Custom)', [PlanSchema] = 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlZgGNC3PPzwZtxfpa9yCMyFh3Fgz4BinppmzeoDFW5r8oQkW7lvlZ3Yc9UspqFXRVu3hVZgwRh7vN/xDHXTlXiBiXi8lKVOYUXCOdfA9IuxLsqAq42Usg5HnbPYSE/g4CuwonlOk0ox7ApM9QdZlCW2RXSmJfxIDfMFM+JtH7LUv9NcBlYgnIHjXG5Fa/Nma4AbrTqVVkO6nOxEAMQWVBsJnm0/5lc1h0xJ145E6aG35+EnvD3iaTG/FOl32YmdTHoiRDnJj3ljF365IgijAgEf1Cri1A8N2FGgWnKui4e020eWaMn6XoVv6mxmaeogqLg=' WHERE [Id] = '53'
UPDATE [SaasPlan] SET [Name] = 'Bold BI Embedded Custom', [PlanSchema] = 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlY6gWn2RFAFkJvLfFEYveI9tTEMpANMVMFHGXKJyM3ZHbCZr6EzfHoQ8TIvnkHrzbRs7A8lfMdeJJIFwghtPVNyLwMJwnQOYP2LZTa/UcTDYR23Vz3Y3vJhVtxLgqfelhNP+03dKDx6GiR1ZOTYUxi6KMEH9QamW/T9hFkkn9/MiTbRqd7mg5+X7jHx/CZKnvz3W/t4PfiNSx5WtItJUmoe5sEu9YCGvW4HYIczLqnmwzi1xAkV7TDyJL8LQAFXM64dXfjkjSY0AKBwFDu19oDJxNf+1sU1PvsZzLznTCCHZA==' WHERE [Id] = '60'
UPDATE [SaasPlan] SET [Name] = 'Bold BI Embedded Custom Annual', [PlanSchema] = 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbv5IvQO2QiaXPcIQ2Kl0sTfacQnl0QQJM5vZPgw7stk/Hi1q7Im0pVKh8BzhIdNyndxMuR/7+O58FqqQXATvRm1un4oKsO5pjDcFcP/7kvbw1vyCkECbL3OYkGLtrmX13HmYFjv4wwHtH0YTKeGaMbm5si4oK/mvGK42cLWYY1spxUrIODSQwn3QQ9s+egrxVwX+nac/4kCjGlbPq+cQQAndah7vMGhg3AgEZIAZHNM72x6AZ4TPWd2Q1o2ulp0Ynd07kwkkhp6LipvxQN0NoMyCKegWu6x9o/eXl7napzgHzMvSBbVA62ZhdXlTPearE=' WHERE [Id] = '61'
UPDATE [SaasPlan] SET [Name] = 'Bold BI Embedded Custom Half-Yearly', [PlanSchema] = 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbv5IvQO2QiaXPcIQ2Kl0sTmOnS5Eo+PeAJ1GOd4i8o182EqJJ6k6LPjcuDryAp6LkzgxsscAVFQtDIZek+cot6MC/iEK/i6PfwNv1D/rjvbYzH9S5aUAygVGFe3OhRWv9AuGaxPHdEzz+SvaPIq08tqloxYcdWNa9RuGvZS1Z0jZkH2aArO6MgrUhmkR2wSOFp3/auE1A35egAE/DJ9KVgqlIrFcyfi9tTbKCbw1ASVvWp1lVJRyqtK/NgDLbEvmIJqD+wIdagnlYGMlLc8koT0XZNCQNoBptN+qDA0rJeDKKo5HzAKyAkMn1CDeLwNdI=' WHERE [Id] = '62'
UPDATE [SaasPlan] SET [Name] = 'Bold BI Embedded Custom Quarterly', [PlanSchema] = 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbv5IvQO2QiaXPcIQ2Kl0sTyrC0kiE2zgzAU+o4osFK56nZ6JuDir/MVopz227AK/V61oDqPB4nvAutnkLRLdqQck17JKyAh0kdpcRnquba4i4rsNwlN7PtuzizGL3tBC5vFknb/7XUrQaTGQ4x5yAPOcnKi1dwRYsPzCccIRCIozeuDy7bs7p88lpvUFuZGAWaOturK4vtlO2S4KeJbVtT0cRZHYWvf7NNAhCkTi4zmSU+pEzSeFIZqhe7qlwP2pqgwYgPqG1agYfYIszBlF3yRbb1Urb2onNVJNb6IDrI1K3oyKN9YU6KAc6SCn9djWk=' WHERE [Id] = '63'

UPDATE [SaasPlan] SET [AdditionalFeatures] = 'Refresh data every 15 minutes,10-GB storage limit,Access to 85+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding support during trial,Custom Domain,Custom Branding,Office 365 Integration,Azure Active Directory Integration' WHERE [Id] = '8'
Update [SaaSPlan] set [AdditionalFeatures] = 'Web-based support,Access to 75+ data sources,Refresh data every 1 hour,25-GB storage limit,Share public and private dashboards,Onboarding support during trial' where Id = 9
Update [SaaSPlan] set [AdditionalFeatures] = 'Web-based support,Access to 75+ data sources,Refresh data daily,1-GB storage limit,Share public dashboards' where Id = 10
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 1 hour,Access to 75+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial' where Id = 11
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 1 hour,Access to 75+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial' where Id = 12
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 13
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 14
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration,Multi-tenant' where Id = 17
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 21
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,50-GB storage limit,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial,Custom Domain,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 24
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,250-GB storage limit,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial,Custom Domain,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 25
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 26
Update [SaaSPlan] set [AdditionalFeatures] = 'Localization,Custom Report Items,Custom Data Sources,Share Public Reports,Share Private Reports,Onboarding Support During Trial' where Id = 29
Update [SaaSPlan] set [AdditionalFeatures] = 'Localization,Custom Report Items,Custom Data Sources,Share Public Reports,Share Private Reports,Onboarding Support During Trial' where Id = 30
Update [SaaSPlan] set [AdditionalFeatures] = 'Localization,Custom Report Items,Custom Data Sources,Share Public Reports,Share Private Reports,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 31
Update [SaaSPlan] set [AdditionalFeatures] = 'Localization,Custom Report Items,Custom Data Sources,Share Public Reports,Share Private Reports,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 32
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,Share Public Reports,Share Private Reports,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration' where Id = 34
Update [SaaSPlan] set [AdditionalFeatures] = 'Refresh data every 5 min,Access to 75+ data sources,Share Public Reports,Share Private Reports,Onboarding Support During Trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration,Multi-tenant' where Id = 39

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Business 5', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgxnm0pkBuOfgwNBP0FYZiADSd3IHutvTo6PvNibpnal61Q6y5k6HCE1OGCVq0KvWLiPYAWnWTjSmG2ohlGTWdZKxoJdcWM4c2ioBsmEAwVPhO3I3iDc8Gr+H5nOLq2c39UfRkRkQ+AHwzhKh/yaOAuKxDHxOIPGU/tXTCORYu/1umUvfPtLJGHxAM/TOP21HQDP6b+w4pjYGPsRHzh90Rm5yRjOdocEhHNFUiU4hedGd8FD+xyAab1wmaIOC0JfBRdLGkOftp25MluhW7KWO25c1X4ipi5RUinumXlPRufo5kLCtPRyNFrDoM76NuZrgtBm/rX3mnRDVoY+LmyKhzpOQvMBZk90CzL/kA1abys/FdmWXSgqNoRLl3ZNaXdUIFTOfdw3cGc8pwH012h96jqHNNQuMR4JlPXdB66otNLTA5QoyHEo/AoIJHk/eDkHdlIrbFwEw01MIWqTDUcSHCrG4hvLp8djt9WLHiRj8FV9MDDYDelUGSQKNH+YEbhQH204UU8T0UUBypE18DszW9owr7Qryxv6P6dkW0pDKxMY6njW4uNph22/ukDeVk0OJiJR9nm1pZb0VG9vzXauZmTiUWdSyL7wgJCDcK8L2TPK+6fJVqZ4EdpoKM3lLHl1mmrj1iEd4CmRo4Rg/f4F936WRMjik24Llq7ehAMASRVRBHTE9CZLWi7+6D6OxEGz6c+d2wEilj8F8+i4osJV6XW5DG8qEN02rzsVKhmlv8Ms73JZLAS1MkZopj7sSa8g+ov0tSEprxm+DTQ8lG1ResGfQyIar/QgfUB/gmBcoawdNRpoUCjKMYHHjqr7wuvmajO4Loo+rTkdPtTM2eYUFuGK', null, 'Refresh data every 15 minutes,5-GB storage limit,Access to 85+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding support during trial,Custom Domain,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 1, 1, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Premium', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTZuFEU8LDj+30iiT2n9wAGKdFVv6ap1+5qrslumRzTCowTVhyeHGvS90uLdjsrqX1MJ1znkoFMBNYa33yWXQRO9ogM9WLNKRIGbVM1uqRd5fCdZlUdmVKZG0SLJ58iqtPBa9HxASyy7XMQC9gnqVeTkb+onUyGYUyXSqdvJVWCMV4mEeoF5kEAIfqSdNseKPVZMqhL+sfw4oqwJTsm/gQycS6ksDErruAlWY6kCktnFxfe6iFj9/r7S4wvjqp+J5rDFRUxTJNrEpy+2KHPLX1ZlYLQYs0K2sd1E9jhSnop1XPU0gecyuqknbu1Kf9u818w==','null','Refresh data every 5 minutes,25-GB storage limit,Access to 85+ data sources,Share Public Dashboards,Share Private Dashboards,Onboarding support during trial,Custom Domain,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 3, 1, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Single User Plan', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVq4fHZvhb3cEukmvW7eHhpSfoqD6iOGN4ylzxQ44/W5Q0AbWBWD4ZxSK9FduvXEGecMiFAfKHs3fO8zN+ZI4Ixhykev1HHuRYb7bxes1ASYW4Qe+uO6HMHFR2oukZORifi9hnRfnY9mA6v+QvYJKCe7juRNZg74jKIa0pqDo4bu04Jc/iGqVIhKhAm79q0xV5uQVoeuCxQLOfq0LCSc7w+si2Co/T/eKfa+RKH0HzSajisByg3LCA1tn7cIlNJoxDdw58R2SWgsHtWfM87Wo8ue2gfSVwZdiDM0NypWg330FkDLGfTkwZViL0S9akDUGZOYdkA97SfrH4UrqcVRL15ruWYMtm58FYOCPcKxQnOQAP6d0SO15d4G3fpFWOQKc+I16heeZ1gdzAiI/mD1l/kdY9/jjM4Hhc9j7tYION5NE4xoOrCD2a62souULXaui7XJJ+TGp9KraX54b8dKorBdqxOAQr1JN/3TcoFDiNKejw/sLM+uVMksPAoWaQKxh1JWiXahjzVV6hqEsdl3Ev38t4TMAkxNMR9x2L9EVcPgb37h9zYtCPYjgUnV4+41vi0gZ4sK38860E513mLy3MkTZ9z6XyiOhSVkS9qxO7D2eaA3l0+Th+iXQegaC4Cz4q3JdTGZavCUWTP80McMqc41pZciHD3BQZzF0emsltSthGaZlPw6ED2PIE7I5DmXuk=', null,'Web-based support,Access to 75+ data sources,Refresh data daily,1-GB storage limit,Share public reports', -1, 0, 2, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Business 5', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqU4tk67GR/okSoaPtBHsakgHMkqnJLPNkJL34MhJdpOwjlOlwMZZGCHI6PUhgyK1jRWgO/jLPpytIH11SMg7ydV+w0Hi0ZBpDW/CgYZ+bXFZQg4Z9V5ZYtrSbkP4CzwNIpYlSZE0oHQQc64CEYF8RIt4MJnrXT0A7c9QRwXrrlLj2inHN4nAkUv+kWU0x+POkKApeyAz8S05DszAdDL3npPuFiXxjkmNGkxINoTIJauzahd2U12jyZD1/bF0rVOMhdU88oAEO95wPP9lfVjojtZxjtCKFIu8zu+EawRQeHPUziIb/XqJ+aP9HZsPRoPBuZK6DPbZB+D81irViLCTR2E3bhTjsjn66WVOSULIwu+Xvzf6KNMA9MXf5R2dliXoRIBcsM84Uu67ToNQGv3BAai9ihIHkajmU7zbbdP8oPQeU=', null, 'Export to multiple file formats,25+ Drag and Drop widgets,Web-based support,Share public and private reports,Onboarding support during trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 1, 2, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Business 10', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqU4tk67GR/okSoaPtBHsakgHMkqnJLPNkJL34MhJdpOwjlOlwMZZGCHI6PUhgyK1jR6zG25dZqDRSFjbj/nffezsLoLhsYH8S4wli1nPTOVRR6V+0IwSlR+s9Jh4BzfQYCSa/fgMKAl6Gy0BFNosc7rY+vxEQaFD2a/AUr95K8JcR6wenFNk+BZkSoDApP4IIk7Yh09MTXJ150tVUcHfbssiOLVhVDOT38dOnQWDeinut06TL1DfN/+Z7RvEDELU/xuhCDU4SG+a6aMRzYB4guvm69MFqjE/VlBZm56LvJaP51RKx+4irhnbT1Y+YiS++LT2i/ZwV7cWOIJIzd4FiscM5w3zoOxe/47/9hw1VfC/eUoJ7jDjWBXTXfY4TFUOOu4Nmdz8JmLQNY+cV3yihy0YEYYkSa2VdKQ9YbdKsQsN8=', null, 'Export to multiple file formats,25+ Drag and Drop widgets,Web-based support,Share public and private reports,Onboarding support during trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 2, 2, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Premium', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTZuFEU8LDj+30iiT2n9wAGKdFVv6ap1+5qrslumRzTCowTVhyeHGvS90uLdjsrqX1MJ1znkoFMBNYa33yWXQRO9ogM9WLNKRIGbVM1uqRd5fCdZlUdmVKZG0SLJ58iqtPBa9HxASyy7XMQC9gnqVeTkb+onUyGYUyXSqdvJVWCMV/s/Ez43XN9VGHY+hpYKCHdfBL7iIucDV7TFNvKGfK0DHChKBfrZJ9lg9/kA0rTtwaN1c1uj5b7EYuLiibp8xDrqdXrSShclKcXY8TXlh++95x2GQxlnpAAByDmbgGkVJmL/dGaKmUIfntaiMgHniTA==','null','Export to multiple file formats,25+ Drag and Drop widgets,Share public and private reports,Onboarding support during trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 3, 2, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) VALUES (N'Custom', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+PgzjVR9TTeqMcZDzNi8PUcl8S9L30vto2eVpL0pHlAqVYu9+RWpGIj1SdTgZS2abXGqJqtoTb87jqblB96+npLqViUSet+4zm4UA3r6SuITl/cwZB+0X8QDZHW98wPu2ND0225jjv2dQbbmt7Pbkl3NlQOd0Kug92CxGYjmrhlo6U98yGQUTfnQZ6YTWemDbvEMpDpdbX8PVOqqup+e3pI3F6TnUkt584QD+mwcjhJFOITNaHsUk2HT59eWejkcC8C32LrGJraiWOi64ktlg2YMqTfLQBEALz3fklnMokJYqXfZpfbX36CXswoa5OQXRstlOzi0dHfalV8DxCdHlquUJZwm7nM6YR1jGrf5Ppbg5E35Nz6IIhj9gHS6gY1/D8C5PPk99yKPYiGL+zYiNwqhn9vDdb5ByfigYKiIKOtRRrR+TdoU2To/ZcEl5pWy3HV9REx2S8KNg2qB3QH0G0JVbdGnbeIgVfIm50vXIatCnbznYWSLFoaQKSbBUTgV/yHP4XOwvQpimpIJ2NCMruNZkGeFp/NdGBFiOKeNMaCVUBR+KXWeiwAEzyk5gqBdwsFQ71YoP6XyyMcgMHLl0h7BNSPZ7LtZ7eOjCc76m3vBnHeMlGZoyK0Lx1kBjiYNmoJgm1+iWBqFt5JvjZ+u4WLFIVmJPs4dFyHs9dDATwM69s/55ZqXtb1rrMtqxUzbYRJw0uVUSJ6zwCz+DCfiX1JeyNgdJ5ASscWZfiFG7A4zFoYun2cWUFIP74SxdA/HLOj0PdYuZwTNykhdbjzKgLrMh8Q8yV7HxguP+NsqwGx2LF75SkAz/mr8ebxLYKyQ97KPIBzntxEQCCnezBNfwh4xT9ldwEU4+WNOdknyypbz46eTvQ7Ld4ow4Al/RjsE8oIU=', null, null, 15, 0, 2, GETDATE(), 1, 1, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Bold BI Enterprise Standard', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlYpW6UC7Us8i30kQxV2MKXwYrJzWxBg4/edTS5Qnig3V5rPZ1QyZsnmPO28VO9tTyZl52BJbJt0RxMScUVhIzqxsbKfmu9iB7ugUHH+oda2093572FnBARbdX4OQ5XxsOf/va2QdLAaJXhWo0z5IHY7oJ16STAehGlKN9xmwNBX3QxJcFZQu6OWQhG9nMVYMj68zkSDtswFUmU1QxDaOLzk1IjnGPRo0bW7kAf/jbgqi7k8poQRyc+0C1WN1opqP1YJoyXyYEWhtzKwlSSRRJQm0FzhIh58lf3OUKLZszpMwM5PBwV6uEoIPIAnExTpeHE=','BoldBIOnPremise','Access to 75+ data sources,Share public and private dashboards,Onboarding support during trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 1, 3, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Bold Reports On-Premise Standard', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdH0lN4e9YSrOWr8LYgiJK72fTZSPpiArO2E2qwZYARn7NbJOve97vys5mZtgrwRcr7R+RknThkBmWNknKZWAp5ArDCZ7QoANmxJss7m36YgWBhlmfTkgHZ0sdBxVkPNTr938nHZoeVnD1t7bVwSVuwZ/BTxOB6O3n4/2190g0gHey0E61015V7yScfG5Z7R6V0xssCRRYyAQyzDDY4diBE32sqfEJT3/QMX3i6ZBVR5JEqZcA8rhI6beotXqN7j0YnUlbpRy3LrPgycgGSTqTOKY9Z/JU0A+Y8z8LaO1DngCACdDrixstrNzQ0s4r1hHus=','BoldReportsOnPremise','Localization,Custom Report Items,Custom Data Sources,Share public and private reports,Onboarding support during trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 1, 4, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Bold BI Embedded Standard', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlYc2c4MchbUYUkrOQbldiLzAsph1GcZd/kOhIye6hmVeRvSZ5KNJhXWc0axq8lbIZlofS7UNv9E/1D/DQyyYGJ59AjPAXP/ynV8qu19+hbeb6UYdIzN3ubWWiH5yUud89f8Iwiu2e8KbcNhPF/g0vQMs5/tQzCekxxrLrEnnicQN6NVzsCg+dGvkc7Lv2bUieU43e31eRY7Bwu4iKR8SGptwQt+khHGl1+eLwd2HbQTiEOV6JbU3MxuDAH0bI4UZQkecAq+rP9uDQi1VvJd1XbyhfqU7gxuc9DZIYedAq7LU80OdN25aoRNTnEyOpK79kc=','BoldBIOnPremise','Access to 75+ data sources,Share public and private dashboards,Onboarding support during trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 1, 3, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) values (N'Bold Reports Embedded Standard', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdE+rUDB9TTsNg/we2tK9L5dqfphauzmh0Rz2W6XkoIXE12wdk1FcqUer8RvPGF2d5mPRJIQo72W1dO2xMMqnORrWFGEfkUZEDXvBKfVh3DtKzvP+0EpTVydyIq+D9SSnAkJW2VS7GxTgy/PUonCkXGIJZ7NjzpW5Rp3t8iVdI1ItZyjOk09f4V1jtH/h06CByAmk27E+M1pa1ziMrdkTL7SwIPRVGoinRUJWWYmoMaQYILLgu+mHEg3Ni5fDGDfR2jpd/HLTnPjjrv01ZgD7kdUQ+wb+f1R3hKnju1OvvNYzzQX77BS6/VbddxZW5uhSB8=','BoldReportsOnPremise','Localization,Custom Report Items,Custom Data Sources,Share public and private reports,Onboarding support during trial,Custom Branding,Office 365 Integration,Azure Active Directory Integration', 15, 1, 4, GETDATE(), 0, 0, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) VALUES(N'Bold Reports (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdG+g+H6mu1QA6dgwFlnskrFvg20Tily65yUrimB4GbPcdS7p5C7+4B6vxNCT4FiJDwP+p/8PiW6gC76zohiEMTy0wyM9UhjYru81fbX4a/XjFo6XlhpicGcda4/wz22FsxpQHm7P+axTgxgalfxg2N+ejv/IsBZ5IWc56dP/mCQBNj/utAjpd0qNCzpev6G5qDt5F1IQh7Tg6ZbgQSycQUHtvyQt1AASlE21UA5G3jYOUcWgGvWCTvQ8MA9w5obS3Tw1MZO/a+BfAK0tBdZAMmYSyvshZRWuHGkiQYZpQsFrA==', null, null, 15, 0, 2, GETDATE(), 1, 1, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) VALUES(N'Bold Reports Cloud Half-Yearly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdEf+OAZfKZ6G/WTslPh+9uCX5DqPUiKUeVOX8WhidUt+nHWwwy9WPS7eVfHtIMlRveqojyNJAeEYZvKRTM6rMUJQd8C2sqY7aFGkARe58hEzHg1awSL9z6p0Nbi3vgT5ZkzupGIDB7xV3EJxLVLfnHqW5pkTfnkTSYhEmdIQKdOhTk1eAduxGtI+mpd8T7XEHPwsfJgT/+VW5ZEj2mar3ugTBCVIYZUXkiY78+sFmpIHOdUx76amzWoroSMzCL13IC/X0mqumqIdowGRU7mwcNTjYviYgKie9cKa0Cd04gK/+RI7sDPi5mIc3w3jX0Ca7M=', null, null, 15, 0, 2, GETDATE(), 1, 1, 0, 0, 1)

INSERT [dbo].[SaaSPlan] ([Name], [PlanSchema], [SetupName], [AdditionalFeatures], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsArchived], [IsActive]) VALUES(N'Bold Reports Cloud Quarterly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdEt6M3HJ/MPUhT1z0M3J2KJ9NGXtTZI1AJqn8Z81ZcumJsQAqbxeNdClBU85uAEIAxw8fyX/tDBv53SDi16y5r5eNRINMtf4BwdEVWgX5Hz0JcLIQ352QyIa9aSG01y0T8AUjYxf4TLUL0UqCLBQM1NN1+NZd1GbUUvVoSTO7HJZd6sI+0Jt+FFUY9w/nWU2BBoQIoP2PSWbCvv1+seEwoh3WwKRGEWudrhiWfB0DOgrzcB9hG573YYFuxrhw5Xvf73Kz/1PDW5nXZql5l8ZG8FFNkHLy23XVUxA9gXGf5SHb0TaYMT1HlkLVpxFUr56Ok=', null, null, 15, 0, 2, GETDATE(), 1, 1, 0, 0,1)

UPDATE  [dbo].[SaaSPlan] SET [IsArchived] = 1 WHERE [IsActive] = '1' AND [Id] NOT IN ('7','8','10','44','48','52','68','69','70','71','72','73','74','79','80','81','75','20','45','49','53','60','61','62','63','77','76','33','42','78','46','47','50','51','54','55','64','65','66','67');


--Staging

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8007, N'Bold BI Cloud Business 5', 1, 68, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8008, N'Bold BI Cloud Business 5 Subscription', 2, 68, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8009, N'Bold BI Cloud Premium', 1, 69, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8010, N'Bold BI Cloud Premium Subscription', 2, 69, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8011, N'Bold Reports Cloud Single User', 1, 70, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8012, N'Bold Reports Cloud Single User Subscription', 2, 70, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8013, N'Bold Reports Cloud Business 5', 1, 71, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8014, N'Bold Reports Cloud Business 5 Subscription', 2, 71, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8015, N'Bold Reports Cloud Business 10', 1, 72, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8016, N'Bold Reports Cloud Business 10 Subscription', 2, 72, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8017, N'Bold Reports Cloud Premium', 1, 73, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8018, N'Bold Reports Cloud Premium Subscription', 2, 73, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8019, N'Bold Reports Cloud Custom', 1, 74, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8020, N'Bold Reports Cloud Custom Subscription', 2, 74, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8027, N'Bold BI Enterprise Standard', 1, 75, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8028, N'Bold BI Enterprise Standard Subscription', 2, 75, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8031, N'Bold Reports On-Premise Standard', 1, 76, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8032, N'Bold Reports On-Premise Standard', 2, 76, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8029, N'Bold BI Embedded Standard', 1, 77, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8030, N'Bold BI Embedded Standard Subscription', 2, 77, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8033, N'Bold Reports On-Premise Embedded Standard', 1, 78, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8034, N'Bold Reports On-Premise Embedded Standard Subscription', 2, 78, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8021, N'Bold Reports Cloud Bold Reports Custom', 1, 79, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8022, N'Bold Reports Cloud Bold Reports Custom Subscription', 2, 79, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8023, N'Bold Reports Cloud Half-Yearly Custom', 1, 80, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8024, N'Bold Reports Cloud Half-Yearly Custom Subscription', 2, 80, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8025, N'Bold Reports Cloud Quarterly Custom', 1, 81, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8026, N'Bold Reports Cloud Quarterly Custom Subscription', 2, 81, 1)

--Live

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8005, N'Bold BI Cloud Business 5', 1, 68, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8006, N'Bold BI Cloud Business 5 Subscription', 2, 68, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8007, N'Bold BI Cloud Premium', 1, 69, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8008, N'Bold BI Cloud Premium Subscription', 2, 69, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8009, N'Bold Reports Cloud Single User', 1, 70, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8010, N'Bold Reports Cloud Single User Subscription', 2, 70, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8011, N'Bold Reports Cloud Business 5', 1, 71, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8012, N'Bold Reports Cloud Business 5 Subscription', 2, 71, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8013, N'Bold Reports Cloud Business 10', 1, 72, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8014, N'Bold Reports Cloud Business 10 Subscription', 2, 72, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8015, N'Bold Reports Cloud Premium', 1, 73, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8016, N'Bold Reports Cloud Premium Subscription', 2, 73, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8017, N'Bold Reports Cloud Custom', 1, 74, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8018, N'Bold Reports Cloud Custom Subscription', 2, 74, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8025, N'Bold BI Enterprise Standard', 1, 75, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8026, N'Bold BI Enterprise Standard Subscription', 2, 75, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8029, N'Bold Reports On-Premise Standard', 1, 76, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8030, N'Bold Reports On-Premise Standard', 2, 76, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8027, N'Bold BI Embedded Standard', 1, 77, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8028, N'Bold BI Embedded Standard Subscription', 2, 77, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8031, N'Bold Reports On-Premise Embedded Standard', 1, 78, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8032, N'Bold Reports On-Premise Embedded Standard Subscription', 2, 78, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8019, N'Bold Reports Cloud Bold Reports Custom', 1, 79, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8020, N'Bold Reports Cloud Bold Reports Custom Subscription', 2, 79, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8021, N'Bold Reports Cloud Half-Yearly Custom', 1, 80, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8022, N'Bold Reports Cloud Half-Yearly Custom Subscription', 2, 80, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8023, N'Bold Reports Cloud Quarterly Custom', 1, 81, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (8024, N'Bold Reports Cloud Quarterly Custom Subscription', 2, 81, 1)
