//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.Dashboard.Connection.SQLServer.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.Dashboard.Connection.SQLServer.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS(SELECT {0} FROM {1} WHERE {2} ).
        /// </summary>
        internal static string AcosFunctionFormat {
            get {
                return ResourceManager.GetString("AcosFunctionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETWEEN.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTAINS.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom_Sort_Order_Table.
        /// </summary>
        internal static string CustomSortOrderTableAliasName {
            get {
                return ResourceManager.GetString("CustomSortOrderTableAliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDS WITH.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse relative date expression. Bad arguments.
        /// </summary>
        internal static string Err_FailToParseRelativeDateExpression {
            get {
                return ResourceManager.GetString("Err_FailToParseRelativeDateExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0} FROM ({1}) AS {2} WHERE {3} &gt;= {4} ORDER BY {5} ASC.
        /// </summary>
        internal static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTITION BY.
        /// </summary>
        internal static string PartitionBy {
            get {
                return ResourceManager.GetString("PartitionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEADD(ms, -DATEPART(ms, {0}), {1}).
        /// </summary>
        internal static string RemoveMilliSecondsFromDateTime {
            get {
                return ResourceManager.GetString("RemoveMilliSecondsFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ROW_NUMBER() OVER ({0} {1}) AS {2}.
        /// </summary>
        internal static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¤RowNumber.
        /// </summary>
        internal static string RowNumberColumnName {
            get {
                return ResourceManager.GetString("RowNumberColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROW_NUMBER.
        /// </summary>
        internal static string RowUnderscoreNumber {
            get {
                return ResourceManager.GetString("RowUnderscoreNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACOS.
        /// </summary>
        internal static string SqlAcos {
            get {
                return ResourceManager.GetString("SqlAcos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        internal static string SqlAnd {
            get {
                return ResourceManager.GetString("SqlAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND NOT.
        /// </summary>
        internal static string SqlAndNot {
            get {
                return ResourceManager.GetString("SqlAndNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS.
        /// </summary>
        internal static string SqlAs {
            get {
                return ResourceManager.GetString("SqlAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC.
        /// </summary>
        internal static string SqlAsc {
            get {
                return ResourceManager.GetString("SqlAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASIN.
        /// </summary>
        internal static string SqlAsin {
            get {
                return ResourceManager.GetString("SqlAsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG.
        /// </summary>
        internal static string SqlAvg {
            get {
                return ResourceManager.GetString("SqlAvg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVGD.
        /// </summary>
        internal static string SqlAvgD
        {
            get
            {
                return ResourceManager.GetString("SqlAvgD", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to BEGIN SELECT {0} FROM {1} END ELSE BEGIN SELECT TOP 1({0}) FROM {1} END.
        /// </summary>
        internal static string SqlBeginFormat {
            get {
                return ResourceManager.GetString("SqlBeginFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETWEEN {0} AND {1}.
        /// </summary>
        internal static string SqlBetweenFormat {
            get {
                return ResourceManager.GetString("SqlBetweenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIGINT.
        /// </summary>
        internal static string SqlBigInt {
            get {
                return ResourceManager.GetString("SqlBigInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BINARY.
        /// </summary>
        internal static string SqlBinary {
            get {
                return ResourceManager.GetString("SqlBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIT.
        /// </summary>
        internal static string SqlBit {
            get {
                return ResourceManager.GetString("SqlBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VarBinary.
        /// </summary>
        internal static string SqlByte {
            get {
                return ResourceManager.GetString("SqlByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE.
        /// </summary>
        internal static string SqlCase {
            get {
                return ResourceManager.GetString("SqlCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} THEN {1} ELSE {2} END.
        /// </summary>
        internal static string SqlCaseWhenElseFormat {
            get {
                return ResourceManager.GetString("SqlCaseWhenElseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST.
        /// </summary>
        internal static string SqlCast {
            get {
                return ResourceManager.GetString("SqlCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST( {0} AS {1} ).
        /// </summary>
        internal static string SqlCastFormat {
            get {
                return ResourceManager.GetString("SqlCastFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEIL.
        /// </summary>
        internal static string SqlCeil {
            get {
                return ResourceManager.GetString("SqlCeil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAR.
        /// </summary>
        internal static string SqlChar {
            get {
                return ResourceManager.GetString("SqlChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string SqlComparisonFormat {
            get {
                return ResourceManager.GetString("SqlComparisonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} THEN {1} ELSE NULL END.
        /// </summary>
        internal static string SqlConditionalConversionFormat {
            get {
                return ResourceManager.GetString("SqlConditionalConversionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is broken and recovery is not possible.  The client driver attempted to recover the connection one or more times and all attempts failed.  Increase the value of ConnectRetryCount to increase the number of recovery attempts..
        /// </summary>
        internal static string SqlConnectionFailException {
            get {
                return ResourceManager.GetString("SqlConnectionFailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} like {1} THEN 1 ELSE 0 END.
        /// </summary>
        internal static string SqlContainsFormat {
            get {
                return ResourceManager.GetString("SqlContainsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT(VARCHAR, CAST({0} AS DATE), 112).
        /// </summary>
        internal static string SqlConvertCastDateFormat {
            get {
                return ResourceManager.GetString("SqlConvertCastDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT(VARCHAR(8), {0}, 112).
        /// </summary>
        internal static string SqlConvertFormat {
            get {
                return ResourceManager.GetString("SqlConvertFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT(VARCHAR(8), {0}, 108).
        /// </summary>
        internal static string SqlConvertFormat_Time {
            get {
                return ResourceManager.GetString("SqlConvertFormat_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT( {0} , {1} ).
        /// </summary>
        internal static string SQLConvertFunction {
            get {
                return ResourceManager.GetString("SQLConvertFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT(REPLACE(CONVERT(VARCHAR(8), CAST({0} AS DATETIME), 114),&apos;:&apos;,&apos;&apos;),6).
        /// </summary>
        internal static string SqlConvertTimeFormat {
            get {
                return ResourceManager.GetString("SqlConvertTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        internal static string SqlCount {
            get {
                return ResourceManager.GetString("SqlCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT(*).
        /// </summary>
        internal static string SqlCountAll {
            get {
                return ResourceManager.GetString("SqlCountAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Count_BIG.
        /// </summary>
        internal static string SqlCount_Big
        {
            get
            {
                return ResourceManager.GetString("SqlCount_Big", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COUNTD.
        /// </summary>
        internal static string SqlCountD {
            get {
                return ResourceManager.GetString("SqlCountD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE {0} ( {1} );.
        /// </summary>
        internal static string SqlCreateTableFormat {
            get {
                return ResourceManager.GetString("SqlCreateTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART(month, CAST(GETDATE() AS DATE)).
        /// </summary>
        internal static string SqlCurrentmonth {
            get {
                return ResourceManager.GetString("SqlCurrentmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART(year, CAST(GETDATE() AS DATE)).
        /// </summary>
        internal static string SqlCurrentyear {
            get {
                return ResourceManager.GetString("SqlCurrentyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string SqlDate {
            get {
                return ResourceManager.GetString("SqlDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEADD.
        /// </summary>
        internal static string SqlDateAdd {
            get {
                return ResourceManager.GetString("SqlDateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEDIFF.
        /// </summary>
        internal static string SqlDateDiff {
            get {
                return ResourceManager.GetString("SqlDateDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART.
        /// </summary>
        internal static string SqlDatePart {
            get {
                return ResourceManager.GetString("SqlDatePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIME.
        /// </summary>
        internal static string SqlDatetime {
            get {
                return ResourceManager.GetString("SqlDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIME2.
        /// </summary>
        internal static string SqlDateTime2 {
            get {
                return ResourceManager.GetString("SqlDateTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIMEOFFSET.
        /// </summary>
        internal static string SqlDateTimeOffset {
            get {
                return ResourceManager.GetString("SqlDateTimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY.
        /// </summary>
        internal static string SqlDay {
            get {
                return ResourceManager.GetString("SqlDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAYOFYEAR.
        /// </summary>
        internal static string SqlDayOfYear {
            get {
                return ResourceManager.GetString("SqlDayOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECIMAL.
        /// </summary>
        internal static string SqlDecimal {
            get {
                return ResourceManager.GetString("SqlDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE.
        /// </summary>
        internal static string SqlDeclare {
            get {
                return ResourceManager.GetString("SqlDeclare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}( {3} ).
        /// </summary>
        internal static string SqlDeclareTableFormat {
            get {
                return ResourceManager.GetString("SqlDeclareTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000-0000-0000-0000-000000000000.
        /// </summary>
        internal static string SqlDefaultGuid {
            get {
                return ResourceManager.GetString("SqlDefaultGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESC.
        /// </summary>
        internal static string SqlDesc {
            get {
                return ResourceManager.GetString("SqlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        internal static string SqlDifferent {
            get {
                return ResourceManager.GetString("SqlDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTINCT.
        /// </summary>
        internal static string SqlDistinct {
            get {
                return ResourceManager.GetString("SqlDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE {0}.
        /// </summary>
        internal static string SqlDropTableFormat {
            get {
                return ResourceManager.GetString("SqlDropTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELSE.
        /// </summary>
        internal static string SqlElse {
            get {
                return ResourceManager.GetString("SqlElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END.
        /// </summary>
        internal static string SqlEnd {
            get {
                return ResourceManager.GetString("SqlEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string SqlEquals {
            get {
                return ResourceManager.GetString("SqlEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC.
        /// </summary>
        internal static string SqlExec {
            get {
                return ResourceManager.GetString("SqlExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLOAT.
        /// </summary>
        internal static string SqlFloat {
            get {
                return ResourceManager.GetString("SqlFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMAT( {0} ).
        /// </summary>
        internal static string SqlFormatFormat {
            get {
                return ResourceManager.GetString("SqlFormatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        internal static string SqlFrom {
            get {
                return ResourceManager.GetString("SqlFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL.
        /// </summary>
        internal static string SqlFull {
            get {
                return ResourceManager.GetString("SqlFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}).
        /// </summary>
        internal static string SqlFunctionFormat {
            get {
                return ResourceManager.GetString("SqlFunctionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOGRAPHY.
        /// </summary>
        internal static string SqlGeography {
            get {
                return ResourceManager.GetString("SqlGeography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOMETRY.
        /// </summary>
        internal static string SqlGeometry {
            get {
                return ResourceManager.GetString("SqlGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string SqlGreaterOrEquals {
            get {
                return ResourceManager.GetString("SqlGreaterOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string SqlGreaterThan {
            get {
                return ResourceManager.GetString("SqlGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP BY.
        /// </summary>
        internal static string SqlGroupBy {
            get {
                return ResourceManager.GetString("SqlGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAVING.
        /// </summary>
        internal static string SqlHaving {
            get {
                return ResourceManager.GetString("SqlHaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIERARCHYID.
        /// </summary>
        internal static string SqlHierarchyId {
            get {
                return ResourceManager.GetString("SqlHierarchyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOUR.
        /// </summary>
        internal static string SqlHour {
            get {
                return ResourceManager.GetString("SqlHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE.
        /// </summary>
        internal static string SqlImage {
            get {
                return ResourceManager.GetString("SqlImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN( {0} ).
        /// </summary>
        internal static string SqlInFormat {
            get {
                return ResourceManager.GetString("SqlInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER.
        /// </summary>
        internal static string SqlInner {
            get {
                return ResourceManager.GetString("SqlInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER JOIN.
        /// </summary>
        internal static string SqlInnerJoin {
            get {
                return ResourceManager.GetString("SqlInnerJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        internal static string SqlInsert {
            get {
                return ResourceManager.GetString("SqlInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4}.
        /// </summary>
        internal static string SqlInsertExecFormat {
            get {
                return ResourceManager.GetString("SqlInsertExecFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0} VALUES ( {1} ).
        /// </summary>
        internal static string SqlInsertIntoFormat {
            get {
                return ResourceManager.GetString("SqlInsertIntoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * INTO {0} FROM ( {1} ) AS QUERY.
        /// </summary>
        internal static string SqlInsertIntoFromQueryFormat {
            get {
                return ResourceManager.GetString("SqlInsertIntoFromQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        internal static string SqlInt {
            get {
                return ResourceManager.GetString("SqlInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT32.
        /// </summary>
        internal static string SqlInt32 {
            get {
                return ResourceManager.GetString("SqlInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT64.
        /// </summary>
        internal static string SqlInt64 {
            get {
                return ResourceManager.GetString("SqlInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        internal static string SqlIs {
            get {
                return ResourceManager.GetString("SqlIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDATE( {0} ) = 1.
        /// </summary>
        internal static string SqlIsDateFormat {
            get {
                return ResourceManager.GetString("SqlIsDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS NOT NULL.
        /// </summary>
        internal static string SqlIsNotNull {
            get {
                return ResourceManager.GetString("SqlIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS NULL.
        /// </summary>
        internal static string SqlIsNull {
            get {
                return ResourceManager.GetString("SqlIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISNULL.
        /// </summary>
        internal static string SqlIsNullFunction {
            get {
                return ResourceManager.GetString("SqlIsNullFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISNUMERIC( {0} ) = 1.
        /// </summary>
        internal static string SqlIsNumberFormat {
            get {
                return ResourceManager.GetString("SqlIsNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN.
        /// </summary>
        internal static string SqlJoin {
            get {
                return ResourceManager.GetString("SqlJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT OUTER.
        /// </summary>
        internal static string SqlLeft {
            get {
                return ResourceManager.GetString("SqlLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT JOIN.
        /// </summary>
        internal static string SqlLeftJoin {
            get {
                return ResourceManager.GetString("SqlLeftJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string SqlLessOrEquals {
            get {
                return ResourceManager.GetString("SqlLessOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string SqlLessThan {
            get {
                return ResourceManager.GetString("SqlLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIKE.
        /// </summary>
        internal static string SqlLike {
            get {
                return ResourceManager.GetString("SqlLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} LIKE {1}.
        /// </summary>
        internal static string SqlLikeFormat {
            get {
                return ResourceManager.GetString("SqlLikeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        internal static string SqlMax {
            get {
                return ResourceManager.GetString("SqlMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        internal static string SqlMin {
            get {
                return ResourceManager.GetString("SqlMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINUTE.
        /// </summary>
        internal static string SqlMinute {
            get {
                return ResourceManager.GetString("SqlMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD.
        /// </summary>
        internal static string SqlMod {
            get {
                return ResourceManager.GetString("SqlMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY.
        /// </summary>
        internal static string SqlMoney {
            get {
                return ResourceManager.GetString("SqlMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTH.
        /// </summary>
        internal static string SqlMonth {
            get {
                return ResourceManager.GetString("SqlMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCHAR.
        /// </summary>
        internal static string SqlNChar {
            get {
                return ResourceManager.GetString("SqlNChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        internal static string SqlNot {
            get {
                return ResourceManager.GetString("SqlNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT BETWEEN {0} AND {1}.
        /// </summary>
        internal static string SqlNotBetweenFormat {
            get {
                return ResourceManager.GetString("SqlNotBetweenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GETDATE().
        /// </summary>
        internal static string SqlNow {
            get {
                return ResourceManager.GetString("SqlNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTEXT.
        /// </summary>
        internal static string SqlNText {
            get {
                return ResourceManager.GetString("SqlNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SqlNull {
            get {
                return ResourceManager.GetString("SqlNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMERIC.
        /// </summary>
        internal static string SqlNumeric {
            get {
                return ResourceManager.GetString("SqlNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVARCHAR.
        /// </summary>
        internal static string SqlNVarchar {
            get {
                return ResourceManager.GetString("SqlNVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string SqlOn {
            get {
                return ResourceManager.GetString("SqlOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string SqlOr {
            get {
                return ResourceManager.GetString("SqlOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY.
        /// </summary>
        internal static string SqlOrderBy {
            get {
                return ResourceManager.GetString("SqlOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR NOT.
        /// </summary>
        internal static string SqlOrNot {
            get {
                return ResourceManager.GetString("SqlOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTER.
        /// </summary>
        internal static string SqlOuter {
            get {
                return ResourceManager.GetString("SqlOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVER.
        /// </summary>
        internal static string SqlOver {
            get {
                return ResourceManager.GetString("SqlOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0}({1}) FROM(SELECT TOP({2}) {1} FROM {3}) AS RESULT.
        /// </summary>
        internal static string SqlPagingRunningQuery {
            get {
                return ResourceManager.GetString("SqlPagingRunningQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}().
        /// </summary>
        internal static string SqlParameterLessFunctionFormat {
            get {
                return ResourceManager.GetString("SqlParameterLessFunctionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART(month, DATEADD(month, -1, CAST(GETDATE() AS DATE))).
        /// </summary>
        internal static string SqlPreviousmonth {
            get {
                return ResourceManager.GetString("SqlPreviousmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEPART(year, DATEADD(year, -1, CAST(GETDATE() AS DATE))).
        /// </summary>
        internal static string SqlPreviousyear {
            get {
                return ResourceManager.GetString("SqlPreviousyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUARTER.
        /// </summary>
        internal static string SqlQuarter {
            get {
                return ResourceManager.GetString("SqlQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL.
        /// </summary>
        internal static string SqlReal {
            get {
                return ResourceManager.GetString("SqlReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE {0};.
        /// </summary>
        internal static string SqlRemoveTableFormat {
            get {
                return ResourceManager.GetString("SqlRemoveTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        internal static string SqlRight {
            get {
                return ResourceManager.GetString("SqlRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOND.
        /// </summary>
        internal static string SqlSecond {
            get {
                return ResourceManager.GetString("SqlSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        internal static string SqlSelect {
            get {
                return ResourceManager.GetString("SqlSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMALLDATETIME.
        /// </summary>
        internal static string SqlSmallDateTime {
            get {
                return ResourceManager.GetString("SqlSmallDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMALLINT.
        /// </summary>
        internal static string SqlSmallInt {
            get {
                return ResourceManager.GetString("SqlSmallInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMALLMONEY.
        /// </summary>
        internal static string SqlSmallMoney {
            get {
                return ResourceManager.GetString("SqlSmallMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL_VARIANT.
        /// </summary>
        internal static string SqlSql_Variant {
            get {
                return ResourceManager.GetString("SqlSql_Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string SqlStar {
            get {
                return ResourceManager.GetString("SqlStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDEV.
        /// </summary>
        internal static string SqlStdev {
            get {
                return ResourceManager.GetString("SqlStdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDEVP.
        /// </summary>
        internal static string SqlStdevP {
            get {
                return ResourceManager.GetString("SqlStdevP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSTRING.
        /// </summary>
        internal static string SqlSubstring {
            get {
                return ResourceManager.GetString("SqlSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string SqlSum {
            get {
                return ResourceManager.GetString("SqlSum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string SqlSumD
        {
            get
            {
                return ResourceManager.GetString("SqlSumD", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ¤Super_Query.
        /// </summary>
        internal static string SqlSuperQuery {
            get {
                return ResourceManager.GetString("SqlSuperQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE.
        /// </summary>
        internal static string SqlTable {
            get {
                return ResourceManager.GetString("SqlTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT.
        /// </summary>
        internal static string SqlText {
            get {
                return ResourceManager.GetString("SqlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THEN.
        /// </summary>
        internal static string SqlThen {
            get {
                return ResourceManager.GetString("SqlThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        internal static string SqlTime {
            get {
                return ResourceManager.GetString("SqlTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMESTAMP.
        /// </summary>
        internal static string SqlTimeStamp {
            get {
                return ResourceManager.GetString("SqlTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TINYINT.
        /// </summary>
        internal static string SqlTinyInt {
            get {
                return ResourceManager.GetString("SqlTinyInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP.
        /// </summary>
        internal static string SqlTop {
            get {
                return ResourceManager.GetString("SqlTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP (1).
        /// </summary>
        internal static string SqlTopOne {
            get {
                return ResourceManager.GetString("SqlTopOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNION ALL.
        /// </summary>
        internal static string SqlUnionAll {
            get {
                return ResourceManager.GetString("SqlUnionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIQUEIDENTIFIER.
        /// </summary>
        internal static string SqlUniqueIdentifier {
            get {
                return ResourceManager.GetString("SqlUniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR.
        /// </summary>
        internal static string SqlVar {
            get {
                return ResourceManager.GetString("SqlVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARBINARY.
        /// </summary>
        internal static string SqlVarBinary {
            get {
                return ResourceManager.GetString("SqlVarBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARCHAR.
        /// </summary>
        internal static string SqlVarChar {
            get {
                return ResourceManager.GetString("SqlVarChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARP.
        /// </summary>
        internal static string SqlVarP {
            get {
                return ResourceManager.GetString("SqlVarP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEK.
        /// </summary>
        internal static string SqlWeek {
            get {
                return ResourceManager.GetString("SqlWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEKDAY.
        /// </summary>
        internal static string SqlWeekDay {
            get {
                return ResourceManager.GetString("SqlWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN.
        /// </summary>
        internal static string SqlWhen {
            get {
                return ResourceManager.GetString("SqlWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE.
        /// </summary>
        internal static string SqlWhere {
            get {
                return ResourceManager.GetString("SqlWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH.
        /// </summary>
        internal static string SqlWith {
            get {
                return ResourceManager.GetString("SqlWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string SqlXml {
            get {
                return ResourceManager.GetString("SqlXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        internal static string SqlYear {
            get {
                return ResourceManager.GetString("SqlYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATEADD(day, -1, CAST(GETDATE() AS DATE)).
        /// </summary>
        internal static string SqlYesterday {
            get {
                return ResourceManager.GetString("SqlYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARTS WITH.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT * FROM OPENQUERY([{0}],&apos;EXEC [{1}].[{2}].[{3}]&apos;)) [{3}].
        /// </summary>
        internal static string StoredProcedureWithOutParameter {
            get {
                return ResourceManager.GetString("StoredProcedureWithOutParameter", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to (SELECT TOP {4} * FROM OPENQUERY([{0}],&apos;EXEC [{1}].[{2}].[{3}]&apos;)) [{3}].
        /// </summary>
        internal static string StoredProcedureWithOutParameterforDataSampling {
            get {
                return ResourceManager.GetString("StoredProcedureWithOutParameterforDataSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT * FROM OPENQUERY([{0}],&apos;EXEC [{1}].[{2}].[{3}]  {4}&apos;)) [{3}].
        /// </summary>
        internal static string StoredProcedureWithParameter {
            get {
                return ResourceManager.GetString("StoredProcedureWithParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT TOP {5} * FROM OPENQUERY([{0}],&apos;EXEC [{1}].[{2}].[{3}]  {4}&apos;)) [{3}].
        /// </summary>
        internal static string StoredProcedureWithParameterforDataSampling {
            get {
                return ResourceManager.GetString("StoredProcedureWithParameterforDataSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNSUPPORT.
        /// </summary>
        internal static string UnSupport {
            get {
                return ResourceManager.GetString("UnSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        internal static string YearFormatCount {
            get {
                return ResourceManager.GetString("YearFormatCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to restrict Order By clause in query string unless TOP, OFFSET, or FOR XML is also specified.
        /// </summary>
        internal static string RestrictOrderByErrorMessage
        {
            get
            {
                return ResourceManager.GetString("RestrictOrderByErrorMessage", resourceCulture);
            }
        }
    }
}
