CREATE TABLE BOLDTC_BackUp (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ConfigurationData CLOB NOT NULL,
    PrivateKey CLOB NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL
);