CREATE TABLE BOLDTC_TOKENVAULT (
    TENANTID VARCHAR2(36) NOT NULL,
    IDPUSERID VARCHAR2(36) NOT NULL,
    AUTHUSERID VARCHAR2(36) NOT NULL,
    AUTHPROVIDERID NUMBER NOT NULL,
    ENCRYPTEDTOKEN CLOB NOT NULL,
    EXPIRESAT TIMESTAMP WITH TIME ZONE NULL,
    UPDATEDAT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BOLDTC_TOKENVAULT PRIMARY KEY (TENANTID, IDPUSERID, AUTHPROVIDERID)
);

ALTER TABLE BOLDTC_UserLogin ADD EncryptedIdToken NVARCHAR2(2000) NULL;

ALTER TABLE BOLDTC_UserLogin ADD IdTokenExpiresAt TIMESTAMP NULL;

ALTER TABLE BOLDTC_UserLogin ADD IsUsedForLogout NUMBER(1) NULL;

ALTER TABLE BOLDTC_SystemSettings ADD SystemValue_Lob NCLOB;
UPDATE BOLDTC_SystemSettings SET SystemValue_Lob = TO_NCLOB(SystemValue);
ALTER TABLE BOLDTC_SystemSettings DROP COLUMN SystemValue;
ALTER TABLE BOLDTC_SystemSettings RENAME COLUMN SystemValue_Lob TO SystemValue;
