﻿ALTER TABLE [dbo].[UserLog]
ADD AdditionalData NVARCHAR(MAX) NULL

ALTER TABLE [dbo].[UserLog]
ADD ReferrerUrl NVARCHAR(MAX) NULL

ALTER TABLE [dbo].[UserLog]
ALTER COLUMN UserId uniqueidentifier NULL

ALTER TABLE [dbo].[UserLog] DROP CONSTRAINT [UserLog_fk0]

ALTER TABLE [dbo].[UserLog] DROP COLUMN [LogTypeId]

DROP TABLE [dbo].[UserLogType]

CREATE TABLE [BillingInterval] (
	Id int IDENTITY(1,1) NOT NULL,
	Interval nvarchar(255) NOT NULL UNIQUE,
	IsActive bit NOT NULL,
  CONSTRAINT [PK_BILLINGINTERVAL] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)

ALTER TABLE [SaaSPlan] ADD [IsCustom] [bit] NOT NULL default 0, [IsSDK] [bit] NOT NULL default 0,[SetupName] nvarchar(255), [AdditionalFeatures] nvarchar(max), [BillingIntervalId] int

INSERT [dbo].[BillingInterval] ([Interval], [IsActive]) VALUES (N'Monthly', 1)
INSERT [dbo].[BillingInterval] ([Interval], [IsActive]) VALUES (N'Yearly', 1)
INSERT [dbo].[BillingInterval] ([Interval], [IsActive]) VALUES (N'HalfYearly', 1)
INSERT [dbo].[BillingInterval] ([Interval], [IsActive]) VALUES (N'Quarterly', 1)

ALTER TABLE [SaaSPlan] WITH CHECK ADD CONSTRAINT [SaaSPlan_fk2] FOREIGN KEY ([BillingIntervalId]) REFERENCES [BillingInterval]([Id])

GO
ALTER TABLE [SaaSPlan] CHECK CONSTRAINT [SaaSPlan_fk2]
GO

Update [SaaSPlan] set [SetupName] = 'BoldBIOnPremise' where [TenantTypeId] = '3'
Update [SaaSPlan] set [SetupName] = 'BoldReportsOnPremise' where [TenantTypeId] = '4'
Update [SaaSPlan] set [SetupName] = 'BoldEmbeddedReportingTools' where Id IN ('34','37' ,'38','42', '43', '47')
Update [SaaSPlan] set [IsCustom] = 'true' where Id IN('7', '20', '33', '43', '44', '45' , '46' , '47')
Update [SaaSPlan] set [IsSDK] = 'true' where Id IN('42', '43', '47')

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI Cloud Half-Yearly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbcrtytcG2txWBe3ubPeigVGMzInR9z7nH1HM13MIi1qXAMLUSbTmVSO+8EEjDxTs3swsId4ZJ7U9O/Mk9IfY9rP5YMhDTTrxpqHuaxuJBLvD6Gg6RbUp/ZeVYatPqTdeYTh8d4nFz2FKW2c1OSDltXLqq3j5wsThkPxJW5m+11ferIPqJeq1RX45LzGw10bqyO3AM5SgW7DfwkuQ2eGcZ6+2kA3iH8inZ1OqjljYheAGvUc+QCj9zKim3+SNPG6ylu97CxYtI9TR7CX6vT5DN32omP87r6I6927u0nvqm4U7jRQlU2kaCvUP7qg/+ZhwQ=', null, 15, 0, 1, GETDATE(), 1, 1, 0, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI On-Premise Half-Yearly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlYKLuvRSAMEcQ7dbJGb3HBRyOpMNfeqKAlTBRko02qyTd52YLsKH5EjLWO8THMGQi/Ci8ceC45gjw6EsjwGsl2qI9NWPUfkEPMSe4dYmizXxhxjFuprQKXQMw8f2XFTVTe/G2cc9knUWeJ6SKhcpyPqkqRHu5wRMnHwrpAHXEInyladY/ut4pmo7fsOdJweEPj+jBMO9NYxT0nKcp93/XZ/z2ew4M2zVf1WCLxfYsG8xUXeOMsCP/yhdhq4lHdJhBvLhfnlyevzrtFbaXXUoEBjP/8DXBBLp5LKnfsY0mU/uggOfQHoUVhHkuY0+dfh1pk=','BoldBIOnPremise', 15, 0, 3, GETDATE(), 1, 1, 0, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold Reports On-Premise Half-Yearly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdH0lN4e9YSrOWr8LYgiJK72IQf4M9n5TdQemPPwXL5Yc57gPFZn1Fy6hLqnwS7RwTfFld3TnvhGKABJi0nncOMVfshYNNb77jAv1C8/O/hWf/pUstn6F0gQALxMh57F9jiZ4ldBIuihd9srpkokrygAJPWuavdYv+1nOPE7HxPCRPZJqQhYIdILcRNRN7YfgM7GflQHAkjH0ph0GAWQwoO/pZsHjzY+yk+2BiK1cKsB4bs3oHfZfZuUY+Bqo3a1SkR9tYBQnNLyRdWswWSpWu2w8BX0Ao4S6FC0ra53gG9IGamTXUtvDI1VYsls9kVKe9JHFqOd0U7wJ2IpfSr1oYuR', 'BoldReportsOnPremise', 15, 0, 4, GETDATE(), 1, 1, 0, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES (N'Bold Reports Viewer SDK Half-Yearly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdEzh1oY/yzboGRRvluxFlFd4e9libWH7eCiDu1lrZr2Bz5cfIlZNRFmXQTqCoLA+WIz2m6VhGUuuSnNDkgswtvZxDVggRhQZ9hYP0SLWN0dZNjuHZRpDB3KgcJTT/fgB27XoTgXGKvRobREMFXyzbVVoAn6Po5+iErnP3jw7xCU5Zf7V+YikrCg+NLz7TaOPhtB/LVTQuaWUW5s9/vFuRXcbpNT57YYRjBKniuq0h/1vqoxA/ggkusCt5jg7ogmDKquHduTeH6KeK1UdNs9tQCAq9YArR8HYEdl8jhvn7kSH4ghqHUtR3adOo5/vQ8D0aJB0w102atK3hlxZddJ04RW','BoldEmbeddedReportingTools', 15, 0, 4, GETDATE(), 1, 1, 1, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI Cloud Quarterly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlZTgo40ooneiAcoMjhqeglxiYPlhVNLpy3RZxgEC4IiDKcMWJ4ehsuagu5nDRzrxHD+i4x36VHLKWxiAaJ8sZB0ImjONCUHkqQxOWsedzXSAPqrenFZNMUKHNqdUU10DUDHs9aWJ2j6DRpTGHj4ZM98vjHmHGpA2kZa42snPXqd7Q6SXTJM5gxjJ2EXzVusUeJNeYM99ZyZa9LEu3sYRB7OQ3xrw6zyFfF35BmYDunLB4J+NfSArY8LIPD9HySquPl26tLyuXf75lHmQooWT9tbUHEa1x+347FvOoYV/2LqOfiqXZxDAbo8myaV1ScBCmk=', null, 15, 0, 1, GETDATE(), 1, 1, 0, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI On-Premise Quarterly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlb1b0EHzJsSsrC8nglI02jZoU2GO6f2OSnvTv535RN/GZQP2eT0ORBjVB8VhZQs1p2mjjwIg5yPXyohU8F6ZmdcmR9vUFLP0jRStI3QYg3nkAC2SLV1HLgVHEosdaCW80G/sxes80Wx/fJuhXpCBMVBxOpej7Ugoll8DBwqLYosH/YW3aw8xtvty58tvUoJF8MOrF5SiLhV78doC0eDBwuekIT3PR9SelGEXfj1GPo642+sgaWmpDZMPN9VySs3AZmmXqwdOzgA9Sp+/dzxYzGNZDWI8bFVJQyqSVGja2TDT+L8cG/81EZRo2QUXGcnl3s=', 'BoldBIOnPremise', 15, 0, 3, GETDATE(), 1, 1, 0, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold Reports On-Premise Quarterly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdH0lN4e9YSrOWr8LYgiJK72iq/WSqvwe2nrJs53W3o/9j89S6A8KjNUmn4eaKJL8BYaDAUon6IaQqqHP7RgkmcBECCB7/XNq8yKJD3l742aHmg3HJ2dSLLjf9vgAV7Z6FzV2rj1nL6YvZqBKMQq2IxYCL1Z2kxZSvtsqWGAzwu5HWlKooNs+47u431hxS7sOdoArv/MjaiScgn0+YtMNP12M+tRDca71XqmdgNuhdiTVGrub2mdlp/+rLxT0uK9sTQXqEbb6N/bgoY7Af87ip0he+gbwVjh+6U3SaD4wg0kOBgRu6H8HYYQeQECY9aqtQUPMIFNSTmt00lssNSwvPNb', 'BoldReportsOnPremise', 15, 0, 4, GETDATE(), 1, 1, 0, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES (N'Bold Reports Viewer SDK Quarterly (Custom)', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdEzh1oY/yzboGRRvluxFlFdK36qUB+bA23LnhM82cKi4oJs+zGO7h1P465FEAo0tXgzeysK32JLvuYv0tiIn1EqDQNN9+di+3nws7mwsg09hzelR+WfEqpFd5QkcsxWS2kKQTOuyLrjabAKjd+4LysUZlfrnk3+f4OC9rcmFwpCGkOaRv7jSJPeqzqOWWCBySWnohC1NwTIAyfUtpKrGlBIG6ZrJuvbaiVHYM9GUn/Yi6YHqYSBdomt64xdteh5aWD0FMJCzTImtHHi0aUWwE6zSglGqdVFN/H9xCVxHYV9vGtU1XaUnPlzFQXqLAxzSldZ6BbgoPPc2IRnbsw+0zxZ','BoldEmbeddedReportingTools', 15, 0, 4, GETDATE(), 1, 1, 1, 1)


INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI Custom Embedded', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbYTmqepuVBchuMlBgiDXIfX+kpRcv9/DA7z9WKanNo0FeV6xm4gbLWhDCKFdqTthuZK5jKdoaRYTGsrgU/NeyHGL12gkA0t9kz5TevFwvy3PyW1+WzBOKIluNl8BLz01z+pfkUycasTq76VN2Hhfi+4AR+OSX/f3o+to40XolYsi3Dovz+6ANbig+3VITy5oG95BEsiwZSou2ZXVp9wfv8INEWpJNIi9bFsusUzU2pY1db/wP9eYNpcKuWp3Oxn/7GmgALEb+CiAdGfJ/VfnapmMFInQanF5fWqcaJ2PHcUw==', null, 15, 0, 1, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI Custom Embedded Annual', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlZcJT4WWpVxU8sZq8N70bPcSwJ3KRIvLxVi7RApI/5FKH71UZsgZQwLdRtzIq89bxevfnswsL1+baKPu9O7kCimNhJXXM8e1faBGX/aVTzlcD6AX7Vphg5imPcoFNGSz10m0FosYgIGlZlXX4V5eT45YM8E5FUFglwE1qZ0JqLxPfJnYMwO4OloY52Lhx+G+SvgNhJvsG1gEqRt0PgK9Y3i1iD/ilhmpFYh/F1uhfZpu8N5E7GWlEUtKFjuIygko6wUcLKxTicztsMGmzHPkg1YF+3veCL9JAPwSaz4TTgudkPo2DVnVLCofCssJNUFjYM=', null, 15, 0, 1, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI Custom Embedded Half-Yearly', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlZcJT4WWpVxU8sZq8N70bPc1l1Ng+ZmI2jUimJDtDhuRrMBi2zZF95Ry57kBtmge9ax5xC7U1dHKtvoqDPnYYdOAoWuAivf0vo3hxwIg5s+I7u/9icG/TvMNz3ClUxkreZdA36hmTpjlF1YU5U0R8SJ2tzs8vdomxgEnQLqLHDWyWAJre0eGV0J+8dFidUn+9qD/N8R2woW+imju0t4w/HR0Jfo8zOaj8PuyDF9sDwwGXLFpcfiw+X3HUk6E8tg5vBZpbSPlKd3z9w9AMu5hJbZ+uVs5wJLuOzP33kqUnLSGlSANfRddEmcakz/xSSj49M=', null, 15, 0, 1, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI Custom Embedded Quarterly', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlZcJT4WWpVxU8sZq8N70bPcbcKiQthKTaRB6cslAxQnxrhnqjTQPlpvtKLWQk9icnJD+MkogI50GTPICiFxSBTtPAmN4Kd182eZfal8xVTn5KkfPyqRR75UoFuJ3N8536DiSWJWpBN7yrR4oy19pobwqnAmqYjYUDbNmHvdR0Scw6WNV6TJ6/d8OT93MKaTdgCWb1ekBi3BQ4Euik62DMW7Unu0m79VtDYWrlcfl8MRkrQU15B5vi+X1CvmoWa/WGuPVJ9DoMOK2USRo2CKyh5HIYItUtbF1Wxj6U6Sos2N89qtgUnlh/DFfAcgQdVI3fE=', null, 15, 0, 1, GETDATE(), 1, 1, 0, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI On-Premise Custom Embedded', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbnGuUtEdfjHddJEZbJ/GfIkkC4Rv4GVzpCxLkAXxXft2J4DeySvtlP79Jc78WEMedI4MFTL/A0hTa4LqSTzTYQeYN86Xs1IEGCQRegZG2VlED3bzkIKlQRRLW3bpwSaQtwi/hPKvNGBvS6JkjqP1CpsrOUcOeMegzgld5SpbibCqiHsXK8+DcuzfyMS3EiI7hjYZgzgbsytD5v9WpyRaYDittOmKuofPgZEcXGs8wDvRpuhhle4fXUn0Aijjf162IH+FvoSGuqDTWx5ebmL/XXgvn0nRSQh0w6bxyJyS/3qCw3T909oLxcd8NI8oRx8iM=', 'BoldBIOnPremise', 15, 0, 3, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI On-Premise Custom Embedded Annual', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbnGuUtEdfjHddJEZbJ/GfIb6AsGAVCbMYql+hfm6stxmCmpZ7U8Zrsi+0Gvv/e3SgpnOikqTlGCGX+4WqBw4MRvZMrtWJECub9q3wtAysxeNok09kVjrZf/v9bf/NEM2eDd2fg5Nu/8Ww30v05yitvNCooxcJLwM2av5aWdWJa0dtyY7Hsux0sDzNqeQUEU7dNr1skm/A754tv81bE7TT3+01yPEm5gHZEIujwyDlUfd6Dj+PQHdZBpd2YyetSX+4GYn/CU9/GzPmxFKtUrKn16PqAfJxCHDHyn0XeQLdgT98h7+EjxVKolQeVI0v9Vfk=', 'BoldBIOnPremise', 15, 0, 3, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI On-Premise Custom Embedded Half-Yearly', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbnGuUtEdfjHddJEZbJ/GfIKwu1znpJ3c8fxQwNW7nVqd7REYUNOL9zh1Dct08M/VX7d0FIVmZS16aKcjG+jIhqzmsFxyfxb0gLFCVEl68WEsMf+zopk/iuY4baubWFRtpkCVR4p74gqSNoa7MhF7P/+rvncVqVgoajjdCXZrp64L28Wl8TP28awIMBmSfTpy5Ra/JEhDLSQwSnGmY1y2xXdNr71PL/3y8G5MZrutxTHbuq2g96pyr+FLSyYWP+XujmK0I26g17ZzGDq6PGyMyj1dE55KS9NEMKWsYlXUYDFKafXFwhDoPteqX/jzPzvm0VZB+6HOsvYZVN6pO78rq7', 'BoldBIOnPremise', 15, 0, 3, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold BI On-Premise Custom Embedded Quarterly', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTcBZykDiy0KRW9rVEx9owlbnGuUtEdfjHddJEZbJ/GfIP3hAsKwAwW3VlOAAoViCTW96e8nHQMhbUMZdAsLBwVjpszp3dVgR02NK1M4or9jbYB/RbwJceZHWrErZKQag/QmZmfuuohyEoF9k7D+xUoRPHThceGdKJswFQhmgzTW1/MU+A0bgqM9pz+YhPFN+o0A3w4HZXpCJnL0kkdzEop+kpWS8GPv6KnY2vPL7eozbEB9o3ryl3wHILuGYybtnHr6EzwnaJ+dTpjOFZj2opXORwH9CIHJd3sK2CjWx8pPlt8hpHRLjwpm9LPwgoHgQfdyTaKx2nvR3IITKs4CClVV7fM/vKtTytSmkqoT5lcel', 'BoldBIOnPremise', 15, 0, 3, GETDATE(), 1, 1, 0, 1)

INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold Reports On-Premise Custom Embedded', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdH0lN4e9YSrOWr8LYgiJK72DWcesbcGl2T1dTg9vRZBcEvzQndVYZP1R5sG29BHnDShE64UQC6sUxLoYwmYkpWyZAY3LXMdpc1A0QWHO8pPLEBj9Z3GGIGBHHNZmNvUFFzfEElY7TtfwMA6L/GXbgW3Hz88FkQ3U1PpvbZDOtFIr55qvhDJ2Df44C8Q4A/n35wU+K3WF9gYhuyfGYhH7eu744LnrV6Ql9a+TAuRl9MXU6IQqZc4NXji6cSI0HNPHQ81hQfohFI0AV+kZHmEUWYHzlw02C1Tkuf4hw8CragW4nTccXOsdeDpvHQWkOPl+j0=', 'BoldReportsOnPremise', 15, 0, 4, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold Reports On-Premise Custom Embedded  Annual', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdH0lN4e9YSrOWr8LYgiJK72d2foW0omyhnepZ0Hq8xUa3FbD61cfHxOcpXpQ/7YR4+CBQst4yG6M9mpg+RB/ZMcxXfwwqkwhAsOFJe3bnb67KtKhUAlCn+TdIeOkVU1sDUb66LNp50vbxRs6R1y9GyKuEx4theoBu9i+REju8wtUc0UqXaMegoM33Ny4tUwPPgsAjGPsEoyu2mK8mMVXM7yqOkKGO4oZyCtLNAWlb+x5S/oJfwS4TFGJ+JkAhWRNp81nhw8Uk6n+1cYb8sfT6dQihIOzHLcKKS7ZtM7scchxGzqg9SIliSqx+CwQXiwXV1z8eM0dsoC+A7XH2CHPaYF', 'BoldReportsOnPremise', 15, 0, 4, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold Reports On-Premise Custom Embedded Half-Yearly', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdH0lN4e9YSrOWr8LYgiJK72d2foW0omyhnepZ0Hq8xUaxQdVYQUrneY9gAB1vgGHICIt5S05X6yhIy8uaP9l9kNyW5f1jaq0SjYzHqnU6U5aFCH+joLtsnYfrOE0quIKktYvPZtKHCurA1BIJ0imSbBTWa0T8ivgsvRMX6cq1jjBm3XST9lPg4rLLw/H8LvWu3b1nvYDRp45YxBDvc2/L+uYkm30//2y/9yPZ1uK7WRsKXovKgXzp5WdUC5COYQQBqaubHujS6Lh8Y80Dl9V0G9eJ4ZP7t+grG7dJKDGcKphOikF9BNFDwvrDJ+Vs0ROjviay5JmKEnTcd/XdLSkpJJ', 'BoldReportsOnPremise', 15, 0, 4, GETDATE(), 1, 1, 0, 1)
INSERT[dbo].[SaaSPlan]([Name], [PlanSchema], [SetupName], [TrialDays], [PriorityOrder], [TenantTypeId], [ModifiedDate], [IsInternal], [IsCustom], [IsSDK], [IsActive]) VALUES(N'Bold Reports On-Premise Custom Embedded Quarterly', N'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+Pgx2QJF/USUQO+x5MbgT4GUjq4oAyDjZDnf5Z4UM9QDqnazGmJw+/45VCpaPCbEnwVa+f1wsm7TbmoaIi/8oRq7HTQTtxYgE86RQgdJyA4/XT/Om0Fv+GPZJt7mOZTqzqXVMKcHzoxQsQgQOTM6x1T+J+ntEcyO4HcUpEqqPg7vrKj2zIpyUTvDr34WDI9bwRtVlrOQoWiUT3ExL68RVcUq6rnR+7Xt8h5A2rQ/Q7CMo5+s8w3arhaP/mn8r7f0sHkfWDaDOvlNdB8qNlOMB7iY3SOPLINIaNn3B6G7Yq5EbEtS4yb63k+DFUSrl5iDVJ1171RfbY7yTQns6xZHISkF0fQyEYcpYoUK1+68MLkrz3O7eHMLMbiutXP179LCVJn3rKcIuz/lqsnzDVCrVHwLrbM+C7mUZcseMwcdp1FsCloDn22KLiDZVSf8kSOC1hWtm6lzKtcn6jEyTyanqKdqUPIvcVFkcEiEzXQ8u5QWAFgopEH0dF7sCO2fCTGa670aPW4KSpQxiJ/hFUc59ehNILeOEGSpFy71XWGo47+ufTTWmNBgnpOmK/s0DBonIDdH0lN4e9YSrOWr8LYgiJK72d2foW0omyhnepZ0Hq8xUa/CdHNm300mNoLHsoq6xaPaiUZGUieLNlNNr7SMOyDgUxdVLKWl8b+8ollc+NdP0Tt4JfYaRHl3CeWzItOBhNvRZM8A+WMDwzfTJHTYzwTFGMGVUFYeMeH3lVhdXVfuUvUcBb0WS/v1+9ACLpL6WKpcaprQOaAh8WqCCQeTyMKk/vJtCPEQwG+EUpNV75ij497k+Vq8LYJ2Ad61Iz5vEY5g3Z1Zc0sVPbBP2Bh7FptlYNxmDM/CNiKtOj4Uk9rf8n9bG5ewB1+v2xCeps/js7N4AIlEzPEd2EhKH34QEzVtQ', 'BoldReportsOnPremise', 15, 0, 4, GETDATE(), 1, 1, 0, 1)

--development & staging product ids
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7935, N'Bold BI Cloud Half-Yearly (Custom)', 1, 48, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7936, N'Bold BI Cloud Half-Yearly Subscription (Custom)', 2, 48, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7939, N'Bold BI On-Premise Half-Yearly (Custom)', 1, 49, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7940, N'Bold BI On-Premise Half-Yearly Subscription (Custom)', 2, 49, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7943, N'Bold Reports On-Premise Half-Yearly (Custom)', 1, 50, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7944, N'Bold Reports On-Premise Half-Yearly Subscription (Custom)', 2, 50, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7945, N'Bold Reports Viewer SDK Half-Yearly (Custom)', 1, 51, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7946, N'Bold Reports Viewer SDK Half-Yearly Subscription (Custom)', 2, 51, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7937, N'Bold BI Cloud Quarterly (Custom)', 1, 52, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7938, N'Bold BI Cloud Quarterly Subscription (Custom)', 2, 52, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7941, N'Bold BI On-Premise Quarterly (Custom)', 1, 53, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7942, N'Bold BI On-Premise Quarterly Subscription (Custom)', 2, 53, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7947, N'Bold Reports On-Premise Quarterly (Custom)', 1, 54, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7948, N'Bold Reports On-Premise Quarterly Subscription (Custom)', 2, 54, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7949, N'Bold Reports Viewer SDK Quarterly (Custom)', 1, 55, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7950, N'Bold Reports Viewer SDK Quarterly Subscription (Custom)', 2, 55, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7951, N'Bold BI Custom Embedded', 1, 56, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7952, N'Bold BI Custom Embedded Subscription', 2, 56, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7953, N'Bold BI Custom Embedded Annual', 1, 57, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7954, N'Bold BI Custom Embedded Annual Subscription', 2, 57, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7955, N'Bold BI Custom Embedded Half-Yearly', 1, 58, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7956, N'Bold BI Custom Embedded Half-Yearly Subscription', 2, 58, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7957, N'Bold BI Custom Embedded Quarterly', 1, 59, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7958, N'Bold BI Custom Embedded Quarterly Subscription', 2, 59, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7959, N'Bold BI On-Premise Custom Embedded', 1, 60, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7960, N'Bold BI On-Premise Custom Embedded Subscription', 2, 60, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7961, N'Bold BI On-Premise Custom Embedded Annual', 1, 61, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7962, N'Bold BI On-Premise Custom Embedded Annual Subscription', 2, 61, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7963, N'Bold BI On-Premise Custom Embedded Half-Yearly', 1, 62, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7964, N'Bold BI On-Premise Custom Embedded Half-Yearly Subscription', 2, 62, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7965, N'Bold BI On-Premise Custom Embedded Quarterly', 1, 63, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7966, N'Bold BI On-Premise Custom Embedded Quarterly Subscription', 2, 63, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7967, N'Bold Reports On-Premise Custom Embedded', 1, 64, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7968, N'Bold Reports On-Premise Custom Embedded Subscription', 2, 64, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7969, N'Bold Reports On-Premise Custom Embedded Annual', 1, 65, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7970, N'Bold Reports On-Premise Custom Embedded Annual Subscription', 2, 65, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7971, N'Bold Reports On-Premise Custom Embedded Half-Yearly', 1, 66, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7972, N'Bold Reports On-Premise Custom Embedded Half-Yearly Subscription', 2, 66, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7973, N'Bold Reports On-Premise Custom Embedded Quarterly', 1, 67, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7974, N'Bold Reports On-Premise Custom Embedded Quarterly Subscription', 2, 67, 1)

--production product ids - check with website team before using this query.
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7933, N'Bold BI Cloud Half-Yearly (Custom)', 1, 48, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7934, N'Bold BI Cloud Half-Yearly Subscription (Custom)', 2, 48, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7937, N'Bold BI On-Premise Half-Yearly (Custom)', 1, 49, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7938, N'Bold BI On-Premise Half-Yearly Subscription (Custom)', 2, 49, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7941, N'Bold Reports On-Premise Half-Yearly (Custom)', 1, 50, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7942, N'Bold Reports On-Premise Half-Yearly Subscription (Custom)', 2, 50, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7943, N'Bold Reports Viewer SDK Half-Yearly (Custom)', 1, 51, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7944, N'Bold Reports Viewer SDK Half-Yearly Subscription (Custom)', 2, 51, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7935, N'Bold BI Cloud Quarterly (Custom)', 1, 52, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7936, N'Bold BI Cloud Quarterly Subscription (Custom)', 2, 52, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7939, N'Bold BI On-Premise Quarterly (Custom)', 1, 53, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7940, N'Bold BI On-Premise Quarterly Subscription (Custom)', 2, 53, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7945, N'Bold Reports On-Premise Quarterly (Custom)', 1, 54, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7946, N'Bold Reports On-Premise Quarterly Subscription (Custom)', 2, 54, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7947, N'Bold Reports Viewer SDK Quarterly (Custom)', 1, 55, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7948, N'Bold Reports Viewer SDK Quarterly Subscription (Custom)', 2, 55, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7949, N'Bold BI Custom Embedded', 1, 56, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7950, N'Bold BI Custom Embedded Subscription', 2, 56, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7951, N'Bold BI Custom Embedded Annual', 1, 57, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7952, N'Bold BI Custom Embedded Annual Subscription', 2, 57, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7953, N'Bold BI Custom Embedded Half-Yearly', 1, 58, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7954, N'Bold BI Custom Embedded Half-Yearly Subscription', 2, 58, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7955, N'Bold BI Custom Embedded Quarterly', 1, 59, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7956, N'Bold BI Custom Embedded Quarterly Subscription', 2, 59, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7957, N'Bold BI On-Premise Custom Embedded', 1, 60, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7958, N'Bold BI On-Premise Custom Embedded Subscription', 2, 60, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7959, N'Bold BI On-Premise Custom Embedded Annual', 1, 61, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7960, N'Bold BI On-Premise Custom Embedded Annual Subscription', 2, 61, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7961, N'Bold BI On-Premise Custom Embedded Half-Yearly', 1, 62, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7962, N'Bold BI On-Premise Custom Embedded Half-Yearly Subscription', 2, 62, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7963, N'Bold BI On-Premise Custom Embedded Quarterly', 1, 63, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7964, N'Bold BI On-Premise Custom Embedded Quarterly Subscription', 2, 63, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7965, N'Bold Reports On-Premise Custom Embedded', 1, 64, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7966, N'Bold Reports On-Premise Custom Embedded Subscription', 2, 64, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7967, N'Bold Reports On-Premise Custom Embedded Annual', 1, 65, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7968, N'Bold Reports On-Premise Custom Embedded Annual Subscription', 2, 65, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7969, N'Bold Reports On-Premise Custom Embedded Half-Yearly', 1, 66, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7970, N'Bold Reports On-Premise Custom Embedded Half-Yearly Subscription', 2, 66, 1)

INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7971, N'Bold Reports On-Premise Custom Embedded Quarterly', 1, 67, 1)
INSERT [dbo].[IntranetProductType] ([ProductId], [ProductName], [OrderTypeId], [PlanId], [IsActive]) VALUES (7972, N'Bold Reports On-Premise Custom Embedded Quarterly Subscription', 2, 67, 1)