CREATE TABLE BOLDTC_CouponLogType (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Name CLOB NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_COUPONLOGTYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_CouponLog (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CouponLogTypeId NUMBER NOT NULL,
  PaymentLogId VARCHAR2(36) NOT NULL,
  LogComments NUMBER NOT NULL,
  CreatedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_COUPONLOG PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantPaymentSubscription (
  Id VARCHAR2(36) NOT NULL,
  TenantInfoId VARCHAR2(36) NOT NULL,
  StripeCustomerId NVARCHAR2(255) NOT NULL UNIQUE,
  SubscriptionId NVARCHAR2(255) NOT NULL UNIQUE,
  ModifiedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_TENANTPAYMENTSUBSCRIPTION PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantInvoiceDetails (
  Id VARCHAR2(36) NOT NULL,
  SubscriptionId VARCHAR2(36) NOT NULL,
  Amount NUMBER NOT NULL,
  InvoiceId NVARCHAR2(255) NOT NULL,
  ChargeId NVARCHAR2(255) NOT NULL,
  PaymentDate TIMESTAMP NOT NULL,
  CONSTRAINT PK_BOLDTC_TENANTINVOICEDETAILS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantPaymentLog (
  Id VARCHAR2(36) NOT NULL,
  TenantInfoId VARCHAR2(36) NOT NULL,
  SubscriptionId VARCHAR2(36) NOT NULL,
  LogComments CLOB NOT NULL,
  CreatedDate TIMESTAMP NOT NULL,
  Status NVARCHAR2(255) NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_TENANTPAYMENTLOG PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_ServerVersion (
  Id NUMBER NOT NULL,
  VersionNumber NVARCHAR2(20) NOT NULL,
  CONSTRAINT PK_BOLDTC_SERVERVERSION PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SqlServer (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ServerName NVARCHAR2(255) NOT NULL UNIQUE,
  Username NVARCHAR2(255) NOT NULL,
  Password NVARCHAR2(255),
  DatabaseLimit NUMBER NOT NULL,
  SqlServerType NUMBER NOT NULL,
  TenantType NUMBER NOT NULL,
  IsAvailable NUMBER(1) DEFAULT 1 NOT NULL,
  IsActive NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_BOLDTC_SQLSERVER PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SqlElasticPool (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PoolName NVARCHAR2(255) NOT NULL UNIQUE,
  SqlServerId NUMBER NOT NULL,
  DatabaseLimit NUMBER NOT NULL,
  SqlServerType NUMBER NOT NULL,
  TenantType NUMBER NOT NULL,
  IsAvailable NUMBER(1) DEFAULT 1 NOT NULL,
  IsActive NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_BOLDTC_SQLELASTICPOOL PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_Tenant (
  Id VARCHAR2(36) NOT NULL,
  DNS NVARCHAR2(255) NOT NULL,
  Subdomain NVARCHAR2(255),
  TenantIdentifier NVARCHAR2(255),
  TenantName NVARCHAR2(255) NOT NULL,
  CustomDomain NVARCHAR2(255),
  UseSiteIdentifier NUMBER(1) DEFAULT 1 NOT NULL,
  UserId VARCHAR2(36) NOT NULL,
  CreatedDate TIMESTAMP NOT NULL,
  ModifiedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  IsInternal NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_BOLDTC_TENANT PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SaaSPlan (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Name NVARCHAR2(255) NOT NULL,
  PlanSchema CLOB,
  ModifiedDate TIMESTAMP NOT NULL,
  IsInternal NUMBER(1) NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_SAASPLAN PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantLogType (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Name NVARCHAR2(100),
  IsActive NUMBER(1),
  CONSTRAINT PK_BOLDTC_TENANTLOGTYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantLog (
  Id VARCHAR2(36) NOT NULL,
  TenantInfoId VARCHAR2(36) NOT NULL,
  TenantLogType NUMBER NOT NULL,
  LogComments CLOB,
  IpAddress NVARCHAR2(100),
  FromStatus NUMBER,
  ToStatus NUMBER NOT NULL,
  UpdatedUserId VARCHAR2(36),
  SourceTypeId NUMBER,
  OptionalData CLOB,
  CreatedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_TENANTLOG PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantStatus (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Name NVARCHAR2(100) NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_TENANTSTATUS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_Coupon (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Coupon NVARCHAR2(255) NOT NULL UNIQUE,
  CouponLimit NUMBER NOT NULL,
  CouponDuration NUMBER NOT NULL,
  CouponExpirationDate NUMBER NOT NULL,
  CreateDate TIMESTAMP NOT NULL,
  ModifiedDate TIMESTAMP NOT NULL,
  CreatedById VARCHAR2(36) NOT NULL,
  ModifiedById VARCHAR2(36) NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_COUPON PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_UserPreference (
  Id VARCHAR2(36) NOT NULL,
  UserId VARCHAR2(36) NOT NULL,
  Language NVARCHAR2(2000),
  TimeZone NVARCHAR2(100),
  RecordSize NUMBER,
  ItemSort NVARCHAR2(2000),
  ItemFilters NVARCHAR2(2000),
  Notifications NVARCHAR2(2000),
  ModifiedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_USERPREFERENCE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_User (
  Id VARCHAR2(36) NOT NULL,
  FirstName NVARCHAR2(255) NOT NULL,
  LastName NVARCHAR2(255),
  DisplayName NVARCHAR2(512),
  Username NVARCHAR2(255) NOT NULL,
  Email NVARCHAR2(350) NOT NULL UNIQUE,
  Password NVARCHAR2(512) NOT NULL,
  Contact NVARCHAR2(20),
  Company NVARCHAR2(255),
  Picture NVARCHAR2(100),
  CreatedDate TIMESTAMP NOT NULL,
  ModifiedDate TIMESTAMP,
  LastLogin TIMESTAMP,
  PasswordChangedDate TIMESTAMP,
  ActivationExpirationDate TIMESTAMP NOT NULL,
  ActivationCode NVARCHAR2(255) NOT NULL,
  VerificationCode NVARCHAR2(100),
  ResetPasswordCode NVARCHAR2(255),
  LastResetAttempt TIMESTAMP,
  ExternalProviderId NVARCHAR2(512),
  DirectoryTypeId NUMBER NOT NULL,
  IsActivated NUMBER(1) NOT NULL,
  ActivationMethod NVARCHAR2(20),
  IsActive NUMBER(1) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  Status NUMBER(5),
  IsMfaEnabled NUMBER(1) DEFAULT 0 NOT NULL,
  MfaType NUMBER(5),
  CONSTRAINT PK_BOLDTC_USER PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_UserLogin (
  Id VARCHAR2(36) NOT NULL,
  UserId VARCHAR2(36) NOT NULL,
  SessionId VARCHAR2(36),
  DirectoryTypeId NUMBER NOT NULL,
  ClientToken NVARCHAR2(2000) NOT NULL,
  LoggedInDomain NVARCHAR2(255) NOT NULL,
  IpAddress NVARCHAR2(255) NOT NULL,
  Browser NVARCHAR2(255),
  LoggedInTime TIMESTAMP NOT NULL,
  LastActive TIMESTAMP,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_USERLOGIN PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TMUserGroup (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  GroupId NUMBER NOT NULL,
  UserId VARCHAR2(36) NOT NULL,
  ModifiedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_TMUSERGROUP PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TMGroup (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Name NVARCHAR2(255) NOT NULL,
  Description NVARCHAR2(1026),
  Color NVARCHAR2(255) NOT NULL,
  DirectoryTypeId NUMBER NOT NULL,
  ExternalProviderId NVARCHAR2(512),
  ModifiedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_TMGROUP PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantUser (
  Id VARCHAR2(36) NOT NULL,
  UserId VARCHAR2(36) NOT NULL,
  TenantInfoId VARCHAR2(36) NOT NULL,
  IsFavorite NUMBER(1) DEFAULT 0 NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  LastAccessedDate TIMESTAMP NULL,
  CONSTRAINT PK_BOLDTC_TENANTUSER PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_DirectoryType (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  DirectoryName NVARCHAR2(100) NOT NULL UNIQUE,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_DIRECTORYTYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_RecurrenceType (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Name NVARCHAR2(100) NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_RECURRENCETYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_Schedule (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  RecurrenceInfo NVARCHAR2(2000) NOT NULL,
  RecurrenceTypeId NUMBER NOT NULL,
  ScheduleTypeId NUMBER NOT NULL,
  StartDate TIMESTAMP NOT NULL,
  EndDate TIMESTAMP NOT NULL,
  EndAfter NUMBER NOT NULL,
  NextSchedule TIMESTAMP NOT NULL,
  IsEnabled NUMBER(1) NOT NULL,
  CreatedById VARCHAR2(36) NOT NULL,
  ModifiedById VARCHAR2(36) NOT NULL,
  CreatedDate TIMESTAMP NOT NULL,
  ModifiedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_SCHEDULE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_ScheduleType (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Name NVARCHAR2(100) NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_SCHEDULETYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_ScheduleLog (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ScheduleId NUMBER NOT NULL,
  ScheduleStatusId NUMBER NOT NULL,
  ExecutedDate TIMESTAMP NOT NULL,
  ModifiedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_SCHEDULELOG PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_ScheduleStatus (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Name NVARCHAR2(100) NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_SCHEDULESTATUS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SAMLSettings (
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ApplicationId NVARCHAR2(100),
  ApplicationIdURI NVARCHAR2(2000),
  TenantName NVARCHAR2(100),
  MobileApplicationId NVARCHAR2(100),
  IsSloEnabled NUMBER(1) NOT NULL,
  IsEnabled NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_SAMLSETTINGS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SystemSettings (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    SystemKey NVARCHAR2(255) NOT NULL,
    SystemValue NVARCHAR2(2000),
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_SYSTEMSETTINGS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_AzureADCredential (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TenantName NVARCHAR2(255),
    ClientId NVARCHAR2(100),
    ClientSecret NVARCHAR2(100),
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_AZUREADCREDENTIAL PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantType (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Type NVARCHAR2(255) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_TENANTTYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantInfo (
    Id VARCHAR2(36) NOT NULL,
    TenantId VARCHAR2(36) NOT NULL,
    TenantTypeId NUMBER(5) NOT NULL,
    ClientSecret NVARCHAR2(512) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    SaaSPlanId NUMBER,
    DatabaseType NUMBER(5) DEFAULT 0,
    BlobConnectionString CLOB,
    ConnectionString CLOB,
    SchemaName NVARCHAR2(2000),
	Prefix NVARCHAR2(2000),
    AdditionalParameters CLOB,
    MaintenanceDatabase NVARCHAR2(255),
    TenantSQLServerId NUMBER,
    ElasticPoolId NUMBER,
    ImDbDatabaseType NUMBER(5) DEFAULT 0,
    ImDbConnectionString CLOB,
    ImDbSqlServerId NUMBER,
    ImDbElasticPoolId NUMBER,
    ImDbMaintenanceDatabase NVARCHAR2(255),
    ImDbAdditionalParameters CLOB,
    TenantStatus NUMBER(5) NOT NULL,
    BillingAddressId VARCHAR2(36),
    StatusUpdatedDate TIMESTAMP NOT NULL,
    PaymentStatus NVARCHAR2(50),
    RecurringPaymentDate TIMESTAMP,
    IsTrialExpired NUMBER(1) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    IsDeleted NUMBER(1) NOT NULL,
    IsMaster NUMBER(1) NOT NULL,
    IsolationCode NVARCHAR2(2000),
    IsTenantIsolationCodeEnabled NUMBER(1) DEFAULT 0 NOT NULL,
    IsRowLevelSecurityEnabled NUMBER(1) DEFAULT 1 NOT NULL,
    ResourceLimitationSettings CLOB,
    UseCustomBranding NUMBER(1) NOT NULL,
    IsNewImDbDatabase NUMBER(1) NOT NULL,
    IsNewDatabase NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_TENANTINFO PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_UserBillingAddress (
    Id VARCHAR2(36) NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    BillingEmail NVARCHAR2(255) NOT NULL,
    BillingAddress CLOB NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_USERBILLINGADDRESS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_AccountDeleteRequest (
    Id VARCHAR2(36) NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    UserTenantStatus CLOB,
    RequestedTime TIMESTAMP NOT NULL,
    CancelledTime TIMESTAMP,
    DeletedTime TIMESTAMP,
    IsCancelled NUMBER(1),
    IsDeleted NUMBER(1) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_ACCOUNTDELETEREQUEST PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_Addon (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name NVARCHAR2(255) NOT NULL,
    StripePlanId NVARCHAR2(255) NOT NULL,
    PlanSchema CLOB,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_ADDON PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantAddon (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    AddonId NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    LastPaymentDate TIMESTAMP,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_TENANTADDON PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_CustomPlan (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    Price NUMBER NOT NULL,
    PlanInfo CLOB,
    HasTrial NUMBER(1) NOT NULL,
    TrialDays NUMBER NOT NULL,
    IsEnterprise NUMBER(1),
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_CUSTOMPLAN PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_Country (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    Name NVARCHAR2(100) NOT NULL,
    CountryCode NVARCHAR2(2) NOT NULL,
    IsActive NUMBER(1) NOT NULL
);

CREATE TABLE BOLDTC_ExternalIdP (
    Id VARCHAR2(36) NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    Detail CLOB NOT NULL,
    DirectoryTypeId NUMBER NOT NULL,
    CredentialTypeId NUMBER NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_EXTERNALIDP PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_IdPCredentialType (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CredentialType NVARCHAR2(255) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_IDPCREDENTIALTYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SqlElasticPoolEdition (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PoolEditionName VARCHAR2(255) NOT NULL,
    PoolDtu NUMBER NOT NULL,
    PoolStorageinGB NUMBER NOT NULL,
    DatabaseDtuMinInGB NUMBER NOT NULL,
    DatabaseDtuMaxInGB NUMBER NOT NULL,
    DatabaseLimit NUMBER NOT NULL,
    Region VARCHAR2(255) NOT NULL,
    IsCurrent NUMBER(1) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_ELASTICPOOLEDITION PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SqlServerEdition (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Version VARCHAR2(255) NOT NULL,
    DatabaseLimit NUMBER NOT NULL,
    Region NVARCHAR2(100) NOT NULL,
    IsCurrent NUMBER(1) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_SQLSERVEREDITION PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TMUser (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_TMUSER PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SqlServerType (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    SqlServerType NVARCHAR2(255) NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_SQLSERVERTYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_OAuthToken (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Token NVARCHAR2(2000),
    Ticket NVARCHAR2(2000),
    ModifiedDate TIMESTAMP,
    CONSTRAINT PK_BOLDTC_OAUTHTOKEN PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_InternalApps (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientId VARCHAR2(36) NOT NULL UNIQUE,
    ClientSecret NVARCHAR2(2000) NOT NULL,
    Name NVARCHAR2(100) NOT NULL,
    URL NVARCHAR2(100) NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_INTERNALAPPS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_FormType (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name NVARCHAR2(255) NOT NULL,
    Url NVARCHAR2(2000) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_FORMTYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_RegistrationFormVersion (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name NVARCHAR2(255) NOT NULL,
    FormTypeId NUMBER NOT NULL,
    Location NVARCHAR2(255) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsLatest NUMBER(1) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_REGISTRATIONFORMVERSION PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TERMSOFUSEVERSION (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name NVARCHAR2(255) NOT NULL,
    Location NVARCHAR2(255) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsLatest NUMBER(1) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_TERMSOFUSEVERSION PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_PrivacyPolicyVersion (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name NVARCHAR2(255) NOT NULL,
    Location NVARCHAR2(255) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsLatest NUMBER(1) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_PRIVACYPOLICYVERSION PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_PrivacyAcceptance (
    Id VARCHAR2(36) NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    PrivacyPolicyVersion NUMBER NOT NULL,
    TermsOfUseVersion NUMBER NOT NULL,
    RegistrationFormVersion NUMBER NOT NULL,
    IpAddress NVARCHAR2(50) NOT NULL,
    Country NVARCHAR2(100) NOT NULL,
    Url NVARCHAR2(2000) NOT NULL,
    HttpHeaders NVARCHAR2(2000) NOT NULL,
    DateTime TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_PRIVACYACCEPTANCE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_FeedBack (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    IncidentId NUMBER NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    FeedbackFormId NUMBER NOT NULL,
    Experience NVARCHAR2(20) NULL,
    FeedbackSubject NVARCHAR2(20) NULL,
    CancelReason NCLOB NULL,
    Comments NCLOB NULL,
    CanContact NUMBER(1) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_FEEDBACK PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_Support (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    IncidentId NUMBER NOT NULL,
    UpdateId NUMBER NOT NULL,
    TenantInfoId VARCHAR2(36) NULL,
    IsConciergeSupport NUMBER(1) NOT NULL,
    CreatedBy VARCHAR2(36) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_Support PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantActivity (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ItemId VARCHAR2(36) NULL,
    ChildId NCLOB NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    ItemType NCLOB NOT NULL,
    ItemSubType NCLOB NOT NULL,
    Action NCLOB NOT NULL,
    DetailActionId NUMBER DEFAULT 0 NOT NULL,
    ActivityLogInfo NCLOB NULL,
    LoggedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_TenantActivity PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_PreviewFeatures (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    FeatureName NVARCHAR2(255) NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    Value NCLOB NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_PreviewFeatures PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_KcTenants (
    Id VARCHAR2(36) NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    KcId NUMBER NOT NULL,
    KcName NVARCHAR2(1024) NOT NULL,
    CreatedDate TIMESTAMP NULL,
    ModifiedDate TIMESTAMP NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT BOLDTC_KcTenants_PK PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SSLCertificate (
    Id VARCHAR2(36) NOT NULL,
    ThumbPrint NVARCHAR2(1024) NOT NULL,
    HostNames NCLOB NOT NULL,
    ExpirationDate TIMESTAMP NOT NULL,
    CreatedById VARCHAR2(36) NOT NULL,
    ModifiedById VARCHAR2(36) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT BOLDTC_SSLCertificate_PK PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SSLMapping (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TenantId VARCHAR2(36) NOT NULL,
    CertificateId VARCHAR2(36) NOT NULL,
    CreatedById VARCHAR2(36) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT BOLDTC_SSLMapping_PK PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SalesRequests (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_SALESREQUESTS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_IntranetProductType (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ProductId NUMBER NOT NULL,
    ProductName NVARCHAR2(1024) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT BOLDTC_IntranetProductType_PK PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_SourceType (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name NVARCHAR2(100) NOT NULL,
    URL NVARCHAR2(100) NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_SOURCETYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_AuthType (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name NVARCHAR2(255) NOT NULL UNIQUE,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_AuthType PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_AuthProvider (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name NVARCHAR2(255) NOT NULL UNIQUE,
    AuthTypeId NUMBER NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_AuthProvider PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_GlobalAuthControl (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    AuthTypeId NUMBER NOT NULL,
    IsEnabled NUMBER(1) NOT NULL,
    CreatedBy VARCHAR2(36) NOT NULL,
    ModifiedBy VARCHAR2(36) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_GlobalAuthControl PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_AuthSettings (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TenantInfoId VARCHAR2(36) NULL,
    AuthProviderId NUMBER NOT NULL,
    Settings NCLOB,
    EncryptionValues NCLOB,
    IsEnabled NUMBER(1) NOT NULL,
    CreatedBy VARCHAR2(36) NULL,
    ModifiedBy VARCHAR2(36) NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsDefaultAuthentication NUMBER(1) DEFAULT 0 NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_AuthSettings PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_UserLog (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    LogAction NVARCHAR2(255) NOT NULL,
    UserId VARCHAR2(36) NULL,
    Message NCLOB NOT NULL,
    RequestedById VARCHAR2(36) NULL,
    IpAddress NVARCHAR2(100) NOT NULL,
    LogDate TIMESTAMP NOT NULL,
    ReferrerUrl NCLOB NULL,
    IsActive NUMBER(1) NOT NULL,
    AdditionalData NCLOB NULL,
    Source NUMBER NULL,
    CONSTRAINT PK_BOLDTC_UserLog PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_AzureBlob (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TenantInfoId VARCHAR2(36) NOT NULL,
    AccountName NCLOB NOT NULL,
    AccessKey NCLOB NOT NULL,
    Uri NCLOB NULL,
    ContainerName NCLOB NOT NULL,
    ConnectionType NCLOB NOT NULL,
    ConnectionString NCLOB NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_AzureBlob PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_UserStatus (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Status NVARCHAR2(100) NOT NULL,
    Value NUMBER NOT NULL UNIQUE,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_USERSTATUS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_UserToken (
    Id VARCHAR2(36) NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    Name NVARCHAR2(255) NOT NULL,
    Value NVARCHAR2(255) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_USERTOKEN PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_MfaType (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Type NVARCHAR2(100) NOT NULL,
    Value NUMBER NOT NULL UNIQUE,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_MFATYPE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_Source (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Type NVARCHAR2(100) NOT NULL,
    Value NUMBER NOT NULL UNIQUE,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_SOURCE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_EmailActivityLog (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Event NVARCHAR2(255) NOT NULL,
    RecipientEmail NVARCHAR2(255) NOT NULL,
    SenderEmail NVARCHAR2(255) NOT NULL,
    MailSubject NVARCHAR2(255) NOT NULL,
    MailBody NCLOB NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NULL,
    InitiatedBy NVARCHAR2(255) NULL,
    UserId VARCHAR2(36) NOT NULL,
    Status NUMBER NOT NULL,
    StatusMessage NCLOB NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_EMAILACTIVITYLOG PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_ActivityLog (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    EventCategory NVARCHAR2(100) NOT NULL,
    EventType NVARCHAR2(100) NOT NULL,
    EventDate TIMESTAMP NOT NULL,
    InitiatedBy NVARCHAR2(255) NULL,
    TargetUser NVARCHAR2(255) NULL,
    IpAddress NVARCHAR2(100) NOT NULL,
    AppSource NVARCHAR2(255) NULL,
    AppType NVARCHAR2(255) NULL,
    EventLog NCLOB NULL,
    ClientId NVARCHAR2(100) NULL,
    UserAgent NVARCHAR2(255) NULL,
    IsActive NUMBER(1) NOT NULL,
    CanDelete NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_ACTIVITYLOG PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_QueryMetrics (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    DashboardID NVARCHAR2(100),
    WidgetID NVARCHAR2(100),
    WidgetName NVARCHAR2(100),
    QueryStartTime TIMESTAMP WITH TIME ZONE,
    QueryEndTime TIMESTAMP WITH TIME ZONE,
    Query NCLOB,
    QueryStatus NVARCHAR2(100),
    RowsRetrieved NUMBER,
    QueryPlan NCLOB,
    TrackingId NVARCHAR2(100),
    QueryType NVARCHAR2(100),
    QueryExecutionTime NVARCHAR2(100),
    DashboardName NVARCHAR2(100),
    UserName NVARCHAR2(100),
    TenantId VARCHAR2(36),
    UserId NVARCHAR2(100),
    DataSourceID NVARCHAR2(100),
    DataSourceName NVARCHAR2(100),
    CONSTRAINT PK_BOLDTC_QUERYMETRICS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_CustomEmailTemplate (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    IsEnabled NUMBER(1),
    DisclaimerContent NVARCHAR2(255) NOT NULL,
    HeaderContent NVARCHAR2(255) NULL,
    Subject NVARCHAR2(255),
    TemplateName NVARCHAR2(255),
    Language NVARCHAR2(255) NOT NULL,
    MailBody NCLOB NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP,
	SendEmailAsHTML NUMBER(1) NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    TemplateId NUMBER NOT NULL,
	IsDefaultTemplate NUMBER(1) NOT NULL,
	IsSystemDefault NUMBER(1) NOT NULL,
	Description NVARCHAR2(255) NULL,
    ModifiedBy VARCHAR2(36) NOT NULL,
	TemplateLocalizationKey NVARCHAR2(255) NULL,
	CONSTRAINT PK_BOLDTC_CUSTOMEMAILTEMPLATE PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_TenantSettings (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    TenantInfoId VARCHAR2(36) NULL,
    Settings CLOB NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_TENANTSETTINGS PRIMARY KEY (Id)
);

CREATE TABLE BOLDTC_UserAttributes (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Name VARCHAR2(255) NOT NULL,
    Value VARCHAR2(4000) NOT NULL,
    Description VARCHAR2(1024),
    Encrypt NUMBER(1) NOT NULL,
    UserId VARCHAR2(36) NOT NULL,
    CreatedById CHAR(38),
    ModifiedById CHAR(38),
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_USERATTRIBUTES PRIMARY KEY (Id)
);

CREATE TABLE BoldTC_AICredentials (
    Id VARCHAR2(36) NOT NULL,
    AIModel NUMBER NOT NULL,
    AIConfiguration VARCHAR2(4000) NULL,
    CreatedById CHAR(38),
    ModifiedById CHAR(38),
    CreatedDate TIMESTAMP NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL,
    CONSTRAINT PK_BOLDTC_AICREDENTIALS PRIMARY KEY (Id)
);


INSERT INTO BOLDTC_TenantLogType (Name, IsActive) VALUES ('Registration', 1);
INSERT INTO BOLDTC_TenantLogType (Name, IsActive) VALUES ('StatusUpdated', 1);
INSERT INTO BOLDTC_TenantLogType (Name, IsActive) VALUES ('PaymentUpdated', 1);
INSERT INTO BOLDTC_TenantLogType (Name, IsActive) VALUES ('SubscriptionUpdated', 1);
INSERT INTO BOLDTC_TenantLogType (Name, IsActive) VALUES ('BillingAddressUpdated', 1);

INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('AccountActivationPending', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('PaymentPending', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('SubscriptionCreationInProgress', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('SubscriptionCreationFailed', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('DeploymentPending', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('DBDeploymentInProgress', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('DBDeploymentFailed', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('StorageDeploymentInProgress', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('StorageDeploymentFailed', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('ServerDeploymentInProgress', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('ServerDeploymentFailed', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('DeploymentFailed', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('Active', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('SubscriptionCancelled', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('MarkedForSuspension', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('Suspended', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('MarkedForDeletion', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('Expired', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('SubscriptionDeleted', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('DBDeleted', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('StorageDeleted', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('Deleted', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('Trial', 1);
INSERT INTO BOLDTC_TenantStatus (Name, IsActive) VALUES ('ActivePaymentRequired', 1);

INSERT INTO BOLDTC_ScheduleStatus (Name, IsActive) VALUES ('Success', 1);
INSERT INTO BOLDTC_ScheduleStatus (Name, IsActive) VALUES ('Failure', 1);

INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('Daily', 1);
INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('DailyWeekDay', 1);
INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('Weekly', 1);
INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('Monthly', 1);
INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('MonthlyDOW', 1);
INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('Yearly', 1);
INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('YearlyDOW', 1);
INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('Time', 1);
INSERT INTO BOLDTC_RecurrenceType (Name, IsActive) VALUES ('Hourly', 1);

INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('AccountActivationReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('PaymentDetailsUpdateReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('SuspendGraceReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('DeletionGraceReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('NewTenantListReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('SuspensionPendingTenantListReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('DeletionPendingTenantListReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('SuspendedTenantListReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('DeletedTenantListReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('SubscriptionCancelledTenantListReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('ServerAvailabilityCheckReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('ResourceDeletionGraceReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('ResourceDeletedReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('CreateBlobSnapshotReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('DeleteExpiredBlobSnapshotReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('MarkForSuspensionReminder', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('SubscriptionCancelled', 1);
INSERT INTO BOLDTC_ScheduleType (Name, IsActive) VALUES ('KnownCompanyExcessStorageUsageReminder', 1);

INSERT INTO BOLDTC_CouponLogType (Name, IsActive) VALUES ('Added', 1);
INSERT INTO BOLDTC_CouponLogType (Name, IsActive) VALUES ('Updated', 1);
INSERT INTO BOLDTC_CouponLogType (Name, IsActive) VALUES ('Used', 1);
INSERT INTO BOLDTC_CouponLogType (Name, IsActive) VALUES ('Suspended', 1);
INSERT INTO BOLDTC_CouponLogType (Name, IsActive) VALUES ('Deleted', 1);

INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('Local', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('AzureAD', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('ExternalDatabase', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('GSuite', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('WindowsAD', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('Syncfusion', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('OAuth2', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('OpenIDConnect', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('LinkedIn', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('Google', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('GitHub', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('Facebook', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('Twitter', 1);
INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('JWTSSO', 1);

INSERT INTO BOLDTC_TMGroup (Name, Description, Color, DirectoryTypeId, ModifiedDate, IsActive)
VALUES ('System Administrator', 'Has administrative rights for the dashboards', '#ff0000', 1, SYSDATE, 1);

INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('5 Users', 'NA', SYSDATE, 0, 0);
INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('25 Users', 'NA', SYSDATE, 0, 0);
INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('50 Users', 'NA', SYSDATE, 0, 0);
INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('75 Users', 'NA', SYSDATE, 0, 0);
INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('100 Users', 'NA', SYSDATE, 0, 0);
INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('KC Benefits', 'NA', SYSDATE, 1, 0);
INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('Bold Bi', 'jOS8fQeRafN+OmuhkdZzib0vs/mdtxFFcqEvSrU+PgxyYJpSQ0aFq3fJQH8lY9dBEyuxDuN6o0St2yX46CmVbqz8JwG8rjHiUlw2FdR8y8vkmeUSFtf82U3fUq+8nemokA4r0JMk/K8mSkbAE6/2E9KodobNGV+uOQSgl4cmcaT4zH8fdfwbS+AeUB0jUmOYJpmOxGYJnRDcolin9CW6g8wv7FSEcYpIPST26ifmxGSLG+W+hVYNY7oXV3Pk4iqBirlGftktvkvaG1ua0xAKacjq0zND/JLWj2fmouQqGhZ1M+dvKyLiTcvIVBWkCxRXdFEaf7pCuGWuxVlhSgfBvq+ZWTuevkoerL6Dv3xANqnMs7rpSRJSF62B4q7MNSa5M/uvdiQ9d/chGsENg1YxS3ZSk6/tRtbP5H4Pmog0rFmkvvImEyGFmYrBo5rq5vHm7vj3O8RlBXWi7oaoNxopp5aoTAfEILO1E0+UGf6rzWDiyYa3JzPtRALnVbWi8fW7vNAGp+sYtcflwCf/EUbz4GJC1bYzU5GnL0y9ijQ+MywNJ4pZWLtA4wDIhrYCF9eB1/yViU/4EtAOWNUeav23T3miiurnc1DMHeM9KRDg/c7+QGhNySPcuYCjYlOsW+XqXTzsxji0okUEUvTk5seJIdqELLR42jNya5s4NW21Mc9lE7iGzOMeJWyWAHqV8Wnj3Rmmmf2F+9yKL3Qlx7GEeAD2Jswo3+iMPm54VGpiMuHOAm/WM63bxl9w/1EpXpM1vRZux8WBoRjH9BGMKSw0lQ==', SYSDATE, 1, 1);
INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('Business 10', 'NA', SYSDATE, 0, 0);
INSERT INTO BOLDTC_SaaSPlan (Name, PlanSchema, ModifiedDate, IsInternal, IsActive)
VALUES ('Business 25', 'NA', SYSDATE, 0, 0);

INSERT INTO BOLDTC_TenantType (Type, IsActive) VALUES ('BoldBI', 1);
INSERT INTO BOLDTC_TenantType (Type, IsActive) VALUES ('BoldReports', 1);
INSERT INTO BOLDTC_TenantType (Type, IsActive) VALUES ('BoldBIOn-Premise', 1);
INSERT INTO BOLDTC_TenantType (Type, IsActive) VALUES ('BoldReportsOn-Premise', 1);

INSERT INTO BOLDTC_Addon (Name, StripePlanId, PlanSchema, ModifiedDate, IsActive) VALUES ('AdditionalDataStorage', 'additional_data_storage', '', SYSDATE, '1');
INSERT INTO BOLDTC_Addon (Name, StripePlanId, PlanSchema, ModifiedDate, IsActive) VALUES ('CustomDomain', 'custom_domain', '', SYSDATE, '1');

INSERT INTO BOLDTC_SqlServerEdition (Version, DatabaseLimit, Region, IsCurrent, IsActive) VALUES ('V12', 4000, 'East US', 1, 1);

INSERT INTO BOLDTC_SqlElasticPoolEdition (PoolEditionName, PoolDtu, PoolStorageinGB, DatabaseDtuMinInGB, DatabaseDtuMaxInGB, DatabaseLimit, IsCurrent, IsActive, Region)
VALUES ('Standard', 50, 50, 0, 50, 100, 1, 1, 'East US');

INSERT INTO BOLDTC_SqlServerType (SqlServerType, ModifiedDate, IsActive) VALUES ('TenantSqlServer', SYSDATE, 1);
INSERT INTO BOLDTC_SqlServerType (SqlServerType, ModifiedDate, IsActive) VALUES ('IntermediateSqlServer', SYSDATE, 1);

INSERT INTO BOLDTC_SqlServer (ServerName, UserName, Password, DatabaseLimit, SqlServerType, TenantType, IsAvailable, IsActive)
VALUES ('dev-boldbi-tenants', 'dashboard-admin', '', 3900, 1, 1, '1', '1');

INSERT INTO BOLDTC_SqlElasticPool (PoolName, SqlServerId, DatabaseLimit, SqlServerType, TenantType, IsAvailable, IsActive)
VALUES ('dev-boldbi-tenant-pool', 1, 95, 1, 1, '1', '1');

INSERT INTO BOLDTC_SqlServer (ServerName, UserName, Password, DatabaseLimit, SqlServerType, TenantType, IsAvailable, IsActive)
VALUES ('dev-boldbi-datastore', 'datastore-admin', '', 3900, 2, 1, '1', '1');

INSERT INTO BOLDTC_SqlElasticPool (PoolName, SqlServerId, DatabaseLimit, SqlServerType, TenantType, IsAvailable, IsActive)
VALUES ('dev-boldbi-data-pool', 2, 95, 2, 1, '1', '1');

INSERT INTO BOLDTC_AuthType (Name, ModifiedDate, IsActive) VALUES ('OAuth', SYSDATE, 1);
INSERT INTO BOLDTC_AuthType (Name, ModifiedDate, IsActive) VALUES ('OIDC', SYSDATE, 1);
INSERT INTO BOLDTC_AuthType (Name, ModifiedDate, IsActive) VALUES ('SAML', SYSDATE, 1);
INSERT INTO BOLDTC_AuthType (Name, ModifiedDate, IsActive) VALUES ('DefaultAuth', SYSDATE, 1);
INSERT INTO BOLDTC_AuthType (Name, ModifiedDate, IsActive) VALUES ('JWTSSO', SYSDATE, 1);
INSERT INTO BOLDTC_AuthType (Name, ModifiedDate, IsActive) VALUES ('WindowsAD', SYSDATE, 1);

INSERT INTO BOLDTC_AuthProvider (Name, AuthTypeId, ModifiedDate, IsActive) VALUES ('CustomOAuth', 1, SYSDATE, 1);
INSERT INTO BOLDTC_AuthProvider (Name, AuthTypeId, ModifiedDate, IsActive) VALUES ('CustomOIDC', 2, SYSDATE, 1);
INSERT INTO BOLDTC_AuthProvider (Name, AuthTypeId, ModifiedDate, IsActive) VALUES ('AzureAD', 3, SYSDATE, 1);
INSERT INTO BOLDTC_AuthProvider (Name, AuthTypeId, ModifiedDate, IsActive) VALUES ('JWTSSO', 5, SYSDATE, 1);
INSERT INTO BOLDTC_AuthProvider (Name, AuthTypeId, ModifiedDate, IsActive) VALUES ('WindowsAD', 6, SYSDATE, 1);

INSERT INTO BOLDTC_UserStatus (Status, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('NotActivated', 0, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_UserStatus (Status, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Activated', 1, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_UserStatus (Status, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Locked', 2, SYSDATE, SYSDATE, 1);

INSERT INTO BOLDTC_MfaType (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Authenticator', 1, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_MfaType (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Email', 2, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_MfaType (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('SMS', 3, SYSDATE, SYSDATE, 1);

INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Identity Provider Web', 1, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Identity Provider API', 2, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Tenant Management Web', 3, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Dashboard Server Web', 4, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Dashboard Server API', 5, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Dashboard Server Jobs', 6, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Report Server Web', 7, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Report Server API', 8, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Report Server Jobs', 9, SYSDATE, SYSDATE, 1);
INSERT INTO BOLDTC_Source (Type, Value, CreatedDate, ModifiedDate, IsActive) VALUES ('Admin Utility', 10, SYSDATE, SYSDATE, 1);

INSERT INTO BOLDTC_AuthType (Name, ModifiedDate, IsActive) VALUES ('AzureADB2C', SYSDATE, 1);
INSERT INTO BOLDTC_AuthProvider (Name, AuthTypeId, ModifiedDate, IsActive) VALUES ('AzureADB2C', 7, SYSDATE, 1);

INSERT INTO BOLDTC_DirectoryType (DirectoryName, IsActive) VALUES ('AzureADB2C', 1);

ALTER TABLE BOLDTC_CouponLog ADD CONSTRAINT BOLDTC_CouponLog_fk0 FOREIGN KEY (CouponLogTypeId) REFERENCES BOLDTC_CouponLogType(Id);
ALTER TABLE BOLDTC_CouponLog ENABLE CONSTRAINT BOLDTC_CouponLog_fk0;

ALTER TABLE BOLDTC_CouponLog ADD CONSTRAINT BOLDTC_CouponLog_fk1 FOREIGN KEY (PaymentLogId) REFERENCES BOLDTC_TenantPaymentLog(id);
ALTER TABLE BOLDTC_CouponLog ENABLE CONSTRAINT BOLDTC_CouponLog_fk1;

ALTER TABLE BOLDTC_TenantPaymentSubscription ADD CONSTRAINT BOLDTC_TenantPaymentSubscription_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_TenantPaymentSubscription ENABLE CONSTRAINT BOLDTC_TenantPaymentSubscription_fk0;

ALTER TABLE BOLDTC_TenantInvoiceDetails ADD CONSTRAINT BOLDTC_TenantInvoiceDetails_fk0 FOREIGN KEY (SubscriptionId) REFERENCES BOLDTC_TenantPaymentSubscription(Id);

ALTER TABLE BOLDTC_TenantPaymentLog ADD CONSTRAINT BOLDTC_TenantPaymentLog_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_TenantPaymentLog ENABLE CONSTRAINT BOLDTC_TenantPaymentLog_fk0;

ALTER TABLE BOLDTC_TenantPaymentLog ADD CONSTRAINT BOLDTC_TenantPaymentLog_fk1 FOREIGN KEY (SubscriptionId) REFERENCES BOLDTC_TenantPaymentSubscription(Id);
ALTER TABLE BOLDTC_TenantPaymentLog ENABLE CONSTRAINT BOLDTC_TenantPaymentLog_fk1;

ALTER TABLE BOLDTC_SqlElasticPool ADD CONSTRAINT BOLDTC_SqlElasticPool_fk0 FOREIGN KEY (SqlServerId) REFERENCES BOLDTC_SqlServer(Id);
ALTER TABLE BOLDTC_SqlElasticPool ENABLE CONSTRAINT BOLDTC_SqlElasticPool_fk0;

ALTER TABLE BOLDTC_Tenant ADD CONSTRAINT BOLDTC_Tenant_fk0 FOREIGN KEY (UserId) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_Tenant ENABLE CONSTRAINT BOLDTC_Tenant_fk0;

ALTER TABLE BOLDTC_TenantLog ADD CONSTRAINT BOLDTC_TenantLog_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_TenantLog ENABLE CONSTRAINT BOLDTC_TenantLog_fk0;

ALTER TABLE BOLDTC_TenantLog ADD CONSTRAINT BOLDTC_TenantLog_fk1 FOREIGN KEY (TenantLogType) REFERENCES BOLDTC_TenantLogType(Id);
ALTER TABLE BOLDTC_TenantLog ENABLE CONSTRAINT BOLDTC_TenantLog_fk1;

ALTER TABLE BOLDTC_TenantLog ADD CONSTRAINT BOLDTC_TenantLog_fk2 FOREIGN KEY (ToStatus) REFERENCES BOLDTC_TenantStatus(Id);
ALTER TABLE BOLDTC_TenantLog ENABLE CONSTRAINT BOLDTC_TenantLog_fk2;

ALTER TABLE BOLDTC_Coupon ADD CONSTRAINT BOLDTC_Coupon_fk0 FOREIGN KEY (CreatedById) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_Coupon ENABLE CONSTRAINT BOLDTC_Coupon_fk0;

ALTER TABLE BOLDTC_Coupon ADD CONSTRAINT BOLDTC_Coupon_fk1 FOREIGN KEY (ModifiedById) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_Coupon ENABLE CONSTRAINT BOLDTC_Coupon_fk1;

ALTER TABLE BOLDTC_UserPreference ADD CONSTRAINT BOLDTC_UserPreference_fk0 FOREIGN KEY (UserId) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_UserPreference ENABLE CONSTRAINT BOLDTC_UserPreference_fk0;

ALTER TABLE BOLDTC_User ADD CONSTRAINT BOLDTC_User_fk0 FOREIGN KEY (DirectoryTypeId) REFERENCES BOLDTC_DirectoryType(Id);
ALTER TABLE BOLDTC_User ENABLE CONSTRAINT BOLDTC_User_fk0;

ALTER TABLE BOLDTC_UserLogin ADD CONSTRAINT BOLDTC_UserLogin_fk0 FOREIGN KEY (UserId) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_UserLogin ENABLE CONSTRAINT BOLDTC_UserLogin_fk0;

ALTER TABLE BOLDTC_UserLogin ADD CONSTRAINT BOLDTC_UserLogin_fk1 FOREIGN KEY (DirectoryTypeId) REFERENCES BOLDTC_DirectoryType(Id);
ALTER TABLE BOLDTC_UserLogin ENABLE CONSTRAINT BOLDTC_UserLogin_fk1;

ALTER TABLE BOLDTC_TMUserGroup ADD CONSTRAINT BOLDTC_TMUserGroup_fk0 FOREIGN KEY (GroupId) REFERENCES BOLDTC_TMGroup(Id);
ALTER TABLE BOLDTC_TMUserGroup ENABLE CONSTRAINT BOLDTC_TMUserGroup_fk0;

ALTER TABLE BOLDTC_TMUserGroup ADD CONSTRAINT BOLDTC_TMUserGroup_fk1 FOREIGN KEY (UserId) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_TMUserGroup ENABLE CONSTRAINT BOLDTC_TMUserGroup_fk1;

ALTER TABLE BOLDTC_TMGroup ADD CONSTRAINT BOLDTC_TMGroup_fk0 FOREIGN KEY (DirectoryTypeId) REFERENCES BOLDTC_DirectoryType(Id);
ALTER TABLE BOLDTC_TMGroup ENABLE CONSTRAINT BOLDTC_TMGroup_fk0;

ALTER TABLE BOLDTC_TenantUser ADD CONSTRAINT BOLDTC_TenantUser_fk0 FOREIGN KEY (UserId) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_TenantUser ENABLE CONSTRAINT BOLDTC_TenantUser_fk0;

ALTER TABLE BOLDTC_TenantUser ADD CONSTRAINT BOLDTC_TenantUser_fk1 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_TenantUser ENABLE CONSTRAINT BOLDTC_TenantUser_fk1;

ALTER TABLE BOLDTC_Schedule ADD CONSTRAINT BOLDTC_Schedule_fk0 FOREIGN KEY (RecurrenceTypeId) REFERENCES BOLDTC_RecurrenceType(Id);
ALTER TABLE BOLDTC_Schedule ENABLE CONSTRAINT BOLDTC_Schedule_fk0;

ALTER TABLE BOLDTC_Schedule ADD CONSTRAINT BOLDTC_Schedule_fk1 FOREIGN KEY (ScheduleTypeId) REFERENCES BOLDTC_ScheduleType(id);
ALTER TABLE BOLDTC_Schedule ENABLE CONSTRAINT BOLDTC_Schedule_fk1;

ALTER TABLE BOLDTC_ScheduleLog ADD CONSTRAINT BOLDTC_ScheduleLog_fk0 FOREIGN KEY (ScheduleId) REFERENCES BOLDTC_Schedule(id);
ALTER TABLE BOLDTC_ScheduleLog ENABLE CONSTRAINT BOLDTC_ScheduleLog_fk0;

ALTER TABLE BOLDTC_ScheduleLog ADD CONSTRAINT BOLDTC_ScheduleLog_fk1 FOREIGN KEY (ScheduleStatusId) REFERENCES BOLDTC_ScheduleStatus(Id);
ALTER TABLE BOLDTC_ScheduleLog ENABLE CONSTRAINT BOLDTC_ScheduleLog_fk1;

ALTER TABLE BOLDTC_TenantInfo ADD CONSTRAINT BOLDTC_TenantInfo_fk0 FOREIGN KEY (TenantId) REFERENCES BOLDTC_Tenant(Id);
ALTER TABLE BOLDTC_TenantInfo ENABLE CONSTRAINT BOLDTC_TenantInfo_fk0;

ALTER TABLE BOLDTC_TenantInfo ADD CONSTRAINT BOLDTC_TenantInfo_fk1 FOREIGN KEY (TenantTypeId) REFERENCES BOLDTC_TenantType(Id);
ALTER TABLE BOLDTC_TenantInfo ENABLE CONSTRAINT BOLDTC_TenantInfo_fk1;

ALTER TABLE BOLDTC_TenantInfo ADD CONSTRAINT BOLDTC_TenantInfo_fk2 FOREIGN KEY (SaaSPlanId) REFERENCES BOLDTC_SaaSPlan(Id);
ALTER TABLE BOLDTC_TenantInfo ENABLE CONSTRAINT BOLDTC_TenantInfo_fk2;

ALTER TABLE BOLDTC_TenantInfo ADD CONSTRAINT BOLDTC_TenantInfo_fk3 FOREIGN KEY (TenantSQLServerId) REFERENCES BOLDTC_SqlServer(Id);
ALTER TABLE BOLDTC_TenantInfo ENABLE CONSTRAINT BOLDTC_TenantInfo_fk3;

ALTER TABLE BOLDTC_TenantInfo ADD CONSTRAINT BOLDTC_TenantInfo_fk4 FOREIGN KEY (ElasticPoolId) REFERENCES BOLDTC_SqlElasticPool(Id);
ALTER TABLE BOLDTC_TenantInfo ENABLE CONSTRAINT BOLDTC_TenantInfo_fk4;

ALTER TABLE BOLDTC_TenantInfo ADD CONSTRAINT BOLDTC_TenantInfo_fk5 FOREIGN KEY (TenantStatus) REFERENCES BOLDTC_TenantStatus(Id);
ALTER TABLE BOLDTC_TenantInfo ENABLE CONSTRAINT BOLDTC_TenantInfo_fk5;

ALTER TABLE BOLDTC_UserBillingAddress ADD CONSTRAINT BOLDTC_UserBillingAddress_fk1 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_UserBillingAddress ENABLE CONSTRAINT BOLDTC_UserBillingAddress_fk1;

ALTER TABLE BOLDTC_TenantAddon ADD CONSTRAINT BOLDTC_TenantAddon_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_TenantAddon ENABLE CONSTRAINT BOLDTC_TenantAddon_fk0;

ALTER TABLE BOLDTC_TenantAddon ADD CONSTRAINT BOLDTC_TenantAddon_fk1 FOREIGN KEY (AddonId) REFERENCES BOLDTC_Addon(Id);
ALTER TABLE BOLDTC_TenantAddon ENABLE CONSTRAINT BOLDTC_TenantAddon_fk1;

ALTER TABLE BOLDTC_CustomPlan ADD CONSTRAINT BOLDTC_CustomPlan_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_CustomPlan ENABLE CONSTRAINT BOLDTC_CustomPlan_fk0;

ALTER TABLE BOLDTC_ExternalIdP ADD CONSTRAINT BOLDTC_ExternalIdP_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_ExternalIdP ENABLE CONSTRAINT BOLDTC_ExternalIdP_fk0;

ALTER TABLE BOLDTC_ExternalIdP ADD CONSTRAINT BOLDTC_ExternalIdP_fk1 FOREIGN KEY (DirectoryTypeId) REFERENCES BOLDTC_DirectoryType(Id);
ALTER TABLE BOLDTC_ExternalIdP ENABLE CONSTRAINT BOLDTC_ExternalIdP_fk1;

ALTER TABLE BOLDTC_ExternalIdP ADD CONSTRAINT BOLDTC_ExternalIdP_fk2 FOREIGN KEY (CredentialTypeId) REFERENCES BOLDTC_IdPCredentialType(Id);
ALTER TABLE BOLDTC_ExternalIdP ENABLE CONSTRAINT BOLDTC_ExternalIdP_fk2;

ALTER TABLE BOLDTC_SqlServer ADD CONSTRAINT BOLDTC_SqlServer_fk0 FOREIGN KEY (SqlServerType) REFERENCES BOLDTC_SqlServerType(Id);
ALTER TABLE BOLDTC_SqlServer ENABLE CONSTRAINT BOLDTC_SqlServer_fk0;

ALTER TABLE BOLDTC_SqlElasticPool ADD CONSTRAINT BOLDTC_SqlElasticPool_fk1 FOREIGN KEY (SqlServerType) REFERENCES BOLDTC_SqlServerType(Id);
ALTER TABLE BOLDTC_SqlElasticPool ENABLE CONSTRAINT BOLDTC_SqlElasticPool_fk1;

ALTER TABLE BOLDTC_SqlElasticPool ADD CONSTRAINT BOLDTC_SqlElasticPool_fk2 FOREIGN KEY (TenantType) REFERENCES BOLDTC_TenantType(Id);
ALTER TABLE BOLDTC_SqlElasticPool ENABLE CONSTRAINT BOLDTC_SqlElasticPool_fk2;

ALTER TABLE BOLDTC_SqlServer ADD CONSTRAINT BOLDTC_SqlServer_fk1 FOREIGN KEY (TenantType) REFERENCES BOLDTC_TenantType(Id);
ALTER TABLE BOLDTC_SqlServer ENABLE CONSTRAINT BOLDTC_SqlServer_fk1;

ALTER TABLE BOLDTC_TenantInfo ADD CONSTRAINT BOLDTC_ImDbElasticPoolId FOREIGN KEY (ImDbElasticPoolId) REFERENCES BOLDTC_SqlElasticPool(Id);
ALTER TABLE BOLDTC_TenantInfo ENABLE CONSTRAINT BOLDTC_ImDbElasticPoolId;

ALTER TABLE BOLDTC_TenantInfo ADD CONSTRAINT BOLDTC_IDbSqlServerId FOREIGN KEY (ImDbSqlServerId) REFERENCES BOLDTC_SqlServer(Id);
ALTER TABLE BOLDTC_TenantInfo ENABLE CONSTRAINT BOLDTC_IDbSqlServerId;

ALTER TABLE BOLDTC_RegistrationFormVersion ADD CONSTRAINT BOLDTC_RegistrationFormVersion_fk0 FOREIGN KEY (FormTypeId) REFERENCES BOLDTC_FormType(Id);
ALTER TABLE BOLDTC_RegistrationFormVersion ENABLE CONSTRAINT BOLDTC_RegistrationFormVersion_fk0;

ALTER TABLE BOLDTC_PrivacyAcceptance ADD CONSTRAINT BOLDTC_PrivacyAcceptance_fk0 FOREIGN KEY (PrivacyPolicyVersion) REFERENCES BOLDTC_PrivacyPolicyVersion(Id);
ALTER TABLE BOLDTC_PrivacyAcceptance ENABLE CONSTRAINT BOLDTC_PrivacyAcceptance_fk0;

ALTER TABLE BOLDTC_PrivacyAcceptance ADD CONSTRAINT BOLDTC_PrivacyAcceptance_fk1 FOREIGN KEY (TermsOfUseVersion) REFERENCES BOLDTC_TermsOfUseVersion(Id);
ALTER TABLE BOLDTC_PrivacyAcceptance ENABLE CONSTRAINT BOLDTC_PrivacyAcceptance_fk1;

ALTER TABLE BOLDTC_PrivacyAcceptance ADD CONSTRAINT BOLDTC_PrivacyAcceptance_fk2 FOREIGN KEY (RegistrationFormVersion) REFERENCES BOLDTC_RegistrationFormVersion(Id);
ALTER TABLE BOLDTC_PrivacyAcceptance ENABLE CONSTRAINT BOLDTC_PrivacyAcceptance_fk2;

ALTER TABLE BOLDTC_FeedBack ADD CONSTRAINT BOLDTC_FeedBack_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_FeedBack ENABLE CONSTRAINT BOLDTC_FeedBack_fk0;

ALTER TABLE BOLDTC_Support ADD CONSTRAINT BOLDTC_Support_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_Support ENABLE CONSTRAINT BOLDTC_Support_fk0;

ALTER TABLE BOLDTC_TenantActivity ADD CONSTRAINT BOLDTC_TenantActivity_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_TenantActivity ENABLE CONSTRAINT BOLDTC_TenantActivity_fk0;

ALTER TABLE BOLDTC_PreviewFeatures ADD CONSTRAINT BOLDTC_PreviewFeatures_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_PreviewFeatures ENABLE CONSTRAINT BOLDTC_PreviewFeatures_fk0;

ALTER TABLE BOLDTC_KcTenants ADD CONSTRAINT BOLDTC_KcTenant_FK0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_KcTenants ENABLE CONSTRAINT BOLDTC_KcTenant_FK0;

ALTER TABLE BOLDTC_SSLMapping ADD CONSTRAINT BOLDTC_SSLMapping_fk1 FOREIGN KEY (TenantId) REFERENCES BOLDTC_Tenant(Id);
ALTER TABLE BOLDTC_SSLMapping ENABLE CONSTRAINT BOLDTC_SSLMapping_fk1;

ALTER TABLE BOLDTC_SSLMapping ADD CONSTRAINT BOLDTC_SSLMapping_fk2 FOREIGN KEY (CertificateId) REFERENCES BOLDTC_SSLCertificate(Id);
ALTER TABLE BOLDTC_SSLMapping ENABLE CONSTRAINT BOLDTC_SSLMapping_fk2;

ALTER TABLE BOLDTC_AuthProvider ADD CONSTRAINT BOLDTC_AuthProvider_fk0 FOREIGN KEY (AuthTypeId) REFERENCES BOLDTC_AuthType(Id);
ALTER TABLE BOLDTC_AuthProvider ENABLE CONSTRAINT BOLDTC_AuthProvider_fk0;

ALTER TABLE BOLDTC_GlobalAuthControl ADD CONSTRAINT BOLDTC_GlobalAuthControl_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_GlobalAuthControl ENABLE CONSTRAINT BOLDTC_GlobalAuthControl_fk0;

ALTER TABLE BOLDTC_GlobalAuthControl ADD CONSTRAINT BOLDTC_GlobalAuthControl_fk1 FOREIGN KEY (AuthTypeId) REFERENCES BOLDTC_AuthType(Id);
ALTER TABLE BOLDTC_GlobalAuthControl ENABLE CONSTRAINT BOLDTC_GlobalAuthControl_fk1;

ALTER TABLE BOLDTC_GlobalAuthControl ADD CONSTRAINT BOLDTC_GlobalAuthControl_fk2 FOREIGN KEY (CreatedBy) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_GlobalAuthControl ENABLE CONSTRAINT BOLDTC_GlobalAuthControl_fk2;

ALTER TABLE BOLDTC_GlobalAuthControl ADD CONSTRAINT BOLDTC_GlobalAuthControl_fk3 FOREIGN KEY (ModifiedBy) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_GlobalAuthControl ENABLE CONSTRAINT BOLDTC_GlobalAuthControl_fk3;

ALTER TABLE BOLDTC_AuthSettings ADD CONSTRAINT BOLDTC_AuthSettings_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
ALTER TABLE BOLDTC_AuthSettings ENABLE CONSTRAINT BOLDTC_AuthSettings_fk0;

ALTER TABLE BOLDTC_AuthSettings ADD CONSTRAINT BOLDTC_AuthSettings_fk1 FOREIGN KEY (AuthProviderId) REFERENCES BOLDTC_AuthProvider(Id);
ALTER TABLE BOLDTC_AuthSettings ENABLE CONSTRAINT BOLDTC_AuthSettings_fk1;

ALTER TABLE BOLDTC_AuthSettings ADD CONSTRAINT BOLDTC_AuthSettings_fk2 FOREIGN KEY (CreatedBy) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_AuthSettings ENABLE CONSTRAINT BOLDTC_AuthSettings_fk2;

ALTER TABLE BOLDTC_AuthSettings ADD CONSTRAINT BOLDTC_AuthSettings_fk3 FOREIGN KEY (ModifiedBy) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_AuthSettings ENABLE CONSTRAINT BOLDTC_AuthSettings_fk3;

ALTER TABLE BOLDTC_UserLog ADD CONSTRAINT BOLDTC_UserLog_fk1 FOREIGN KEY (UserId) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_UserLog ENABLE CONSTRAINT BOLDTC_UserLog_fk1;

ALTER TABLE BOLDTC_UserLog ADD CONSTRAINT BOLDTC_UserLog_fk2 FOREIGN KEY (RequestedById) REFERENCES BOLDTC_User(Id);
ALTER TABLE BOLDTC_UserLog ENABLE CONSTRAINT BOLDTC_UserLog_fk2;

ALTER TABLE BOLDTC_AzureBlob ADD CONSTRAINT BOLDTC_AzureBlob_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);

ALTER TABLE BOLDTC_User ADD CONSTRAINT BOLDTC_User_fk1 FOREIGN KEY (Status) REFERENCES BOLDTC_UserStatus(Value);
ALTER TABLE BOLDTC_User ENABLE CONSTRAINT BOLDTC_User_fk1;

ALTER TABLE BOLDTC_User ADD CONSTRAINT BOLDTC_User_fk2 FOREIGN KEY (MfaType) REFERENCES BOLDTC_MfaType(Value);
ALTER TABLE BOLDTC_User ENABLE CONSTRAINT BOLDTC_User_fk2;

ALTER TABLE BOLDTC_UserLog ADD CONSTRAINT BOLDTC_UserLog_fk3 FOREIGN KEY (Source) REFERENCES BOLDTC_Source(Value);
ALTER TABLE BOLDTC_UserLog ENABLE CONSTRAINT BOLDTC_UserLog_fk3;

ALTER TABLE BOLDTC_EmailActivityLog ADD CONSTRAINT BOLDTC_EmailActivityLog_fk0 FOREIGN KEY (UserId) REFERENCES BOLDTC_User(Id);

ALTER TABLE BOLDTC_UserAttributes ADD CONSTRAINT FK_BOLDTC_UserAttributes_User FOREIGN KEY (UserId) REFERENCES BOLDTC_User(Id);

ALTER TABLE BOLDTC_TenantSettings ADD CONSTRAINT BOLDTC_TenantSettings_fk0 FOREIGN KEY (TenantInfoId) REFERENCES BOLDTC_TenantInfo(Id);
