CREATE TABLE BOLDTC_AICredentials (
  Id VARCHAR2(36) NOT NULL,
  AIModel NUMBER NOT NULL,
  AIConfiguration VARCHAR2(4000) NULL,
  CreatedById CHAR(38),
  ModifiedById CHAR(38),
  CreatedDate TIMESTAMP NOT NULL,
  ModifiedDate TIMESTAMP NOT NULL,
  IsActive NUMBER(1) NOT NULL,
  CONSTRAINT PK_BOLDTC_AICREDENTIALS PRIMARY KEY (Id)
);