//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.Dashboard.Connection.InternalCache.Model.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.Dashboard.Connection.InternalCache.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BETWEEN.
        /// </summary>
        internal static string Between
        {
            get
            {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CONTAINS.
        /// </summary>
        internal static string Contains
        {
            get
            {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to date_part(&apos;month&apos;, CURRENT_DATE).
        /// </summary>
        internal static string CurrentMonth
        {
            get
            {
                return ResourceManager.GetString("CurrentMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to date_part(&apos;year&apos;, CURRENT_DATE).
        /// </summary>
        internal static string CurrentYear
        {
            get
            {
                return ResourceManager.GetString("CurrentYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YYYY-MM-DD HH24:MI:SS.
        /// </summary>
        internal static string DateTimeStringFormat
        {
            get
            {
                return ResourceManager.GetString("DateTimeStringFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mm/dd/yyyy hh:MI:SS AM.
        /// </summary>
        internal static string DateTimeStringFormat2
        {
            get
            {
                return ResourceManager.GetString("DateTimeStringFormat2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ENDS WITH.
        /// </summary>
        internal static string EndsWith
        {
            get
            {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to parse relative date expression. Bad arguments.
        /// </summary>
        internal static string Err_FailToParseRelativeDateExpression
        {
            get
            {
                return ResourceManager.GetString("Err_FailToParseRelativeDateExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        internal static string In
        {
            get
            {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Null
        {
            get
            {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        internal static string InternalCacheAnd
        {
            get
            {
                return ResourceManager.GetString("InternalCacheAnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AS.
        /// </summary>
        internal static string InternalCacheAs
        {
            get
            {
                return ResourceManager.GetString("InternalCacheAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ASC.
        /// </summary>
        internal static string InternalCacheAsc
        {
            get
            {
                return ResourceManager.GetString("InternalCacheAsc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVG.
        /// </summary>
        internal static string InternalCacheAvg
        {
            get
            {
                return ResourceManager.GetString("InternalCacheAvg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVGD.
        /// </summary>
        internal static string InternalCacheAvgD
        {
            get
            {
                return ResourceManager.GetString("InternalCacheAvgD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BETWEEN {0} AND {1}.
        /// </summary>
        internal static string InternalCacheBetweenFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheBetweenFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NOT BETWEEN {0} AND {1}.
        /// </summary>
        internal static string InternalCacheNotBetweenFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNotBetweenFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BIGINT.
        /// </summary>
        internal static string InternalCacheBigInt
        {
            get
            {
                return ResourceManager.GetString("InternalCacheBigInt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BINARY.
        /// </summary>
        internal static string InternalCacheBinary
        {
            get
            {
                return ResourceManager.GetString("InternalCacheBinary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BIT.
        /// </summary>
        internal static string InternalCacheBit
        {
            get
            {
                return ResourceManager.GetString("InternalCacheBit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} THEN {1} ELSE {2} END.
        /// </summary>
        internal static string InternalCacheCaseWhenElseFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheCaseWhenElseFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CAST( {0} AS {1} ).
        /// </summary>
        internal static string InternalCacheCastFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheCastFormat", resourceCulture);
            }
        }

        /// <summary>
		///   Looks up a localized string similar to (DATE_PART(&apos;YEAR&apos;,{0}::timestamp)*100 + DATE_PART(&apos;MONTH&apos;,{0}::timestamp))*100 + DATE_PART(&apos;d&apos;,{0}::timestamp).
        /// </summary>
        internal static string InternalCacheDateCastFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDateCastFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CHAR.
        /// </summary>
        internal static string InternalCacheChar
        {
            get
            {
                return ResourceManager.GetString("InternalCacheChar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string InternalCacheComparisonFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheComparisonFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} THEN {1} ELSE NULL END.
        /// </summary>
        internal static string InternalCacheConditionalConversionFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheConditionalConversionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CASE WHEN {0} like {1} THEN 1 ELSE 0 END.
        /// </summary>
        internal static string InternalCacheContainsFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheContainsFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        internal static string InternalCacheCount
        {
            get
            {
                return ResourceManager.GetString("InternalCacheCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COUNTD.
        /// </summary>
        internal static string InternalCacheCountD
        {
            get
            {
                return ResourceManager.GetString("InternalCacheCountD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COUNT(*).
        /// </summary>
        internal static string InternalCacheCountAll
        {
            get
            {
                return ResourceManager.GetString("InternalCacheCountAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE {0} ( {1} );.
        /// </summary>
        internal static string InternalCacheCreateTableFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheCreateTableFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string InternalCacheDate
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DATEADD.
        /// </summary>
        internal static string InternalCacheDateAdd
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDateAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DATEDIFF.
        /// </summary>
        internal static string InternalCacheDateDiff
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDateDiff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DATE_PART.
        /// </summary>
        internal static string InternalCacheDatePart
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDatePart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DATETIME.
        /// </summary>
        internal static string InternalCacheDatetime
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDatetime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DATETIME2.
        /// </summary>
        internal static string InternalCacheDateTime2
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDateTime2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DATETIMEOFFSET.
        /// </summary>
        internal static string InternalCacheDateTimeOffset
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDateTimeOffset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DAY.
        /// </summary>
        internal static string InternalCacheDay
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DAYOFYEAR.
        /// </summary>
        internal static string InternalCacheDayOfYear
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDayOfYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DECIMAL.
        /// </summary>
        internal static string InternalCacheDecimal
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDecimal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DECLARE.
        /// </summary>
        internal static string InternalCacheDeclare
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDeclare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}( {3} ).
        /// </summary>
        internal static string InternalCacheDeclareTableFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDeclareTableFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DESC.
        /// </summary>
        internal static string InternalCacheDesc
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        internal static string InternalCacheDifferent
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDifferent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DISTINCT.
        /// </summary>
        internal static string InternalCacheDistinct
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDistinct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE {0}.
        /// </summary>
        internal static string InternalCacheDropTableFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDropTableFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string InternalCacheEquals
        {
            get
            {
                return ResourceManager.GetString("InternalCacheEquals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EXEC.
        /// </summary>
        internal static string InternalCacheExec
        {
            get
            {
                return ResourceManager.GetString("InternalCacheExec", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FLOAT.
        /// </summary>
        internal static string InternalCacheFloat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheFloat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FORMAT( {0} ).
        /// </summary>
        internal static string InternalCacheFormatFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheFormatFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        internal static string InternalCacheFrom
        {
            get
            {
                return ResourceManager.GetString("InternalCacheFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FULL.
        /// </summary>
        internal static string InternalCacheFull
        {
            get
            {
                return ResourceManager.GetString("InternalCacheFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CROSS.
        /// </summary>
        internal static string InternalCacheCross
        {
            get
            {
                return ResourceManager.GetString("InternalCacheCross", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}( {1} ).
        /// </summary>
        internal static string InternalCacheFunctionFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheFunctionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GEOGRAPHY.
        /// </summary>
        internal static string InternalCacheGeography
        {
            get
            {
                return ResourceManager.GetString("InternalCacheGeography", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GEOMETRY.
        /// </summary>
        internal static string InternalCacheGeometry
        {
            get
            {
                return ResourceManager.GetString("InternalCacheGeometry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string InternalCacheGreaterOrEquals
        {
            get
            {
                return ResourceManager.GetString("InternalCacheGreaterOrEquals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string InternalCacheGreaterThan
        {
            get
            {
                return ResourceManager.GetString("InternalCacheGreaterThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GROUP BY.
        /// </summary>
        internal static string InternalCacheGroupBy
        {
            get
            {
                return ResourceManager.GetString("InternalCacheGroupBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HAVING.
        /// </summary>
        internal static string InternalCacheHaving
        {
            get
            {
                return ResourceManager.GetString("InternalCacheHaving", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HIERARCHYID.
        /// </summary>
        internal static string InternalCacheHierarchyId
        {
            get
            {
                return ResourceManager.GetString("InternalCacheHierarchyId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HOUR.
        /// </summary>
        internal static string InternalCacheHour
        {
            get
            {
                return ResourceManager.GetString("InternalCacheHour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IMAGE.
        /// </summary>
        internal static string InternalCacheImage
        {
            get
            {
                return ResourceManager.GetString("InternalCacheImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IN( {0} ).
        /// </summary>
        internal static string InternalCacheInFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INNER.
        /// </summary>
        internal static string InternalCacheInner
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INNER JOIN.
        /// </summary>
        internal static string InternalCacheInnerJoin
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInnerJoin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        internal static string InternalCacheInsert
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4}.
        /// </summary>
        internal static string InternalCacheInsertExecFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInsertExecFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0} VALUES ( {1} ).
        /// </summary>
        internal static string InternalCacheInsertIntoFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInsertIntoFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT * INTO {0} FROM ( {1} ) AS QUERY.
        /// </summary>
        internal static string InternalCacheInsertIntoFromQueryFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInsertIntoFromQueryFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        internal static string InternalCacheInt
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INT32.
        /// </summary>
        internal static string InternalCacheInt32
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInt32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INT64.
        /// </summary>
        internal static string InternalCacheInt64
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInt64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ISDATE( {0} ) = 1.
        /// </summary>
        internal static string InternalCacheIsDateFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheIsDateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IS NOT NULL.
        /// </summary>
        internal static string InternalCacheIsNotNull
        {
            get
            {
                return ResourceManager.GetString("InternalCacheIsNotNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IS NULL.
        /// </summary>
        internal static string InternalCacheIsNull
        {
            get
            {
                return ResourceManager.GetString("InternalCacheIsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ISNULL.
        /// </summary>
        internal static string InternalCacheIsNullFunction
        {
            get
            {
                return ResourceManager.GetString("InternalCacheIsNullFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ISNUMERIC( {0} ) = 1.
        /// </summary>
        internal static string InternalCacheIsNumberFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheIsNumberFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JOIN.
        /// </summary>
        internal static string InternalCacheJoin
        {
            get
            {
                return ResourceManager.GetString("InternalCacheJoin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LEFT.
        /// </summary>
        internal static string InternalCacheLeft
        {
            get
            {
                return ResourceManager.GetString("InternalCacheLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LEFT JOIN.
        /// </summary>
        internal static string InternalCacheLeftJoin 
        {
            get 
            {
                return ResourceManager.GetString("InternalCacheLeftJoin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string InternalCacheLessOrEquals
        {
            get
            {
                return ResourceManager.GetString("InternalCacheLessOrEquals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string InternalCacheLessThan
        {
            get
            {
                return ResourceManager.GetString("InternalCacheLessThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LIKE.
        /// </summary>
        internal static string InternalCacheLike
        {
            get
            {
                return ResourceManager.GetString("InternalCacheLike", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (UPPER{0}) LIKE (UPPER{1}).
        /// </summary>
        internal static string InternalCacheLikeFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheLikeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (UPPER{0}) NOT LIKE (UPPER{1}).
        /// </summary>
        internal static string InternalCacheNotLikeFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNotLikeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        internal static string InternalCacheMax
        {
            get
            {
                return ResourceManager.GetString("InternalCacheMax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        internal static string InternalCacheMin
        {
            get
            {
                return ResourceManager.GetString("InternalCacheMin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MINUTE.
        /// </summary>
        internal static string InternalCacheMinute
        {
            get
            {
                return ResourceManager.GetString("InternalCacheMinute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MONEY.
        /// </summary>
        internal static string InternalCacheMoney
        {
            get
            {
                return ResourceManager.GetString("InternalCacheMoney", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MONTH.
        /// </summary>
        internal static string InternalCacheMonth
        {
            get
            {
                return ResourceManager.GetString("InternalCacheMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NCHAR.
        /// </summary>
        internal static string InternalCacheNChar
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNChar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        internal static string InternalCacheNot
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GETDATE().
        /// </summary>
        internal static string InternalCacheNow
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTEXT.
        /// </summary>
        internal static string InternalCacheNText
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string InternalCacheNull
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NUMERIC.
        /// </summary>
        internal static string InternalCacheNumeric
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNumeric", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NVARCHAR.
        /// </summary>
        internal static string InternalCacheNVarchar
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNVarchar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string InternalCacheOn
        {
            get
            {
                return ResourceManager.GetString("InternalCacheOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string InternalCacheOr
        {
            get
            {
                return ResourceManager.GetString("InternalCacheOr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string InternalCacheOrNot
        {
            get
            {
                return ResourceManager.GetString("InternalCacheOrNot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string InternalCacheAndNot
        {
            get
            {
                return ResourceManager.GetString("InternalCacheAndNot", resourceCulture);
            }
        }

        internal static string InternalCacheAndGroup
        {
            get
            {
                return ResourceManager.GetString("InternalCacheAndGroup", resourceCulture);
            }
        }
        internal static string InternalCacheOrGroup
        {
            get
            {
                return ResourceManager.GetString("InternalCacheOrGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        internal static string InternalCacheIs
        {
            get
            {
                return ResourceManager.GetString("InternalCacheIs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ORDER BY.
        /// </summary>
        internal static string InternalCacheOrderBy
        {
            get
            {
                return ResourceManager.GetString("InternalCacheOrderBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OUTER.
        /// </summary>
        internal static string InternalCacheOuter
        {
            get
            {
                return ResourceManager.GetString("InternalCacheOuter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}().
        /// </summary>
        internal static string InternalCacheParameterLessFunctionFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheParameterLessFunctionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to QUARTER.
        /// </summary>
        internal static string InternalCacheQuarter
        {
            get
            {
                return ResourceManager.GetString("InternalCacheQuarter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to REAL.
        /// </summary>
        internal static string InternalCacheReal
        {
            get
            {
                return ResourceManager.GetString("InternalCacheReal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE {0};.
        /// </summary>
        internal static string InternalCacheRemoveTableFormat
        {
            get
            {
                return ResourceManager.GetString("InternalCacheRemoveTableFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        internal static string InternalCacheRight
        {
            get
            {
                return ResourceManager.GetString("InternalCacheRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SECOND.
        /// </summary>
        internal static string InternalCacheSecond
        {
            get
            {
                return ResourceManager.GetString("InternalCacheSecond", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        internal static string InternalCacheSelect
        {
            get
            {
                return ResourceManager.GetString("InternalCacheSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMALLDATETIME.
        /// </summary>
        internal static string InternalCacheSmallDateTime
        {
            get
            {
                return ResourceManager.GetString("InternalCacheSmallDateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMALLINT.
        /// </summary>
        internal static string InternalCacheSmallInt
        {
            get
            {
                return ResourceManager.GetString("InternalCacheSmallInt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMALLMONEY.
        /// </summary>
        internal static string InternalCacheSmallMoney
        {
            get
            {
                return ResourceManager.GetString("InternalCacheSmallMoney", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to InternalCache_VARIANT.
        /// </summary>
        internal static string InternalCacheInternalCache_Variant
        {
            get
            {
                return ResourceManager.GetString("InternalCacheInternalCache_Variant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string InternalCacheStar
        {
            get
            {
                return ResourceManager.GetString("InternalCacheStar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to STDEV.
        /// </summary>
        internal static string InternalCacheStdev
        {
            get
            {
                return ResourceManager.GetString("InternalCacheStdev", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to STDEVP.
        /// </summary>
        internal static string InternalCacheStdevP
        {
            get
            {
                return ResourceManager.GetString("InternalCacheStdevP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUBSTRING.
        /// </summary>
        internal static string InternalCacheSubstring
        {
            get
            {
                return ResourceManager.GetString("InternalCacheSubstring", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string InternalCacheSum
        {
            get
            {
                return ResourceManager.GetString("InternalCacheSum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string InternalCacheSumD
        {
            get
            {
                return ResourceManager.GetString("InternalCacheSumD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABLE.
        /// </summary>
        internal static string InternalCacheTable
        {
            get
            {
                return ResourceManager.GetString("InternalCacheTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TEXT.
        /// </summary>
        internal static string InternalCacheText
        {
            get
            {
                return ResourceManager.GetString("InternalCacheText", resourceCulture);
            }
        }

        internal static string InternalCacheByte
        {
            get
            {
                return ResourceManager.GetString("InternalCacheByte", resourceCulture);
            }
        }

        internal static string InternalCacheCast
        {
            get
            {
                return ResourceManager.GetString("InternalCacheCast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        internal static string InternalCacheTime
        {
            get
            {
                return ResourceManager.GetString("InternalCacheTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TMESTAMP.
        /// </summary>
        internal static string InternalCacheTimeStamp
        {
            get
            {
                return ResourceManager.GetString("InternalCacheTimeStamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TINYINT.
        /// </summary>
        internal static string InternalCacheTinyInt
        {
            get
            {
                return ResourceManager.GetString("InternalCacheTinyInt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TOP.
        /// </summary>
        internal static string InternalCacheTop
        {
            get
            {
                return ResourceManager.GetString("InternalCacheTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UNION ALL.
        /// </summary>
        internal static string InternalCacheUnionAll
        {
            get
            {
                return ResourceManager.GetString("InternalCacheUnionAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UNIQUEIDENTIFIER.
        /// </summary>
        internal static string InternalCacheUniqueIdentifier
        {
            get
            {
                return ResourceManager.GetString("InternalCacheUniqueIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VAR.
        /// </summary>
        internal static string InternalCacheVar
        {
            get
            {
                return ResourceManager.GetString("InternalCacheVar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VARBINARY.
        /// </summary>
        internal static string InternalCacheVarBinary
        {
            get
            {
                return ResourceManager.GetString("InternalCacheVarBinary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VARCHAR.
        /// </summary>
        internal static string InternalCacheVarChar
        {
            get
            {
                return ResourceManager.GetString("InternalCacheVarChar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VAR.
        /// </summary>
        internal static string InternalCacheVariance
        {
            get
            {
                return ResourceManager.GetString("InternalCacheVariance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VARP.
        /// </summary>
        internal static string InternalCacheVarP
        {
            get
            {
                return ResourceManager.GetString("InternalCacheVarP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WEEK.
        /// </summary>
        internal static string InternalCacheWeek
        {
            get
            {
                return ResourceManager.GetString("InternalCacheWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WEEKDAY.
        /// </summary>
        internal static string InternalCacheWeekDay
        {
            get
            {
                return ResourceManager.GetString("InternalCacheWeekDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WHERE.
        /// </summary>
        internal static string InternalCacheWhere
        {
            get
            {
                return ResourceManager.GetString("InternalCacheWhere", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WITH.
        /// </summary>
        internal static string InternalCacheWith
        {
            get
            {
                return ResourceManager.GetString("InternalCacheWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string InternalCacheXml
        {
            get
            {
                return ResourceManager.GetString("InternalCacheXml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        internal static string InternalCacheYear
        {
            get
            {
                return ResourceManager.GetString("InternalCacheYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        internal static string InternalCacheDayOfWeek
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDayOfWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        internal static string StandardDateTimeFormat
        {
            get
            {
                return ResourceManager.GetString("StandardDateTimeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string InternalCacheExtract
        {
            get
            {
                return ResourceManager.GetString("InternalCacheExtract", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to RowUnderscoreNumber function format string.
        /// </summary>
        internal static string RowUnderscoreNumber
        {
            get
            {
                return ResourceManager.GetString("RowUnderscoreNumber", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to over function format string.
        /// </summary>
        internal static string InternalCacheOver
        {
            get
            {
                return ResourceManager.GetString("InternalCacheOver", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to PartitionBy function format string.
        /// </summary>
        internal static string PartitionBy
        {
            get
            {
                return ResourceManager.GetString("PartitionBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to date_part(&apos;month&apos;, DATEADD(&apos;month&apos;, -1, CURRENT_DATE)).
        /// </summary>
        internal static string PreviousMonth
        {
            get
            {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to date_part(&apos;year&apos;, DATEADD(&apos;year&apos;, -1, CURRENT_DATE)).
        /// </summary>
        internal static string PreviousYear
        {
            get
            {
                return ResourceManager.GetString("PreviousYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to STARTS WITH.
        /// </summary>
        internal static string StartsWith
        {
            get
            {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to M/d/yyyy h:mm:ss tt.
        /// </summary>
        internal static string TimeZoneDateFormat
        {
            get
            {
                return ResourceManager.GetString("TimeZoneDateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TO_CHAR(CAST ({0} as DATE), &apos;YYYYMMDD&apos;).
        /// </summary>
        internal static string ToCharDateFormat
        {
            get
            {
                return ResourceManager.GetString("ToCharDateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TO_DATE({0}, &apos;{1}&apos;).
        /// </summary>
        internal static string ToDateStringFormatQuery
        {
            get
            {
                return ResourceManager.GetString("ToDateStringFormatQuery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TO_CHAR(CAST ({0} as TIMESTAMP), &apos;yyyyMMddHHMIss&apos;).
        /// </summary>
        internal static string ToCharDateTimeFormat
        {
            get
            {
                return ResourceManager.GetString("ToCharDateTimeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TO_CHAR(CAST ({0} as TIMESTAMP), &apos;HHMIss&apos;).
        /// </summary>
        internal static string ToCharTimeFormat
        {
            get
            {
                return ResourceManager.GetString("ToCharTimeFormat", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to DATEADD(&apos;year&apos;, -1, CURRENT_DATE).
        /// </summary>
        internal static string Yesterday
        {
            get
            {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string for the string_agg function..
        /// </summary>
        internal static string InternalCacheString_Agg
        {
            get
            {
                return ResourceManager.GetString("InternalCacheString_Agg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FIRST_VALUE().
        /// </summary>
        internal static string InternalCacheFirstValue
        {
            get
            {
                return ResourceManager.GetString("InternalCacheFirstValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LAST_VALUE().
        /// </summary>
        internal static string InternalCacheLastValue
        {
            get
            {
                return ResourceManager.GetString("InternalCacheLastValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ROW_NUMBER().
        /// </summary>
        internal static string InternalCacheRowNumber
        {
            get
            {
                return ResourceManager.GetString("InternalCacheRowNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RANK().
        /// </summary>
        internal static string InternalCacheRank
        {
            get
            {
                return ResourceManager.GetString("InternalCacheRank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DENSE_RANK().
        /// </summary>
        internal static string InternalCacheDenseRank
        {
            get
            {
                return ResourceManager.GetString("InternalCacheDenseRank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTILE.
        /// </summary>
        internal static string InternalCacheNtile
        {
            get
            {
                return ResourceManager.GetString("InternalCacheNtile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom_LOD_Table.
        /// </summary>
        internal static string CustomLODTableAliasName
        {
            get
            {
                return ResourceManager.GetString("CustomLODTableAliasName", resourceCulture);
            }
        }
    }
}
